import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Ink — Deep navy with warm sand.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const ink: ThemeConfig = {
  name: "ink",
  colors: {
    primary: "#1f3d75",
    primaryHover: "#152b55",
    background: "#f8f9fb",
    backgroundAlt: "#eef1f5",
    text: "#0f1524",
    textMuted: "#5d6779",
    border: "#e0e5ec",
    codeBackground: "#0f1524",
    codeBackgroundTop: "#0f1524",
    codeText: "#e8ecf3",
  },
  darkColors: {
    primary: "#e3c08a",
    primaryHover: "#efd6ad",
    background: "#0c1220",
    backgroundAlt: "#131b2c",
    text: "#e8ecf3",
    textMuted: "#8390a8",
    border: "#1e2739",
    codeBackground: "#080d17",
    codeBackgroundTop: "#080d17",
    codeText: "#e8ecf3",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1f3d75 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #946c1c 18%, transparent)",
    "color-code-line-warning-border": "#946c1c",
    "color-code-line-error": "color-mix(in srgb, #b23a4a 20%, transparent)",
    "color-code-line-error-border": "#b23a4a",
    "color-code-line-add": "color-mix(in srgb, #3f7050 16%, transparent)",
    "color-code-line-add-border": "#3f7050",
    "color-code-line-remove": "color-mix(in srgb, #b23a4a 14%, transparent)",
    "color-code-line-remove-border": "#b23a4a",
    "color-code-line-focus": "color-mix(in srgb, #1f3d75 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #0f1524 92%, #e8ecf3)",
    "color-code-title-text": "color-mix(in srgb, #e8ecf3 88%, #0f1524)",
    "color-code-title-border": "color-mix(in srgb, #e8ecf3 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e8ecf3 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e0e5ec 92%, transparent)",
    "color-backdrop": "rgba(87, 87, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eef1f5 62%, #f8f9fb)",
    "surface-line": "color-mix(in srgb, #e0e5ec 72%, #f8f9fb)",
    "brand-violet": "#6b4a94",
    "brand-cyan": "#1d6a7c",
    "brand-lime": "#3f7050",
    "brand-coral": "#b23a4a",
    "brand-navy": "color-mix(in srgb, #0f1524 70%, #f8f9fb)",
    "brand-violet-rgb": "107, 74, 148",
    "brand-cyan-rgb": "29, 106, 124",
    "brand-lime-rgb": "63, 112, 80",
    "brand-coral-rgb": "178, 58, 74",
    "accent-a": "#1f3d75",
    "accent-b": "#6b4a94",
    "accent-c": "#1d6a7c",
    "accent-warm": "#946c1c",
    "accent-cool": "#1f3d75",
    "accent-a-ink": "#1f3d75",
    "accent-b-ink": "#6b4a94",
    "accent-c-ink": "#1d6a7c",
    "accent-warm-ink": "#946c1c",
    "accent-cool-ink": "#1f3d75",
    "accent-coral-ink": "#b23a4a",
    "syntax-foreground": "#e8ecf3",
    "syntax-background": "#0f1524",
    "syntax-token-comment": "color-mix(in srgb, #e8ecf3 55%, #0f1524)",
    "syntax-token-punctuation": "color-mix(in srgb, #e8ecf3 72%, #0f1524)",
    "syntax-token-keyword": "#b79ae8",
    "syntax-token-string": "#8ac79b",
    "syntax-token-string-expression": "#8ac79b",
    "syntax-token-constant": "#e3c08a",
    "syntax-token-function": "#8fb2ee",
    "syntax-token-parameter": "#f0838f",
    "syntax-token-link": "#6cc3d4",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8fb2ee 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e3c08a 18%, transparent)",
    "color-code-line-warning-border": "#e3c08a",
    "color-code-line-error": "color-mix(in srgb, #f0838f 20%, transparent)",
    "color-code-line-error-border": "#f0838f",
    "color-code-line-add": "color-mix(in srgb, #8ac79b 16%, transparent)",
    "color-code-line-add-border": "#8ac79b",
    "color-code-line-remove": "color-mix(in srgb, #f0838f 14%, transparent)",
    "color-code-line-remove-border": "#f0838f",
    "color-code-line-focus": "color-mix(in srgb, #e3c08a 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #080d17 92%, #e8ecf3)",
    "color-code-title-text": "color-mix(in srgb, #e8ecf3 88%, #080d17)",
    "color-code-title-border": "color-mix(in srgb, #e8ecf3 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e8ecf3 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1e2739 92%, transparent)",
    "color-backdrop": "rgba(4, 6, 11, 0.62)",
    "surface-glass": "color-mix(in srgb, #131b2c 62%, #0c1220)",
    "surface-line": "color-mix(in srgb, #1e2739 72%, #0c1220)",
    "brand-violet": "#b79ae8",
    "brand-cyan": "#6cc3d4",
    "brand-lime": "#8ac79b",
    "brand-coral": "#f0838f",
    "brand-navy": "color-mix(in srgb, #e8ecf3 70%, #0c1220)",
    "brand-violet-rgb": "183, 154, 232",
    "brand-cyan-rgb": "108, 195, 212",
    "brand-lime-rgb": "138, 199, 155",
    "brand-coral-rgb": "240, 131, 143",
    "accent-a": "#e3c08a",
    "accent-b": "#b79ae8",
    "accent-c": "#6cc3d4",
    "accent-warm": "#e3c08a",
    "accent-cool": "#8fb2ee",
    "accent-a-ink": "#e3c08a",
    "accent-b-ink": "#b79ae8",
    "accent-c-ink": "#6cc3d4",
    "accent-warm-ink": "#e3c08a",
    "accent-cool-ink": "#8fb2ee",
    "accent-coral-ink": "#f0838f",
    "syntax-foreground": "#e8ecf3",
    "syntax-background": "#080d17",
    "syntax-token-comment": "color-mix(in srgb, #e8ecf3 55%, #080d17)",
    "syntax-token-punctuation": "color-mix(in srgb, #e8ecf3 72%, #080d17)",
    "syntax-token-keyword": "#b79ae8",
    "syntax-token-string": "#8ac79b",
    "syntax-token-string-expression": "#8ac79b",
    "syntax-token-constant": "#e3c08a",
    "syntax-token-function": "#8fb2ee",
    "syntax-token-parameter": "#f0838f",
    "syntax-token-link": "#6cc3d4",
  },
};
