import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Vitesse — Anthony Fu's Vitesse light and dark.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const vitesse: ThemeConfig = {
  name: "vitesse",
  colors: {
    primary: "#1e754f",
    primaryHover: "#155a3c",
    background: "#ffffff",
    backgroundAlt: "#f7f7f6",
    text: "#393a34",
    textMuted: "#75756c",
    border: "#e3e3dd",
    codeBackground: "#f7f7f6",
    codeBackgroundTop: "#f7f7f6",
    codeText: "#393a34",
  },
  darkColors: {
    primary: "#4d9375",
    primaryHover: "#6fb494",
    background: "#121212",
    backgroundAlt: "#1b1b1b",
    text: "#dbd7caee",
    textMuted: "#84848c",
    border: "#2c2c2c",
    codeBackground: "#0f0f0f",
    codeBackgroundTop: "#0f0f0f",
    codeText: "#dbd7ca",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #296aa3 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #a65e2b 18%, transparent)",
    "color-code-line-warning-border": "#a65e2b",
    "color-code-line-error": "color-mix(in srgb, #ab5959 20%, transparent)",
    "color-code-line-error-border": "#ab5959",
    "color-code-line-add": "color-mix(in srgb, #1e754f 16%, transparent)",
    "color-code-line-add-border": "#1e754f",
    "color-code-line-remove": "color-mix(in srgb, #ab5959 14%, transparent)",
    "color-code-line-remove-border": "#ab5959",
    "color-code-line-focus": "color-mix(in srgb, #1e754f 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f7f7f6 92%, #393a34)",
    "color-code-title-text": "color-mix(in srgb, #393a34 88%, #f7f7f6)",
    "color-code-title-border": "color-mix(in srgb, #393a34 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #393a34 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e3e3dd 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f7f7f6 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #e3e3dd 72%, #ffffff)",
    "brand-violet": "#6c51a3",
    "brand-cyan": "#2f8a89",
    "brand-lime": "#1e754f",
    "brand-coral": "#ab5959",
    "brand-navy": "color-mix(in srgb, #393a34 70%, #ffffff)",
    "brand-violet-rgb": "108, 81, 163",
    "brand-cyan-rgb": "47, 138, 137",
    "brand-lime-rgb": "30, 117, 79",
    "brand-coral-rgb": "171, 89, 89",
    "accent-a": "#1e754f",
    "accent-b": "#6c51a3",
    "accent-c": "#2f8a89",
    "accent-warm": "#a65e2b",
    "accent-cool": "#296aa3",
    "accent-a-ink": "#1e754f",
    "accent-b-ink": "#6c51a3",
    "accent-c-ink": "#2b7f7e",
    "accent-warm-ink": "#a65e2b",
    "accent-cool-ink": "#296aa3",
    "accent-coral-ink": "#ab5959",
    "shiki-foreground": "#393a34",
    "shiki-background": "#f7f7f6",
    "shiki-token-comment": "color-mix(in srgb, #393a34 55%, #f7f7f6)",
    "shiki-token-punctuation": "color-mix(in srgb, #393a34 72%, #f7f7f6)",
    "shiki-token-keyword": "#6c51a3",
    "shiki-token-string": "#1e754f",
    "shiki-token-string-expression": "#1e754f",
    "shiki-token-constant": "#a65e2b",
    "shiki-token-function": "#296aa3",
    "shiki-token-parameter": "#ab5959",
    "shiki-token-link": "#2f8a89",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #6394bf 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d4976c 18%, transparent)",
    "color-code-line-warning-border": "#d4976c",
    "color-code-line-error": "color-mix(in srgb, #cb7676 20%, transparent)",
    "color-code-line-error-border": "#cb7676",
    "color-code-line-add": "color-mix(in srgb, #4d9375 16%, transparent)",
    "color-code-line-add-border": "#4d9375",
    "color-code-line-remove": "color-mix(in srgb, #cb7676 14%, transparent)",
    "color-code-line-remove-border": "#cb7676",
    "color-code-line-focus": "color-mix(in srgb, #4d9375 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0f0f0f 92%, #dbd7ca)",
    "color-code-title-text": "color-mix(in srgb, #dbd7ca 88%, #0f0f0f)",
    "color-code-title-border": "color-mix(in srgb, #dbd7ca 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #dbd7ca 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2c2c2c 92%, transparent)",
    "color-backdrop": "rgba(6, 6, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #1b1b1b 62%, #121212)",
    "surface-line": "color-mix(in srgb, #2c2c2c 72%, #121212)",
    "brand-violet": "#a08cd0",
    "brand-cyan": "#5eaab5",
    "brand-lime": "#4d9375",
    "brand-coral": "#cb7676",
    "brand-navy": "color-mix(in srgb, #dbd7caee 70%, #121212)",
    "brand-violet-rgb": "160, 140, 208",
    "brand-cyan-rgb": "94, 170, 181",
    "brand-lime-rgb": "77, 147, 117",
    "brand-coral-rgb": "203, 118, 118",
    "accent-a": "#4d9375",
    "accent-b": "#a08cd0",
    "accent-c": "#5eaab5",
    "accent-warm": "#d4976c",
    "accent-cool": "#6394bf",
    "accent-a-ink": "#4d9375",
    "accent-b-ink": "#a08cd0",
    "accent-c-ink": "#5eaab5",
    "accent-warm-ink": "#d4976c",
    "accent-cool-ink": "#6394bf",
    "accent-coral-ink": "#cb7676",
    "shiki-foreground": "#dbd7ca",
    "shiki-background": "#0f0f0f",
    "shiki-token-comment": "color-mix(in srgb, #dbd7ca 55%, #0f0f0f)",
    "shiki-token-punctuation": "color-mix(in srgb, #dbd7ca 72%, #0f0f0f)",
    "shiki-token-keyword": "#a08cd0",
    "shiki-token-string": "#4d9375",
    "shiki-token-string-expression": "#4d9375",
    "shiki-token-constant": "#d4976c",
    "shiki-token-function": "#6394bf",
    "shiki-token-parameter": "#cb7676",
    "shiki-token-link": "#5eaab5",
  },
};

export default vitesse;
