import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Zenburn — The classic low-contrast scheme for long sessions.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const zenburn: ThemeConfig = {
  name: "zenburn",
  colors: {
    primary: "#62704b",
    primaryHover: "#53603f",
    background: "#f4f4ec",
    backgroundAlt: "#e8e8dc",
    text: "#33322c",
    textMuted: "#6b6a5e",
    border: "#d4d3c4",
    codeBackground: "#3f3f3f",
    codeBackgroundTop: "#3f3f3f",
    codeText: "#dcdccc",
  },
  darkColors: {
    primary: "#8cd0d3",
    primaryHover: "#b0e0e3",
    background: "#3f3f3f",
    backgroundAlt: "#4a4a4a",
    text: "#dcdccc",
    textMuted: "#abab9c",
    border: "#585858",
    codeBackground: "#383838",
    codeBackgroundTop: "#383838",
    codeText: "#dcdccc",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5b6f88 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8a7444 18%, transparent)",
    "color-code-line-warning-border": "#8a7444",
    "color-code-line-error": "color-mix(in srgb, #9d5b52 20%, transparent)",
    "color-code-line-error-border": "#9d5b52",
    "color-code-line-add": "color-mix(in srgb, #6a7a52 16%, transparent)",
    "color-code-line-add-border": "#6a7a52",
    "color-code-line-remove": "color-mix(in srgb, #9d5b52 14%, transparent)",
    "color-code-line-remove-border": "#9d5b52",
    "color-code-line-focus": "color-mix(in srgb, #62704b 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #3f3f3f 92%, #dcdccc)",
    "color-code-title-text": "color-mix(in srgb, #dcdccc 88%, #3f3f3f)",
    "color-code-title-border": "color-mix(in srgb, #dcdccc 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #dcdccc 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d4d3c4 92%, transparent)",
    "color-backdrop": "rgba(85, 85, 83, 0.62)",
    "surface-glass": "color-mix(in srgb, #e8e8dc 62%, #f4f4ec)",
    "surface-line": "color-mix(in srgb, #d4d3c4 72%, #f4f4ec)",
    "brand-violet": "#7d5f7a",
    "brand-cyan": "#4f7570",
    "brand-lime": "#6a7a52",
    "brand-coral": "#9d5b52",
    "brand-navy": "color-mix(in srgb, #33322c 70%, #f4f4ec)",
    "brand-violet-rgb": "125, 95, 122",
    "brand-cyan-rgb": "79, 117, 112",
    "brand-lime-rgb": "106, 122, 82",
    "brand-coral-rgb": "157, 91, 82",
    "accent-a": "#62704b",
    "accent-b": "#7d5f7a",
    "accent-c": "#4f7570",
    "accent-warm": "#8a7444",
    "accent-cool": "#5b6f88",
    "accent-a-ink": "#62704b",
    "accent-b-ink": "#7d5f7a",
    "accent-c-ink": "#4f7570",
    "accent-warm-ink": "#7f6b3f",
    "accent-cool-ink": "#5b6f88",
    "accent-coral-ink": "#9d5b52",
    "shiki-foreground": "#dcdccc",
    "shiki-background": "#3f3f3f",
    "shiki-token-comment": "color-mix(in srgb, #dcdccc 55%, #3f3f3f)",
    "shiki-token-punctuation": "color-mix(in srgb, #dcdccc 72%, #3f3f3f)",
    "shiki-token-keyword": "#dc8cc3",
    "shiki-token-string": "#7f9f7f",
    "shiki-token-string-expression": "#7f9f7f",
    "shiki-token-constant": "#f0dfaf",
    "shiki-token-function": "#8cd0d3",
    "shiki-token-parameter": "#cc9393",
    "shiki-token-link": "#93e0e3",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8cd0d3 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f0dfaf 18%, transparent)",
    "color-code-line-warning-border": "#f0dfaf",
    "color-code-line-error": "color-mix(in srgb, #cc9393 20%, transparent)",
    "color-code-line-error-border": "#cc9393",
    "color-code-line-add": "color-mix(in srgb, #7f9f7f 16%, transparent)",
    "color-code-line-add-border": "#7f9f7f",
    "color-code-line-remove": "color-mix(in srgb, #cc9393 14%, transparent)",
    "color-code-line-remove-border": "#cc9393",
    "color-code-line-focus": "color-mix(in srgb, #8cd0d3 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #383838 92%, #dcdccc)",
    "color-code-title-text": "color-mix(in srgb, #dcdccc 88%, #383838)",
    "color-code-title-border": "color-mix(in srgb, #dcdccc 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #dcdccc 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #585858 92%, transparent)",
    "color-backdrop": "rgba(22, 22, 22, 0.62)",
    "surface-glass": "color-mix(in srgb, #4a4a4a 62%, #3f3f3f)",
    "surface-line": "color-mix(in srgb, #585858 72%, #3f3f3f)",
    "brand-violet": "#dc8cc3",
    "brand-cyan": "#93e0e3",
    "brand-lime": "#7f9f7f",
    "brand-coral": "#cc9393",
    "brand-navy": "color-mix(in srgb, #dcdccc 70%, #3f3f3f)",
    "brand-violet-rgb": "220, 140, 195",
    "brand-cyan-rgb": "147, 224, 227",
    "brand-lime-rgb": "127, 159, 127",
    "brand-coral-rgb": "204, 147, 147",
    "accent-a": "#8cd0d3",
    "accent-b": "#dc8cc3",
    "accent-c": "#93e0e3",
    "accent-warm": "#f0dfaf",
    "accent-cool": "#8cd0d3",
    "accent-a-ink": "#8cd0d3",
    "accent-b-ink": "#df95c8",
    "accent-c-ink": "#93e0e3",
    "accent-warm-ink": "#f0dfaf",
    "accent-cool-ink": "#8cd0d3",
    "accent-coral-ink": "#d2a0a0",
    "shiki-foreground": "#dcdccc",
    "shiki-background": "#383838",
    "shiki-token-comment": "color-mix(in srgb, #dcdccc 55%, #383838)",
    "shiki-token-punctuation": "color-mix(in srgb, #dcdccc 72%, #383838)",
    "shiki-token-keyword": "#dc8cc3",
    "shiki-token-string": "#7f9f7f",
    "shiki-token-string-expression": "#7f9f7f",
    "shiki-token-constant": "#f0dfaf",
    "shiki-token-function": "#8cd0d3",
    "shiki-token-parameter": "#cc9393",
    "shiki-token-link": "#93e0e3",
  },
};

export default zenburn;
