import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Catppuccin — Catppuccin Latte and Frappé.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccinFrappe: ThemeConfig = {
  name: "catppuccin-frappe",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#8caaee",
    primaryHover: "#99d1db",
    background: "#303446",
    backgroundAlt: "#292c3c",
    text: "#c6d0f5",
    textMuted: "#949cbb",
    border: "#626880",
    codeBackground: "#303446",
    codeBackgroundTop: "#303446",
    codeText: "#c6d0f5",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8caaee 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e5c890 18%, transparent)",
    "color-code-line-warning-border": "#e5c890",
    "color-code-line-error": "color-mix(in srgb, #e78284 20%, transparent)",
    "color-code-line-error-border": "#e78284",
    "color-code-line-add": "color-mix(in srgb, #a6d189 16%, transparent)",
    "color-code-line-add-border": "#a6d189",
    "color-code-line-remove": "color-mix(in srgb, #e78284 14%, transparent)",
    "color-code-line-remove-border": "#e78284",
    "color-code-line-focus": "color-mix(in srgb, #8caaee 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #303446 92%, #c6d0f5)",
    "color-code-title-text": "color-mix(in srgb, #c6d0f5 88%, #303446)",
    "color-code-title-border": "color-mix(in srgb, #c6d0f5 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #c6d0f5 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #626880 92%, transparent)",
    "color-backdrop": "rgba(17, 18, 25, 0.62)",
    "surface-glass": "color-mix(in srgb, #292c3c 62%, #303446)",
    "surface-line": "color-mix(in srgb, #626880 72%, #303446)",
    "brand-violet": "#f4b8e4",
    "brand-cyan": "#81c8be",
    "brand-lime": "#a6d189",
    "brand-coral": "#e78284",
    "brand-navy": "color-mix(in srgb, #c6d0f5 70%, #303446)",
    "brand-violet-rgb": "244, 184, 228",
    "brand-cyan-rgb": "129, 200, 190",
    "brand-lime-rgb": "166, 209, 137",
    "brand-coral-rgb": "231, 130, 132",
    "accent-a": "#8caaee",
    "accent-b": "#f4b8e4",
    "accent-c": "#81c8be",
    "accent-warm": "#e5c890",
    "accent-cool": "#8caaee",
    "accent-a-ink": "#8caaee",
    "accent-b-ink": "#f4b8e4",
    "accent-c-ink": "#81c8be",
    "accent-warm-ink": "#e5c890",
    "accent-cool-ink": "#8caaee",
    "accent-coral-ink": "#e78284",
    "syntax-foreground": "#c6d0f5",
    "syntax-background": "#303446",
    "syntax-token-comment": "#949cbb",
    "syntax-token-punctuation": "#949cbb",
    "syntax-token-keyword": "#ca9ee6",
    "syntax-token-string": "#a6d189",
    "syntax-token-string-expression": "#a6d189",
    "syntax-token-constant": "#ef9f76",
    "syntax-token-function": "#8caaee",
    "syntax-token-parameter": "#ea999c",
    "syntax-token-link": "#babbf1",
  },
};
