import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Catppuccin — Catppuccin Latte and Macchiato.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccinMacchiato: ThemeConfig = {
  name: "catppuccin-macchiato",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#8aadf4",
    primaryHover: "#91d7e3",
    background: "#24273a",
    backgroundAlt: "#1e2030",
    text: "#cad3f5",
    textMuted: "#939ab7",
    border: "#5b6078",
    codeBackground: "#24273a",
    codeBackgroundTop: "#24273a",
    codeText: "#cad3f5",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8aadf4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #eed49f 18%, transparent)",
    "color-code-line-warning-border": "#eed49f",
    "color-code-line-error": "color-mix(in srgb, #ed8796 20%, transparent)",
    "color-code-line-error-border": "#ed8796",
    "color-code-line-add": "color-mix(in srgb, #a6da95 16%, transparent)",
    "color-code-line-add-border": "#a6da95",
    "color-code-line-remove": "color-mix(in srgb, #ed8796 14%, transparent)",
    "color-code-line-remove-border": "#ed8796",
    "color-code-line-focus": "color-mix(in srgb, #8aadf4 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #24273a 92%, #cad3f5)",
    "color-code-title-text": "color-mix(in srgb, #cad3f5 88%, #24273a)",
    "color-code-title-border": "color-mix(in srgb, #cad3f5 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cad3f5 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #5b6078 92%, transparent)",
    "color-backdrop": "rgba(13, 14, 20, 0.62)",
    "surface-glass": "color-mix(in srgb, #1e2030 62%, #24273a)",
    "surface-line": "color-mix(in srgb, #5b6078 72%, #24273a)",
    "brand-violet": "#f5bde6",
    "brand-cyan": "#8bd5ca",
    "brand-lime": "#a6da95",
    "brand-coral": "#ed8796",
    "brand-navy": "color-mix(in srgb, #cad3f5 70%, #24273a)",
    "brand-violet-rgb": "245, 189, 230",
    "brand-cyan-rgb": "139, 213, 202",
    "brand-lime-rgb": "166, 218, 149",
    "brand-coral-rgb": "237, 135, 150",
    "accent-a": "#8aadf4",
    "accent-b": "#f5bde6",
    "accent-c": "#8bd5ca",
    "accent-warm": "#eed49f",
    "accent-cool": "#8aadf4",
    "accent-a-ink": "#8aadf4",
    "accent-b-ink": "#f5bde6",
    "accent-c-ink": "#8bd5ca",
    "accent-warm-ink": "#eed49f",
    "accent-cool-ink": "#8aadf4",
    "accent-coral-ink": "#ed8796",
    "syntax-foreground": "#cad3f5",
    "syntax-background": "#24273a",
    "syntax-token-comment": "#939ab7",
    "syntax-token-punctuation": "#939ab7",
    "syntax-token-keyword": "#c6a0f6",
    "syntax-token-string": "#a6da95",
    "syntax-token-string-expression": "#a6da95",
    "syntax-token-constant": "#f5a97f",
    "syntax-token-function": "#8aadf4",
    "syntax-token-parameter": "#ee99a0",
    "syntax-token-link": "#b7bdf8",
  },
};
