import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Catppuccin — Catppuccin Latte and Mocha.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccin: ThemeConfig = {
  name: "catppuccin",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#89b4fa",
    primaryHover: "#b4d0fd",
    background: "#1e1e2e",
    backgroundAlt: "#181825",
    text: "#cdd6f4",
    textMuted: "#a6adc8",
    border: "#313244",
    codeBackground: "#11111b",
    codeBackgroundTop: "#11111b",
    codeText: "#cdd6f4",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #89b4fa 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f9e2af 18%, transparent)",
    "color-code-line-warning-border": "#f9e2af",
    "color-code-line-error": "color-mix(in srgb, #f38ba8 20%, transparent)",
    "color-code-line-error-border": "#f38ba8",
    "color-code-line-add": "color-mix(in srgb, #a6e3a1 16%, transparent)",
    "color-code-line-add-border": "#a6e3a1",
    "color-code-line-remove": "color-mix(in srgb, #f38ba8 14%, transparent)",
    "color-code-line-remove-border": "#f38ba8",
    "color-code-line-focus": "color-mix(in srgb, #89b4fa 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #11111b 92%, #cdd6f4)",
    "color-code-title-text": "color-mix(in srgb, #cdd6f4 88%, #11111b)",
    "color-code-title-border": "color-mix(in srgb, #cdd6f4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cdd6f4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #313244 92%, transparent)",
    "color-backdrop": "rgba(11, 11, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #181825 62%, #1e1e2e)",
    "surface-line": "color-mix(in srgb, #313244 72%, #1e1e2e)",
    "brand-violet": "#cba6f7",
    "brand-cyan": "#94e2d5",
    "brand-lime": "#a6e3a1",
    "brand-coral": "#f38ba8",
    "brand-navy": "color-mix(in srgb, #cdd6f4 70%, #1e1e2e)",
    "brand-violet-rgb": "203, 166, 247",
    "brand-cyan-rgb": "148, 226, 213",
    "brand-lime-rgb": "166, 227, 161",
    "brand-coral-rgb": "243, 139, 168",
    "accent-a": "#89b4fa",
    "accent-b": "#cba6f7",
    "accent-c": "#94e2d5",
    "accent-warm": "#f9e2af",
    "accent-cool": "#89b4fa",
    "accent-a-ink": "#89b4fa",
    "accent-b-ink": "#cba6f7",
    "accent-c-ink": "#94e2d5",
    "accent-warm-ink": "#f9e2af",
    "accent-cool-ink": "#89b4fa",
    "accent-coral-ink": "#f38ba8",
    "syntax-foreground": "#cdd6f4",
    "syntax-background": "#11111b",
    "syntax-token-comment": "color-mix(in srgb, #cdd6f4 55%, #11111b)",
    "syntax-token-punctuation": "color-mix(in srgb, #cdd6f4 72%, #11111b)",
    "syntax-token-keyword": "#cba6f7",
    "syntax-token-string": "#a6e3a1",
    "syntax-token-string-expression": "#a6e3a1",
    "syntax-token-constant": "#f9e2af",
    "syntax-token-function": "#89b4fa",
    "syntax-token-parameter": "#f38ba8",
    "syntax-token-link": "#94e2d5",
  },
};

/**
 * Catppuccin — Catppuccin Latte and Frappé.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccinFrappe: ThemeConfig = {
  name: "catppuccin-frappe",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#8caaee",
    primaryHover: "#99d1db",
    background: "#303446",
    backgroundAlt: "#292c3c",
    text: "#c6d0f5",
    textMuted: "#949cbb",
    border: "#626880",
    codeBackground: "#303446",
    codeBackgroundTop: "#303446",
    codeText: "#c6d0f5",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8caaee 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e5c890 18%, transparent)",
    "color-code-line-warning-border": "#e5c890",
    "color-code-line-error": "color-mix(in srgb, #e78284 20%, transparent)",
    "color-code-line-error-border": "#e78284",
    "color-code-line-add": "color-mix(in srgb, #a6d189 16%, transparent)",
    "color-code-line-add-border": "#a6d189",
    "color-code-line-remove": "color-mix(in srgb, #e78284 14%, transparent)",
    "color-code-line-remove-border": "#e78284",
    "color-code-line-focus": "color-mix(in srgb, #8caaee 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #303446 92%, #c6d0f5)",
    "color-code-title-text": "color-mix(in srgb, #c6d0f5 88%, #303446)",
    "color-code-title-border": "color-mix(in srgb, #c6d0f5 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #c6d0f5 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #626880 92%, transparent)",
    "color-backdrop": "rgba(17, 18, 25, 0.62)",
    "surface-glass": "color-mix(in srgb, #292c3c 62%, #303446)",
    "surface-line": "color-mix(in srgb, #626880 72%, #303446)",
    "brand-violet": "#f4b8e4",
    "brand-cyan": "#81c8be",
    "brand-lime": "#a6d189",
    "brand-coral": "#e78284",
    "brand-navy": "color-mix(in srgb, #c6d0f5 70%, #303446)",
    "brand-violet-rgb": "244, 184, 228",
    "brand-cyan-rgb": "129, 200, 190",
    "brand-lime-rgb": "166, 209, 137",
    "brand-coral-rgb": "231, 130, 132",
    "accent-a": "#8caaee",
    "accent-b": "#f4b8e4",
    "accent-c": "#81c8be",
    "accent-warm": "#e5c890",
    "accent-cool": "#8caaee",
    "accent-a-ink": "#8caaee",
    "accent-b-ink": "#f4b8e4",
    "accent-c-ink": "#81c8be",
    "accent-warm-ink": "#e5c890",
    "accent-cool-ink": "#8caaee",
    "accent-coral-ink": "#e78284",
    "syntax-foreground": "#c6d0f5",
    "syntax-background": "#303446",
    "syntax-token-comment": "#949cbb",
    "syntax-token-punctuation": "#949cbb",
    "syntax-token-keyword": "#ca9ee6",
    "syntax-token-string": "#a6d189",
    "syntax-token-string-expression": "#a6d189",
    "syntax-token-constant": "#ef9f76",
    "syntax-token-function": "#8caaee",
    "syntax-token-parameter": "#ea999c",
    "syntax-token-link": "#babbf1",
  },
};

/**
 * Catppuccin — Catppuccin Latte and Macchiato.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccinMacchiato: ThemeConfig = {
  name: "catppuccin-macchiato",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#8aadf4",
    primaryHover: "#91d7e3",
    background: "#24273a",
    backgroundAlt: "#1e2030",
    text: "#cad3f5",
    textMuted: "#939ab7",
    border: "#5b6078",
    codeBackground: "#24273a",
    codeBackgroundTop: "#24273a",
    codeText: "#cad3f5",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8aadf4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #eed49f 18%, transparent)",
    "color-code-line-warning-border": "#eed49f",
    "color-code-line-error": "color-mix(in srgb, #ed8796 20%, transparent)",
    "color-code-line-error-border": "#ed8796",
    "color-code-line-add": "color-mix(in srgb, #a6da95 16%, transparent)",
    "color-code-line-add-border": "#a6da95",
    "color-code-line-remove": "color-mix(in srgb, #ed8796 14%, transparent)",
    "color-code-line-remove-border": "#ed8796",
    "color-code-line-focus": "color-mix(in srgb, #8aadf4 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #24273a 92%, #cad3f5)",
    "color-code-title-text": "color-mix(in srgb, #cad3f5 88%, #24273a)",
    "color-code-title-border": "color-mix(in srgb, #cad3f5 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cad3f5 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #5b6078 92%, transparent)",
    "color-backdrop": "rgba(13, 14, 20, 0.62)",
    "surface-glass": "color-mix(in srgb, #1e2030 62%, #24273a)",
    "surface-line": "color-mix(in srgb, #5b6078 72%, #24273a)",
    "brand-violet": "#f5bde6",
    "brand-cyan": "#8bd5ca",
    "brand-lime": "#a6da95",
    "brand-coral": "#ed8796",
    "brand-navy": "color-mix(in srgb, #cad3f5 70%, #24273a)",
    "brand-violet-rgb": "245, 189, 230",
    "brand-cyan-rgb": "139, 213, 202",
    "brand-lime-rgb": "166, 218, 149",
    "brand-coral-rgb": "237, 135, 150",
    "accent-a": "#8aadf4",
    "accent-b": "#f5bde6",
    "accent-c": "#8bd5ca",
    "accent-warm": "#eed49f",
    "accent-cool": "#8aadf4",
    "accent-a-ink": "#8aadf4",
    "accent-b-ink": "#f5bde6",
    "accent-c-ink": "#8bd5ca",
    "accent-warm-ink": "#eed49f",
    "accent-cool-ink": "#8aadf4",
    "accent-coral-ink": "#ed8796",
    "syntax-foreground": "#cad3f5",
    "syntax-background": "#24273a",
    "syntax-token-comment": "#939ab7",
    "syntax-token-punctuation": "#939ab7",
    "syntax-token-keyword": "#c6a0f6",
    "syntax-token-string": "#a6da95",
    "syntax-token-string-expression": "#a6da95",
    "syntax-token-constant": "#f5a97f",
    "syntax-token-function": "#8aadf4",
    "syntax-token-parameter": "#ee99a0",
    "syntax-token-link": "#b7bdf8",
  },
};

export default catppuccin;
