import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Catppuccin — Catppuccin Latte and Mocha.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const catppuccin: ThemeConfig = {
  name: "catppuccin",
  colors: {
    primary: "#1d62eb",
    primaryHover: "#114ac7",
    background: "#eff1f5",
    backgroundAlt: "#e6e9ef",
    text: "#4c4f69",
    textMuted: "#686b80",
    border: "#ccd0da",
    codeBackground: "#e6e9ef",
    codeBackgroundTop: "#e6e9ef",
    codeText: "#4c4f69",
  },
  darkColors: {
    primary: "#89b4fa",
    primaryHover: "#b4d0fd",
    background: "#1e1e2e",
    backgroundAlt: "#181825",
    text: "#cdd6f4",
    textMuted: "#a6adc8",
    border: "#313244",
    codeBackground: "#11111b",
    codeBackgroundTop: "#11111b",
    codeText: "#cdd6f4",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1e66f5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #df8e1d 18%, transparent)",
    "color-code-line-warning-border": "#df8e1d",
    "color-code-line-error": "color-mix(in srgb, #d20f39 20%, transparent)",
    "color-code-line-error-border": "#d20f39",
    "color-code-line-add": "color-mix(in srgb, #40a02b 16%, transparent)",
    "color-code-line-add-border": "#40a02b",
    "color-code-line-remove": "color-mix(in srgb, #d20f39 14%, transparent)",
    "color-code-line-remove-border": "#d20f39",
    "color-code-line-focus": "color-mix(in srgb, #1d62eb 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e6e9ef 92%, #4c4f69)",
    "color-code-title-text": "color-mix(in srgb, #4c4f69 88%, #e6e9ef)",
    "color-code-title-border": "color-mix(in srgb, #4c4f69 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #4c4f69 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ccd0da 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #e6e9ef 62%, #eff1f5)",
    "surface-line": "color-mix(in srgb, #ccd0da 72%, #eff1f5)",
    "brand-violet": "#8839ef",
    "brand-cyan": "#179299",
    "brand-lime": "#40a02b",
    "brand-coral": "#d20f39",
    "brand-navy": "color-mix(in srgb, #4c4f69 70%, #eff1f5)",
    "brand-violet-rgb": "136, 57, 239",
    "brand-cyan-rgb": "23, 146, 153",
    "brand-lime-rgb": "64, 160, 43",
    "brand-coral-rgb": "210, 15, 57",
    "accent-a": "#1d62eb",
    "accent-b": "#8839ef",
    "accent-c": "#179299",
    "accent-warm": "#df8e1d",
    "accent-cool": "#1e66f5",
    "accent-a-ink": "#1d62eb",
    "accent-b-ink": "#8839ef",
    "accent-c-ink": "#12757a",
    "accent-warm-ink": "#986114",
    "accent-cool-ink": "#1d62eb",
    "accent-coral-ink": "#d20f39",
    "syntax-foreground": "#4c4f69",
    "syntax-background": "#e6e9ef",
    "syntax-token-comment": "color-mix(in srgb, #4c4f69 55%, #e6e9ef)",
    "syntax-token-punctuation": "color-mix(in srgb, #4c4f69 72%, #e6e9ef)",
    "syntax-token-keyword": "#8839ef",
    "syntax-token-string": "#40a02b",
    "syntax-token-string-expression": "#40a02b",
    "syntax-token-constant": "#df8e1d",
    "syntax-token-function": "#1e66f5",
    "syntax-token-parameter": "#d20f39",
    "syntax-token-link": "#179299",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #89b4fa 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f9e2af 18%, transparent)",
    "color-code-line-warning-border": "#f9e2af",
    "color-code-line-error": "color-mix(in srgb, #f38ba8 20%, transparent)",
    "color-code-line-error-border": "#f38ba8",
    "color-code-line-add": "color-mix(in srgb, #a6e3a1 16%, transparent)",
    "color-code-line-add-border": "#a6e3a1",
    "color-code-line-remove": "color-mix(in srgb, #f38ba8 14%, transparent)",
    "color-code-line-remove-border": "#f38ba8",
    "color-code-line-focus": "color-mix(in srgb, #89b4fa 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #11111b 92%, #cdd6f4)",
    "color-code-title-text": "color-mix(in srgb, #cdd6f4 88%, #11111b)",
    "color-code-title-border": "color-mix(in srgb, #cdd6f4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cdd6f4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #313244 92%, transparent)",
    "color-backdrop": "rgba(11, 11, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #181825 62%, #1e1e2e)",
    "surface-line": "color-mix(in srgb, #313244 72%, #1e1e2e)",
    "brand-violet": "#cba6f7",
    "brand-cyan": "#94e2d5",
    "brand-lime": "#a6e3a1",
    "brand-coral": "#f38ba8",
    "brand-navy": "color-mix(in srgb, #cdd6f4 70%, #1e1e2e)",
    "brand-violet-rgb": "203, 166, 247",
    "brand-cyan-rgb": "148, 226, 213",
    "brand-lime-rgb": "166, 227, 161",
    "brand-coral-rgb": "243, 139, 168",
    "accent-a": "#89b4fa",
    "accent-b": "#cba6f7",
    "accent-c": "#94e2d5",
    "accent-warm": "#f9e2af",
    "accent-cool": "#89b4fa",
    "accent-a-ink": "#89b4fa",
    "accent-b-ink": "#cba6f7",
    "accent-c-ink": "#94e2d5",
    "accent-warm-ink": "#f9e2af",
    "accent-cool-ink": "#89b4fa",
    "accent-coral-ink": "#f38ba8",
    "syntax-foreground": "#cdd6f4",
    "syntax-background": "#11111b",
    "syntax-token-comment": "color-mix(in srgb, #cdd6f4 55%, #11111b)",
    "syntax-token-punctuation": "color-mix(in srgb, #cdd6f4 72%, #11111b)",
    "syntax-token-keyword": "#cba6f7",
    "syntax-token-string": "#a6e3a1",
    "syntax-token-string-expression": "#a6e3a1",
    "syntax-token-constant": "#f9e2af",
    "syntax-token-function": "#89b4fa",
    "syntax-token-parameter": "#f38ba8",
    "syntax-token-link": "#94e2d5",
  },
};

export default catppuccin;
