import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Fuji — Mountain festival poster — forest, dawn orange and open sky.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const fuji: ThemeConfig = {
  name: "fuji",
  colors: {
    primary: "#0f7a5f",
    primaryHover: "#0a5943",
    background: "#fbfaf5",
    backgroundAlt: "#f0efe4",
    text: "#16211c",
    textMuted: "#5b6a5f",
    border: "#dcdccd",
    codeBackground: "#16211c",
    codeBackgroundTop: "#16211c",
    codeText: "#eaf0ea",
  },
  darkColors: {
    primary: "#4fd39b",
    primaryHover: "#7fe3b8",
    background: "#101815",
    backgroundAlt: "#17211c",
    text: "#e6ede7",
    textMuted: "#8a9a8f",
    border: "#22302a",
    codeBackground: "#0b110e",
    codeBackgroundTop: "#0b110e",
    codeText: "#e6ede7",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2a6d9c 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #b8790f 18%, transparent)",
    "color-code-line-warning-border": "#b8790f",
    "color-code-line-error": "color-mix(in srgb, #d2542f 20%, transparent)",
    "color-code-line-error-border": "#d2542f",
    "color-code-line-add": "color-mix(in srgb, #0f7a5f 16%, transparent)",
    "color-code-line-add-border": "#0f7a5f",
    "color-code-line-remove": "color-mix(in srgb, #d2542f 14%, transparent)",
    "color-code-line-remove-border": "#d2542f",
    "color-code-line-focus": "color-mix(in srgb, #0f7a5f 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #16211c 92%, #eaf0ea)",
    "color-code-title-text": "color-mix(in srgb, #eaf0ea 88%, #16211c)",
    "color-code-title-border": "color-mix(in srgb, #eaf0ea 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #eaf0ea 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dcdccd 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #f0efe4 62%, #fbfaf5)",
    "surface-line": "color-mix(in srgb, #dcdccd 72%, #fbfaf5)",
    "brand-violet": "#8a4a72",
    "brand-cyan": "#0f7f86",
    "brand-lime": "#0f7a5f",
    "brand-coral": "#d2542f",
    "brand-navy": "color-mix(in srgb, #16211c 70%, #fbfaf5)",
    "brand-violet-rgb": "138, 74, 114",
    "brand-cyan-rgb": "15, 127, 134",
    "brand-lime-rgb": "15, 122, 95",
    "brand-coral-rgb": "210, 84, 47",
    "accent-a": "#0f7a5f",
    "accent-b": "#8a4a72",
    "accent-c": "#0f7f86",
    "accent-warm": "#b8790f",
    "accent-cool": "#2a6d9c",
    "accent-a-ink": "#0f7a5f",
    "accent-b-ink": "#8a4a72",
    "accent-c-ink": "#0f7f86",
    "accent-warm-ink": "#9b660d",
    "accent-cool-ink": "#2a6d9c",
    "accent-coral-ink": "#c14d2b",
    "shiki-foreground": "#eaf0ea",
    "shiki-background": "#16211c",
    "shiki-token-comment": "color-mix(in srgb, #eaf0ea 55%, #16211c)",
    "shiki-token-punctuation": "color-mix(in srgb, #eaf0ea 72%, #16211c)",
    "shiki-token-keyword": "#d49ac0",
    "shiki-token-string": "#4fd39b",
    "shiki-token-string-expression": "#4fd39b",
    "shiki-token-constant": "#ffcc5c",
    "shiki-token-function": "#6fbfe8",
    "shiki-token-parameter": "#ff8a5c",
    "shiki-token-link": "#5fd6cf",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #6fbfe8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffcc5c 18%, transparent)",
    "color-code-line-warning-border": "#ffcc5c",
    "color-code-line-error": "color-mix(in srgb, #ff8a5c 20%, transparent)",
    "color-code-line-error-border": "#ff8a5c",
    "color-code-line-add": "color-mix(in srgb, #4fd39b 16%, transparent)",
    "color-code-line-add-border": "#4fd39b",
    "color-code-line-remove": "color-mix(in srgb, #ff8a5c 14%, transparent)",
    "color-code-line-remove-border": "#ff8a5c",
    "color-code-line-focus": "color-mix(in srgb, #4fd39b 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0b110e 92%, #e6ede7)",
    "color-code-title-text": "color-mix(in srgb, #e6ede7 88%, #0b110e)",
    "color-code-title-border": "color-mix(in srgb, #e6ede7 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6ede7 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #22302a 92%, transparent)",
    "color-backdrop": "rgba(6, 8, 7, 0.62)",
    "surface-glass": "color-mix(in srgb, #17211c 62%, #101815)",
    "surface-line": "color-mix(in srgb, #22302a 72%, #101815)",
    "brand-violet": "#d49ac0",
    "brand-cyan": "#5fd6cf",
    "brand-lime": "#4fd39b",
    "brand-coral": "#ff8a5c",
    "brand-navy": "color-mix(in srgb, #e6ede7 70%, #101815)",
    "brand-violet-rgb": "212, 154, 192",
    "brand-cyan-rgb": "95, 214, 207",
    "brand-lime-rgb": "79, 211, 155",
    "brand-coral-rgb": "255, 138, 92",
    "accent-a": "#4fd39b",
    "accent-b": "#d49ac0",
    "accent-c": "#5fd6cf",
    "accent-warm": "#ffcc5c",
    "accent-cool": "#6fbfe8",
    "accent-a-ink": "#4fd39b",
    "accent-b-ink": "#d49ac0",
    "accent-c-ink": "#5fd6cf",
    "accent-warm-ink": "#ffcc5c",
    "accent-cool-ink": "#6fbfe8",
    "accent-coral-ink": "#ff8a5c",
    "shiki-foreground": "#e6ede7",
    "shiki-background": "#0b110e",
    "shiki-token-comment": "color-mix(in srgb, #e6ede7 55%, #0b110e)",
    "shiki-token-punctuation": "color-mix(in srgb, #e6ede7 72%, #0b110e)",
    "shiki-token-keyword": "#d49ac0",
    "shiki-token-string": "#4fd39b",
    "shiki-token-string-expression": "#4fd39b",
    "shiki-token-constant": "#ffcc5c",
    "shiki-token-function": "#6fbfe8",
    "shiki-token-parameter": "#ff8a5c",
    "shiki-token-link": "#5fd6cf",
  },
};

export default fuji;
