import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Coral — Warm off-white with coral and teal.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const coral: ThemeConfig = {
  name: "coral",
  colors: {
    primary: "#bc4d3c",
    primaryHover: "#9c3c2e",
    background: "#fdfaf8",
    backgroundAlt: "#f6eeea",
    text: "#1c1614",
    textMuted: "#6d5f5a",
    border: "#ebdcd5",
    codeBackground: "#1c1614",
    codeBackgroundTop: "#1c1614",
    codeText: "#f2e8e3",
  },
  darkColors: {
    primary: "#ff8a75",
    primaryHover: "#ffab9b",
    background: "#161110",
    backgroundAlt: "#1f1817",
    text: "#f2e6e1",
    textMuted: "#9c8b85",
    border: "#2c2321",
    codeBackground: "#100c0b",
    codeBackgroundTop: "#100c0b",
    codeText: "#f2e6e1",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3f6480 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #93691f 18%, transparent)",
    "color-code-line-warning-border": "#93691f",
    "color-code-line-error": "color-mix(in srgb, #c4503f 20%, transparent)",
    "color-code-line-error-border": "#c4503f",
    "color-code-line-add": "color-mix(in srgb, #3f7566 16%, transparent)",
    "color-code-line-add-border": "#3f7566",
    "color-code-line-remove": "color-mix(in srgb, #c4503f 14%, transparent)",
    "color-code-line-remove-border": "#c4503f",
    "color-code-line-focus": "color-mix(in srgb, #bc4d3c 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #1c1614 92%, #f2e8e3)",
    "color-code-title-text": "color-mix(in srgb, #f2e8e3 88%, #1c1614)",
    "color-code-title-border": "color-mix(in srgb, #f2e8e3 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f2e8e3 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ebdcd5 92%, transparent)",
    "color-backdrop": "rgba(89, 88, 87, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6eeea 62%, #fdfaf8)",
    "surface-line": "color-mix(in srgb, #ebdcd5 72%, #fdfaf8)",
    "brand-violet": "#8a4a72",
    "brand-cyan": "#2f7370",
    "brand-lime": "#3f7566",
    "brand-coral": "#c4503f",
    "brand-navy": "color-mix(in srgb, #1c1614 70%, #fdfaf8)",
    "brand-violet-rgb": "138, 74, 114",
    "brand-cyan-rgb": "47, 115, 112",
    "brand-lime-rgb": "63, 117, 102",
    "brand-coral-rgb": "196, 80, 63",
    "accent-a": "#bc4d3c",
    "accent-b": "#8a4a72",
    "accent-c": "#2f7370",
    "accent-warm": "#93691f",
    "accent-cool": "#3f6480",
    "accent-a-ink": "#bc4d3c",
    "accent-b-ink": "#8a4a72",
    "accent-c-ink": "#2f7370",
    "accent-warm-ink": "#93691f",
    "accent-cool-ink": "#3f6480",
    "accent-coral-ink": "#bc4d3c",
    "syntax-foreground": "#f2e8e3",
    "syntax-background": "#1c1614",
    "syntax-token-comment": "color-mix(in srgb, #f2e8e3 55%, #1c1614)",
    "syntax-token-punctuation": "color-mix(in srgb, #f2e8e3 72%, #1c1614)",
    "syntax-token-keyword": "#c99ab8",
    "syntax-token-string": "#6fc9b0",
    "syntax-token-string-expression": "#6fc9b0",
    "syntax-token-constant": "#e6bd7d",
    "syntax-token-function": "#89b4d4",
    "syntax-token-parameter": "#ff8a75",
    "syntax-token-link": "#6fc9c4",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #89b4d4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e6bd7d 18%, transparent)",
    "color-code-line-warning-border": "#e6bd7d",
    "color-code-line-error": "color-mix(in srgb, #ff8a75 20%, transparent)",
    "color-code-line-error-border": "#ff8a75",
    "color-code-line-add": "color-mix(in srgb, #6fc9b0 16%, transparent)",
    "color-code-line-add-border": "#6fc9b0",
    "color-code-line-remove": "color-mix(in srgb, #ff8a75 14%, transparent)",
    "color-code-line-remove-border": "#ff8a75",
    "color-code-line-focus": "color-mix(in srgb, #ff8a75 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #100c0b 92%, #f2e6e1)",
    "color-code-title-text": "color-mix(in srgb, #f2e6e1 88%, #100c0b)",
    "color-code-title-border": "color-mix(in srgb, #f2e6e1 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f2e6e1 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2c2321 92%, transparent)",
    "color-backdrop": "rgba(8, 6, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #1f1817 62%, #161110)",
    "surface-line": "color-mix(in srgb, #2c2321 72%, #161110)",
    "brand-violet": "#c99ab8",
    "brand-cyan": "#6fc9c4",
    "brand-lime": "#6fc9b0",
    "brand-coral": "#ff8a75",
    "brand-navy": "color-mix(in srgb, #f2e6e1 70%, #161110)",
    "brand-violet-rgb": "201, 154, 184",
    "brand-cyan-rgb": "111, 201, 196",
    "brand-lime-rgb": "111, 201, 176",
    "brand-coral-rgb": "255, 138, 117",
    "accent-a": "#ff8a75",
    "accent-b": "#c99ab8",
    "accent-c": "#6fc9c4",
    "accent-warm": "#e6bd7d",
    "accent-cool": "#89b4d4",
    "accent-a-ink": "#ff8a75",
    "accent-b-ink": "#c99ab8",
    "accent-c-ink": "#6fc9c4",
    "accent-warm-ink": "#e6bd7d",
    "accent-cool-ink": "#89b4d4",
    "accent-coral-ink": "#ff8a75",
    "syntax-foreground": "#f2e6e1",
    "syntax-background": "#100c0b",
    "syntax-token-comment": "color-mix(in srgb, #f2e6e1 55%, #100c0b)",
    "syntax-token-punctuation": "color-mix(in srgb, #f2e6e1 72%, #100c0b)",
    "syntax-token-keyword": "#c99ab8",
    "syntax-token-string": "#6fc9b0",
    "syntax-token-string-expression": "#6fc9b0",
    "syntax-token-constant": "#e6bd7d",
    "syntax-token-function": "#89b4d4",
    "syntax-token-parameter": "#ff8a75",
    "syntax-token-link": "#6fc9c4",
  },
};
