packages:
  - crates/ox_content_napi
  - crates/ox_content_wasm/pkg
  - npm/*
  - docs
  - examples/*
  - benchmarks/*
  - benchmarks/bundle-size/apps/*

catalog:
  "@sveltejs/vite-plugin-svelte": ^7.1.2
  "@types/node": ^25.8.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.0.0
  "@vitejs/plugin-react": ^6.0.2
  "@vitejs/plugin-vue": ^6.0.7
  "@typescript/native-preview": ^7.0.0-dev.20260524.1
  esbuild: ^0.28.0
  react: ^19.0.0
  react-dom: ^19.0.0
  svelte: ^5.55.7
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.21
  vue: ^3.5.34
  vite-plus: 0.1.22

onlyBuiltDependencies:
  - esbuild
  - sharp
  - puppeteer
packageExtensions:
  "@voidzero-dev/vite-plus-core@0.1.21":
    dependencies:
      picomatch: ^4.0.4
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
