import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Ayu — Ayu Light and Ayu Dark.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const ayuDark: ThemeConfig = {
  name: "ayu-dark",
  colors: {
    primary: "#a36229",
    primaryHover: "#b65b00",
    background: "#fcfcfc",
    backgroundAlt: "#f3f4f5",
    text: "#5c6166",
    textMuted: "#6e747a",
    border: "#e7e8e9",
    codeBackground: "#f3f4f5",
    codeBackgroundTop: "#f3f4f5",
    codeText: "#5c6166",
  },
  darkColors: {
    primary: "#e6b450",
    primaryHover: "#e6b450",
    background: "#10141c",
    backgroundAlt: "#0d1017",
    text: "#bfbdb6",
    textMuted: "#7b858f",
    border: "#1b1f29",
    codeBackground: "#10141c",
    codeBackgroundTop: "#10141c",
    codeText: "#bfbdb6",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #399ee6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f2ae49 18%, transparent)",
    "color-code-line-warning-border": "#f2ae49",
    "color-code-line-error": "color-mix(in srgb, #f07171 20%, transparent)",
    "color-code-line-error-border": "#f07171",
    "color-code-line-add": "color-mix(in srgb, #86b300 16%, transparent)",
    "color-code-line-add-border": "#86b300",
    "color-code-line-remove": "color-mix(in srgb, #f07171 14%, transparent)",
    "color-code-line-remove-border": "#f07171",
    "color-code-line-focus": "color-mix(in srgb, #a36229 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f3f4f5 92%, #5c6166)",
    "color-code-title-text": "color-mix(in srgb, #5c6166 88%, #f3f4f5)",
    "color-code-title-border": "color-mix(in srgb, #5c6166 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #5c6166 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e7e8e9 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f3f4f5 62%, #fcfcfc)",
    "surface-line": "color-mix(in srgb, #e7e8e9 72%, #fcfcfc)",
    "brand-violet": "#a37acc",
    "brand-cyan": "#4cbf99",
    "brand-lime": "#86b300",
    "brand-coral": "#f07171",
    "brand-navy": "color-mix(in srgb, #5c6166 70%, #fcfcfc)",
    "brand-violet-rgb": "163, 122, 204",
    "brand-cyan-rgb": "76, 191, 153",
    "brand-lime-rgb": "134, 179, 0",
    "brand-coral-rgb": "240, 113, 113",
    "accent-a": "#a36229",
    "accent-b": "#a37acc",
    "accent-c": "#4cbf99",
    "accent-warm": "#f2ae49",
    "accent-cool": "#399ee6",
    "accent-a-ink": "#a36229",
    "accent-b-ink": "#8262a3",
    "accent-c-ink": "#348268",
    "accent-warm-ink": "#91682c",
    "accent-cool-ink": "#2b78af",
    "accent-coral-ink": "#b65656",
    "syntax-foreground": "#5c6166",
    "syntax-background": "#f3f4f5",
    "syntax-token-comment": "color-mix(in srgb, #5c6166 55%, #f3f4f5)",
    "syntax-token-punctuation": "color-mix(in srgb, #5c6166 72%, #f3f4f5)",
    "syntax-token-keyword": "#a37acc",
    "syntax-token-string": "#86b300",
    "syntax-token-string-expression": "#86b300",
    "syntax-token-constant": "#f2ae49",
    "syntax-token-function": "#399ee6",
    "syntax-token-parameter": "#f07171",
    "syntax-token-link": "#4cbf99",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4fbfff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fdb04c 18%, transparent)",
    "color-code-line-warning-border": "#fdb04c",
    "color-code-line-error": "color-mix(in srgb, #f06b73 20%, transparent)",
    "color-code-line-error-border": "#f06b73",
    "color-code-line-add": "color-mix(in srgb, #70bf56 16%, transparent)",
    "color-code-line-add-border": "#70bf56",
    "color-code-line-remove": "color-mix(in srgb, #f06b73 14%, transparent)",
    "color-code-line-remove-border": "#f06b73",
    "color-code-line-focus": "color-mix(in srgb, #e6b450 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #10141c 92%, #bfbdb6)",
    "color-code-title-text": "color-mix(in srgb, #bfbdb6 88%, #10141c)",
    "color-code-title-border": "color-mix(in srgb, #bfbdb6 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #bfbdb6 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1b1f29 92%, transparent)",
    "color-backdrop": "rgba(6, 7, 10, 0.62)",
    "surface-glass": "color-mix(in srgb, #0d1017 62%, #10141c)",
    "surface-line": "color-mix(in srgb, #1b1f29 72%, #10141c)",
    "brand-violet": "#d0a1ff",
    "brand-cyan": "#93e2c8",
    "brand-lime": "#70bf56",
    "brand-coral": "#f06b73",
    "brand-navy": "color-mix(in srgb, #bfbdb6 70%, #10141c)",
    "brand-violet-rgb": "208, 161, 255",
    "brand-cyan-rgb": "147, 226, 200",
    "brand-lime-rgb": "112, 191, 86",
    "brand-coral-rgb": "240, 107, 115",
    "accent-a": "#e6b450",
    "accent-b": "#d0a1ff",
    "accent-c": "#93e2c8",
    "accent-warm": "#fdb04c",
    "accent-cool": "#4fbfff",
    "accent-a-ink": "#e6b450",
    "accent-b-ink": "#d0a1ff",
    "accent-c-ink": "#93e2c8",
    "accent-warm-ink": "#fdb04c",
    "accent-cool-ink": "#4fbfff",
    "accent-coral-ink": "#f06b73",
    "syntax-foreground": "#bfbdb6",
    "syntax-background": "#10141c",
    "syntax-token-comment": "#5a6673",
    "syntax-token-punctuation": "#bfbdb6b3",
    "syntax-token-keyword": "#ff8f40",
    "syntax-token-string": "#aad94c",
    "syntax-token-string-expression": "#aad94c",
    "syntax-token-constant": "#d2a6ff",
    "syntax-token-function": "#ffb454",
    "syntax-token-parameter": "#d2a6ff",
    "syntax-token-link": "#39bae6",
  },
};
