import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Ayu — Ayu Light and Ayu Mirage.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const ayu: ThemeConfig = {
  name: "ayu",
  colors: {
    primary: "#a36229",
    primaryHover: "#b65b00",
    background: "#fcfcfc",
    backgroundAlt: "#f3f4f5",
    text: "#5c6166",
    textMuted: "#6e747a",
    border: "#e7e8e9",
    codeBackground: "#f3f4f5",
    codeBackgroundTop: "#f3f4f5",
    codeText: "#5c6166",
  },
  darkColors: {
    primary: "#ffcc66",
    primaryHover: "#ffdd99",
    background: "#1f2430",
    backgroundAlt: "#242936",
    text: "#cccac2",
    textMuted: "#8a9199",
    border: "#343b4b",
    codeBackground: "#1a1f29",
    codeBackgroundTop: "#1a1f29",
    codeText: "#cccac2",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #399ee6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f2ae49 18%, transparent)",
    "color-code-line-warning-border": "#f2ae49",
    "color-code-line-error": "color-mix(in srgb, #f07171 20%, transparent)",
    "color-code-line-error-border": "#f07171",
    "color-code-line-add": "color-mix(in srgb, #86b300 16%, transparent)",
    "color-code-line-add-border": "#86b300",
    "color-code-line-remove": "color-mix(in srgb, #f07171 14%, transparent)",
    "color-code-line-remove-border": "#f07171",
    "color-code-line-focus": "color-mix(in srgb, #a36229 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f3f4f5 92%, #5c6166)",
    "color-code-title-text": "color-mix(in srgb, #5c6166 88%, #f3f4f5)",
    "color-code-title-border": "color-mix(in srgb, #5c6166 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #5c6166 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e7e8e9 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f3f4f5 62%, #fcfcfc)",
    "surface-line": "color-mix(in srgb, #e7e8e9 72%, #fcfcfc)",
    "brand-violet": "#a37acc",
    "brand-cyan": "#4cbf99",
    "brand-lime": "#86b300",
    "brand-coral": "#f07171",
    "brand-navy": "color-mix(in srgb, #5c6166 70%, #fcfcfc)",
    "brand-violet-rgb": "163, 122, 204",
    "brand-cyan-rgb": "76, 191, 153",
    "brand-lime-rgb": "134, 179, 0",
    "brand-coral-rgb": "240, 113, 113",
    "accent-a": "#a36229",
    "accent-b": "#a37acc",
    "accent-c": "#4cbf99",
    "accent-warm": "#f2ae49",
    "accent-cool": "#399ee6",
    "accent-a-ink": "#a36229",
    "accent-b-ink": "#8262a3",
    "accent-c-ink": "#348268",
    "accent-warm-ink": "#91682c",
    "accent-cool-ink": "#2b78af",
    "accent-coral-ink": "#b65656",
    "syntax-foreground": "#5c6166",
    "syntax-background": "#f3f4f5",
    "syntax-token-comment": "color-mix(in srgb, #5c6166 55%, #f3f4f5)",
    "syntax-token-punctuation": "color-mix(in srgb, #5c6166 72%, #f3f4f5)",
    "syntax-token-keyword": "#a37acc",
    "syntax-token-string": "#86b300",
    "syntax-token-string-expression": "#86b300",
    "syntax-token-constant": "#f2ae49",
    "syntax-token-function": "#399ee6",
    "syntax-token-parameter": "#f07171",
    "syntax-token-link": "#4cbf99",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #73d0ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffd173 18%, transparent)",
    "color-code-line-warning-border": "#ffd173",
    "color-code-line-error": "color-mix(in srgb, #f28779 20%, transparent)",
    "color-code-line-error-border": "#f28779",
    "color-code-line-add": "color-mix(in srgb, #d5ff80 16%, transparent)",
    "color-code-line-add-border": "#d5ff80",
    "color-code-line-remove": "color-mix(in srgb, #f28779 14%, transparent)",
    "color-code-line-remove-border": "#f28779",
    "color-code-line-focus": "color-mix(in srgb, #ffcc66 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #1a1f29 92%, #cccac2)",
    "color-code-title-text": "color-mix(in srgb, #cccac2 88%, #1a1f29)",
    "color-code-title-border": "color-mix(in srgb, #cccac2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cccac2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #343b4b 92%, transparent)",
    "color-backdrop": "rgba(11, 13, 17, 0.62)",
    "surface-glass": "color-mix(in srgb, #242936 62%, #1f2430)",
    "surface-line": "color-mix(in srgb, #343b4b 72%, #1f2430)",
    "brand-violet": "#dfbfff",
    "brand-cyan": "#95e6cb",
    "brand-lime": "#d5ff80",
    "brand-coral": "#f28779",
    "brand-navy": "color-mix(in srgb, #cccac2 70%, #1f2430)",
    "brand-violet-rgb": "223, 191, 255",
    "brand-cyan-rgb": "149, 230, 203",
    "brand-lime-rgb": "213, 255, 128",
    "brand-coral-rgb": "242, 135, 121",
    "accent-a": "#ffcc66",
    "accent-b": "#dfbfff",
    "accent-c": "#95e6cb",
    "accent-warm": "#ffd173",
    "accent-cool": "#73d0ff",
    "accent-a-ink": "#ffcc66",
    "accent-b-ink": "#dfbfff",
    "accent-c-ink": "#95e6cb",
    "accent-warm-ink": "#ffd173",
    "accent-cool-ink": "#73d0ff",
    "accent-coral-ink": "#f28779",
    "syntax-foreground": "#cccac2",
    "syntax-background": "#1a1f29",
    "syntax-token-comment": "color-mix(in srgb, #cccac2 55%, #1a1f29)",
    "syntax-token-punctuation": "color-mix(in srgb, #cccac2 72%, #1a1f29)",
    "syntax-token-keyword": "#dfbfff",
    "syntax-token-string": "#d5ff80",
    "syntax-token-string-expression": "#d5ff80",
    "syntax-token-constant": "#ffd173",
    "syntax-token-function": "#73d0ff",
    "syntax-token-parameter": "#f28779",
    "syntax-token-link": "#95e6cb",
  },
};

export default ayu;
