import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Voltage — High-voltage accents over a near-black canvas.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const voltage: ThemeConfig = {
  name: "voltage",
  colors: {
    primary: "#7c2fe0",
    primaryHover: "#6320b8",
    background: "#ffffff",
    backgroundAlt: "#f4f2fa",
    text: "#14111f",
    textMuted: "#5d5673",
    border: "#e0dced",
    codeBackground: "#141020",
    codeBackgroundTop: "#141020",
    codeText: "#f0ecff",
  },
  darkColors: {
    primary: "#b57bff",
    primaryHover: "#cfa6ff",
    background: "#0a0812",
    backgroundAlt: "#141020",
    text: "#f2effd",
    textMuted: "#9a92b8",
    border: "#2a2140",
    codeBackground: "#0d0a17",
    codeBackgroundTop: "#0d0a17",
    codeText: "#f2effd",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4b3ae0 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #b4790a 18%, transparent)",
    "color-code-line-warning-border": "#b4790a",
    "color-code-line-error": "color-mix(in srgb, #d61f5c 20%, transparent)",
    "color-code-line-error-border": "#d61f5c",
    "color-code-line-add": "color-mix(in srgb, #0f8a5f 16%, transparent)",
    "color-code-line-add-border": "#0f8a5f",
    "color-code-line-remove": "color-mix(in srgb, #d61f5c 14%, transparent)",
    "color-code-line-remove-border": "#d61f5c",
    "color-code-line-focus": "color-mix(in srgb, #7c2fe0 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #141020 92%, #f0ecff)",
    "color-code-title-text": "color-mix(in srgb, #f0ecff 88%, #141020)",
    "color-code-title-border": "color-mix(in srgb, #f0ecff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0ecff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e0dced 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f4f2fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #e0dced 72%, #ffffff)",
    "brand-violet": "#a32fd6",
    "brand-cyan": "#0f7f9c",
    "brand-lime": "#0f8a5f",
    "brand-coral": "#d61f5c",
    "brand-navy": "color-mix(in srgb, #14111f 70%, #ffffff)",
    "brand-violet-rgb": "163, 47, 214",
    "brand-cyan-rgb": "15, 127, 156",
    "brand-lime-rgb": "15, 138, 95",
    "brand-coral-rgb": "214, 31, 92",
    "accent-a": "#7c2fe0",
    "accent-b": "#a32fd6",
    "accent-c": "#0f7f9c",
    "accent-warm": "#b4790a",
    "accent-cool": "#4b3ae0",
    "accent-a-ink": "#7c2fe0",
    "accent-b-ink": "#a32fd6",
    "accent-c-ink": "#0f7f9c",
    "accent-warm-ink": "#9e6a09",
    "accent-cool-ink": "#4b3ae0",
    "accent-coral-ink": "#d61f5c",
    "shiki-foreground": "#f0ecff",
    "shiki-background": "#141020",
    "shiki-token-comment": "color-mix(in srgb, #f0ecff 55%, #141020)",
    "shiki-token-punctuation": "color-mix(in srgb, #f0ecff 72%, #141020)",
    "shiki-token-keyword": "#c77dff",
    "shiki-token-string": "#3ddc97",
    "shiki-token-string-expression": "#3ddc97",
    "shiki-token-constant": "#ffd60a",
    "shiki-token-function": "#7c8cff",
    "shiki-token-parameter": "#ff5c8a",
    "shiki-token-link": "#4fd6e8",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #7c8cff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffd60a 18%, transparent)",
    "color-code-line-warning-border": "#ffd60a",
    "color-code-line-error": "color-mix(in srgb, #ff5c8a 20%, transparent)",
    "color-code-line-error-border": "#ff5c8a",
    "color-code-line-add": "color-mix(in srgb, #3ddc97 16%, transparent)",
    "color-code-line-add-border": "#3ddc97",
    "color-code-line-remove": "color-mix(in srgb, #ff5c8a 14%, transparent)",
    "color-code-line-remove-border": "#ff5c8a",
    "color-code-line-focus": "color-mix(in srgb, #b57bff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0d0a17 92%, #f2effd)",
    "color-code-title-text": "color-mix(in srgb, #f2effd 88%, #0d0a17)",
    "color-code-title-border": "color-mix(in srgb, #f2effd 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f2effd 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2a2140 92%, transparent)",
    "color-backdrop": "rgba(4, 3, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #141020 62%, #0a0812)",
    "surface-line": "color-mix(in srgb, #2a2140 72%, #0a0812)",
    "brand-violet": "#c77dff",
    "brand-cyan": "#4fd6e8",
    "brand-lime": "#3ddc97",
    "brand-coral": "#ff5c8a",
    "brand-navy": "color-mix(in srgb, #f2effd 70%, #0a0812)",
    "brand-violet-rgb": "199, 125, 255",
    "brand-cyan-rgb": "79, 214, 232",
    "brand-lime-rgb": "61, 220, 151",
    "brand-coral-rgb": "255, 92, 138",
    "accent-a": "#b57bff",
    "accent-b": "#c77dff",
    "accent-c": "#4fd6e8",
    "accent-warm": "#ffd60a",
    "accent-cool": "#7c8cff",
    "accent-a-ink": "#b57bff",
    "accent-b-ink": "#c77dff",
    "accent-c-ink": "#4fd6e8",
    "accent-warm-ink": "#ffd60a",
    "accent-cool-ink": "#7c8cff",
    "accent-coral-ink": "#ff5c8a",
    "shiki-foreground": "#f2effd",
    "shiki-background": "#0d0a17",
    "shiki-token-comment": "color-mix(in srgb, #f2effd 55%, #0d0a17)",
    "shiki-token-punctuation": "color-mix(in srgb, #f2effd 72%, #0d0a17)",
    "shiki-token-keyword": "#c77dff",
    "shiki-token-string": "#3ddc97",
    "shiki-token-string-expression": "#3ddc97",
    "shiki-token-constant": "#ffd60a",
    "shiki-token-function": "#7c8cff",
    "shiki-token-parameter": "#ff5c8a",
    "shiki-token-link": "#4fd6e8",
  },
};

export default voltage;
