import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Dracula — Dracula Alucard light companion and Dracula Soft.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const draculaSoft: ThemeConfig = {
  name: "dracula-soft",
  colors: {
    primary: "#644ac9",
    primaryHover: "#4e39a8",
    background: "#fffbeb",
    backgroundAlt: "#f5f0dc",
    text: "#1f1f1f",
    textMuted: "#6c664b",
    border: "#cfc9ad",
    codeBackground: "#f5f0dc",
    codeBackgroundTop: "#f5f0dc",
    codeText: "#1f1f1f",
  },
  darkColors: {
    primary: "#97e1f1",
    primaryHover: "#97e1f1",
    background: "#282a36",
    backgroundAlt: "#262626",
    text: "#f6f6f4",
    textMuted: "#90939e",
    border: "#bf9eee",
    codeBackground: "#282a36",
    codeBackgroundTop: "#282a36",
    codeText: "#f6f6f4",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #644ac9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #846e15 18%, transparent)",
    "color-code-line-warning-border": "#846e15",
    "color-code-line-error": "color-mix(in srgb, #cb3a2a 20%, transparent)",
    "color-code-line-error-border": "#cb3a2a",
    "color-code-line-add": "color-mix(in srgb, #14710a 16%, transparent)",
    "color-code-line-add-border": "#14710a",
    "color-code-line-remove": "color-mix(in srgb, #cb3a2a 14%, transparent)",
    "color-code-line-remove-border": "#cb3a2a",
    "color-code-line-focus": "color-mix(in srgb, #644ac9 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f5f0dc 92%, #1f1f1f)",
    "color-code-title-text": "color-mix(in srgb, #1f1f1f 88%, #f5f0dc)",
    "color-code-title-border": "color-mix(in srgb, #1f1f1f 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f1f1f 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #cfc9ad 92%, transparent)",
    "color-backdrop": "rgba(89, 88, 82, 0.62)",
    "surface-glass": "color-mix(in srgb, #f5f0dc 62%, #fffbeb)",
    "surface-line": "color-mix(in srgb, #cfc9ad 72%, #fffbeb)",
    "brand-violet": "#a3144d",
    "brand-cyan": "#036a96",
    "brand-lime": "#14710a",
    "brand-coral": "#cb3a2a",
    "brand-navy": "color-mix(in srgb, #1f1f1f 70%, #fffbeb)",
    "brand-violet-rgb": "163, 20, 77",
    "brand-cyan-rgb": "3, 106, 150",
    "brand-lime-rgb": "20, 113, 10",
    "brand-coral-rgb": "203, 58, 42",
    "accent-a": "#644ac9",
    "accent-b": "#a3144d",
    "accent-c": "#036a96",
    "accent-warm": "#846e15",
    "accent-cool": "#644ac9",
    "accent-a-ink": "#644ac9",
    "accent-b-ink": "#a3144d",
    "accent-c-ink": "#036a96",
    "accent-warm-ink": "#846e15",
    "accent-cool-ink": "#644ac9",
    "accent-coral-ink": "#cb3a2a",
    "syntax-foreground": "#1f1f1f",
    "syntax-background": "#f5f0dc",
    "syntax-token-comment": "color-mix(in srgb, #1f1f1f 55%, #f5f0dc)",
    "syntax-token-punctuation": "color-mix(in srgb, #1f1f1f 72%, #f5f0dc)",
    "syntax-token-keyword": "#a3144d",
    "syntax-token-string": "#14710a",
    "syntax-token-string-expression": "#14710a",
    "syntax-token-constant": "#846e15",
    "syntax-token-function": "#644ac9",
    "syntax-token-parameter": "#cb3a2a",
    "syntax-token-link": "#036a96",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #bf9eee 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e7ee98 18%, transparent)",
    "color-code-line-warning-border": "#e7ee98",
    "color-code-line-error": "color-mix(in srgb, #ee6666 20%, transparent)",
    "color-code-line-error-border": "#ee6666",
    "color-code-line-add": "color-mix(in srgb, #62e884 16%, transparent)",
    "color-code-line-add-border": "#62e884",
    "color-code-line-remove": "color-mix(in srgb, #ee6666 14%, transparent)",
    "color-code-line-remove-border": "#ee6666",
    "color-code-line-focus": "color-mix(in srgb, #97e1f1 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #282a36 92%, #f6f6f4)",
    "color-code-title-text": "color-mix(in srgb, #f6f6f4 88%, #282a36)",
    "color-code-title-border": "color-mix(in srgb, #f6f6f4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f6f6f4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #bf9eee 92%, transparent)",
    "color-backdrop": "rgba(14, 15, 19, 0.62)",
    "surface-glass": "color-mix(in srgb, #262626 62%, #282a36)",
    "surface-line": "color-mix(in srgb, #bf9eee 72%, #282a36)",
    "brand-violet": "#f286c4",
    "brand-cyan": "#97e1f1",
    "brand-lime": "#62e884",
    "brand-coral": "#ee6666",
    "brand-navy": "color-mix(in srgb, #f6f6f4 70%, #282a36)",
    "brand-violet-rgb": "242, 134, 196",
    "brand-cyan-rgb": "151, 225, 241",
    "brand-lime-rgb": "98, 232, 132",
    "brand-coral-rgb": "238, 102, 102",
    "accent-a": "#97e1f1",
    "accent-b": "#f286c4",
    "accent-c": "#97e1f1",
    "accent-warm": "#e7ee98",
    "accent-cool": "#bf9eee",
    "accent-a-ink": "#97e1f1",
    "accent-b-ink": "#f286c4",
    "accent-c-ink": "#97e1f1",
    "accent-warm-ink": "#e7ee98",
    "accent-cool-ink": "#bf9eee",
    "accent-coral-ink": "#ee6666",
    "syntax-foreground": "#f6f6f4",
    "syntax-background": "#282a36",
    "syntax-token-comment": "#7b7f8b",
    "syntax-token-punctuation": "#97e1f1",
    "syntax-token-keyword": "#f286c4",
    "syntax-token-string": "#e7ee98",
    "syntax-token-string-expression": "#e7ee98",
    "syntax-token-constant": "#bf9eee",
    "syntax-token-function": "#62e884",
    "syntax-token-parameter": "#ffb86c",
    "syntax-token-link": "#f286c4",
  },
};
