import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Dracula — Dracula with the Alucard light counterpart.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const dracula: ThemeConfig = {
  name: "dracula",
  colors: {
    primary: "#644ac9",
    primaryHover: "#4e39a8",
    background: "#fffbeb",
    backgroundAlt: "#f5f0dc",
    text: "#1f1f1f",
    textMuted: "#6c664b",
    border: "#cfc9ad",
    codeBackground: "#f5f0dc",
    codeBackgroundTop: "#f5f0dc",
    codeText: "#1f1f1f",
  },
  darkColors: {
    primary: "#bd93f9",
    primaryHover: "#d0b0ff",
    background: "#282a36",
    backgroundAlt: "#343746",
    text: "#f8f8f2",
    textMuted: "#9ca3b8",
    border: "#44475a",
    codeBackground: "#21222c",
    codeBackgroundTop: "#21222c",
    codeText: "#f8f8f2",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #644ac9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #846e15 18%, transparent)",
    "color-code-line-warning-border": "#846e15",
    "color-code-line-error": "color-mix(in srgb, #cb3a2a 20%, transparent)",
    "color-code-line-error-border": "#cb3a2a",
    "color-code-line-add": "color-mix(in srgb, #14710a 16%, transparent)",
    "color-code-line-add-border": "#14710a",
    "color-code-line-remove": "color-mix(in srgb, #cb3a2a 14%, transparent)",
    "color-code-line-remove-border": "#cb3a2a",
    "color-code-line-focus": "color-mix(in srgb, #644ac9 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f5f0dc 92%, #1f1f1f)",
    "color-code-title-text": "color-mix(in srgb, #1f1f1f 88%, #f5f0dc)",
    "color-code-title-border": "color-mix(in srgb, #1f1f1f 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f1f1f 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #cfc9ad 92%, transparent)",
    "color-backdrop": "rgba(89, 88, 82, 0.62)",
    "surface-glass": "color-mix(in srgb, #f5f0dc 62%, #fffbeb)",
    "surface-line": "color-mix(in srgb, #cfc9ad 72%, #fffbeb)",
    "brand-violet": "#a3144d",
    "brand-cyan": "#036a96",
    "brand-lime": "#14710a",
    "brand-coral": "#cb3a2a",
    "brand-navy": "color-mix(in srgb, #1f1f1f 70%, #fffbeb)",
    "brand-violet-rgb": "163, 20, 77",
    "brand-cyan-rgb": "3, 106, 150",
    "brand-lime-rgb": "20, 113, 10",
    "brand-coral-rgb": "203, 58, 42",
    "accent-a": "#644ac9",
    "accent-b": "#a3144d",
    "accent-c": "#036a96",
    "accent-warm": "#846e15",
    "accent-cool": "#644ac9",
    "accent-a-ink": "#644ac9",
    "accent-b-ink": "#a3144d",
    "accent-c-ink": "#036a96",
    "accent-warm-ink": "#846e15",
    "accent-cool-ink": "#644ac9",
    "accent-coral-ink": "#cb3a2a",
    "shiki-foreground": "#1f1f1f",
    "shiki-background": "#f5f0dc",
    "shiki-token-comment": "color-mix(in srgb, #1f1f1f 55%, #f5f0dc)",
    "shiki-token-punctuation": "color-mix(in srgb, #1f1f1f 72%, #f5f0dc)",
    "shiki-token-keyword": "#a3144d",
    "shiki-token-string": "#14710a",
    "shiki-token-string-expression": "#14710a",
    "shiki-token-constant": "#846e15",
    "shiki-token-function": "#644ac9",
    "shiki-token-parameter": "#cb3a2a",
    "shiki-token-link": "#036a96",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8be9fd 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f1fa8c 18%, transparent)",
    "color-code-line-warning-border": "#f1fa8c",
    "color-code-line-error": "color-mix(in srgb, #ff5555 20%, transparent)",
    "color-code-line-error-border": "#ff5555",
    "color-code-line-add": "color-mix(in srgb, #50fa7b 16%, transparent)",
    "color-code-line-add-border": "#50fa7b",
    "color-code-line-remove": "color-mix(in srgb, #ff5555 14%, transparent)",
    "color-code-line-remove-border": "#ff5555",
    "color-code-line-focus": "color-mix(in srgb, #bd93f9 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #21222c 92%, #f8f8f2)",
    "color-code-title-text": "color-mix(in srgb, #f8f8f2 88%, #21222c)",
    "color-code-title-border": "color-mix(in srgb, #f8f8f2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f8f8f2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #44475a 92%, transparent)",
    "color-backdrop": "rgba(14, 15, 19, 0.62)",
    "surface-glass": "color-mix(in srgb, #343746 62%, #282a36)",
    "surface-line": "color-mix(in srgb, #44475a 72%, #282a36)",
    "brand-violet": "#ff79c6",
    "brand-cyan": "#8be9fd",
    "brand-lime": "#50fa7b",
    "brand-coral": "#ff5555",
    "brand-navy": "color-mix(in srgb, #f8f8f2 70%, #282a36)",
    "brand-violet-rgb": "255, 121, 198",
    "brand-cyan-rgb": "139, 233, 253",
    "brand-lime-rgb": "80, 250, 123",
    "brand-coral-rgb": "255, 85, 85",
    "accent-a": "#bd93f9",
    "accent-b": "#ff79c6",
    "accent-c": "#8be9fd",
    "accent-warm": "#f1fa8c",
    "accent-cool": "#8be9fd",
    "accent-a-ink": "#bd93f9",
    "accent-b-ink": "#ff79c6",
    "accent-c-ink": "#8be9fd",
    "accent-warm-ink": "#f1fa8c",
    "accent-cool-ink": "#8be9fd",
    "accent-coral-ink": "#ff5555",
    "shiki-foreground": "#f8f8f2",
    "shiki-background": "#21222c",
    "shiki-token-comment": "color-mix(in srgb, #f8f8f2 55%, #21222c)",
    "shiki-token-punctuation": "color-mix(in srgb, #f8f8f2 72%, #21222c)",
    "shiki-token-keyword": "#ff79c6",
    "shiki-token-string": "#50fa7b",
    "shiki-token-string-expression": "#50fa7b",
    "shiki-token-constant": "#f1fa8c",
    "shiki-token-function": "#8be9fd",
    "shiki-token-parameter": "#ff5555",
    "shiki-token-link": "#8be9fd",
  },
};

export default dracula;
