import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Cacao — Warm dark chocolate with caramel.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const cacao: ThemeConfig = {
  name: "cacao",
  colors: {
    primary: "#96591f",
    primaryHover: "#744317",
    background: "#faf5ef",
    backgroundAlt: "#f0e8de",
    text: "#231a14",
    textMuted: "#6f6055",
    border: "#e2d6c8",
    codeBackground: "#231a14",
    codeBackgroundTop: "#231a14",
    codeText: "#f0e8de",
  },
  darkColors: {
    primary: "#dda86a",
    primaryHover: "#ecc290",
    background: "#1a1310",
    backgroundAlt: "#241b16",
    text: "#f0e6da",
    textMuted: "#9d8d7e",
    border: "#332720",
    codeBackground: "#130e0b",
    codeBackgroundTop: "#130e0b",
    codeText: "#f0e6da",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4c5f74 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #96591f 18%, transparent)",
    "color-code-line-warning-border": "#96591f",
    "color-code-line-error": "color-mix(in srgb, #a9412f 20%, transparent)",
    "color-code-line-error-border": "#a9412f",
    "color-code-line-add": "color-mix(in srgb, #5d6f42 16%, transparent)",
    "color-code-line-add-border": "#5d6f42",
    "color-code-line-remove": "color-mix(in srgb, #a9412f 14%, transparent)",
    "color-code-line-remove-border": "#a9412f",
    "color-code-line-focus": "color-mix(in srgb, #96591f 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #231a14 92%, #f0e8de)",
    "color-code-title-text": "color-mix(in srgb, #f0e8de 88%, #231a14)",
    "color-code-title-border": "color-mix(in srgb, #f0e8de 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0e8de 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e2d6c8 92%, transparent)",
    "color-backdrop": "rgba(88, 86, 84, 0.62)",
    "surface-glass": "color-mix(in srgb, #f0e8de 62%, #faf5ef)",
    "surface-line": "color-mix(in srgb, #e2d6c8 72%, #faf5ef)",
    "brand-violet": "#7e4f68",
    "brand-cyan": "#3f6b66",
    "brand-lime": "#5d6f42",
    "brand-coral": "#a9412f",
    "brand-navy": "color-mix(in srgb, #231a14 70%, #faf5ef)",
    "brand-violet-rgb": "126, 79, 104",
    "brand-cyan-rgb": "63, 107, 102",
    "brand-lime-rgb": "93, 111, 66",
    "brand-coral-rgb": "169, 65, 47",
    "accent-a": "#96591f",
    "accent-b": "#7e4f68",
    "accent-c": "#3f6b66",
    "accent-warm": "#96591f",
    "accent-cool": "#4c5f74",
    "accent-a-ink": "#96591f",
    "accent-b-ink": "#7e4f68",
    "accent-c-ink": "#3f6b66",
    "accent-warm-ink": "#96591f",
    "accent-cool-ink": "#4c5f74",
    "accent-coral-ink": "#a9412f",
    "syntax-foreground": "#f0e8de",
    "syntax-background": "#231a14",
    "syntax-token-comment": "color-mix(in srgb, #f0e8de 55%, #231a14)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0e8de 72%, #231a14)",
    "syntax-token-keyword": "#c398ad",
    "syntax-token-string": "#a7bb7c",
    "syntax-token-string-expression": "#a7bb7c",
    "syntax-token-constant": "#dda86a",
    "syntax-token-function": "#93aabd",
    "syntax-token-parameter": "#e28a76",
    "syntax-token-link": "#82b4ab",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #93aabd 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dda86a 18%, transparent)",
    "color-code-line-warning-border": "#dda86a",
    "color-code-line-error": "color-mix(in srgb, #e28a76 20%, transparent)",
    "color-code-line-error-border": "#e28a76",
    "color-code-line-add": "color-mix(in srgb, #a7bb7c 16%, transparent)",
    "color-code-line-add-border": "#a7bb7c",
    "color-code-line-remove": "color-mix(in srgb, #e28a76 14%, transparent)",
    "color-code-line-remove-border": "#e28a76",
    "color-code-line-focus": "color-mix(in srgb, #dda86a 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #130e0b 92%, #f0e6da)",
    "color-code-title-text": "color-mix(in srgb, #f0e6da 88%, #130e0b)",
    "color-code-title-border": "color-mix(in srgb, #f0e6da 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0e6da 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #332720 92%, transparent)",
    "color-backdrop": "rgba(9, 7, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #241b16 62%, #1a1310)",
    "surface-line": "color-mix(in srgb, #332720 72%, #1a1310)",
    "brand-violet": "#c398ad",
    "brand-cyan": "#82b4ab",
    "brand-lime": "#a7bb7c",
    "brand-coral": "#e28a76",
    "brand-navy": "color-mix(in srgb, #f0e6da 70%, #1a1310)",
    "brand-violet-rgb": "195, 152, 173",
    "brand-cyan-rgb": "130, 180, 171",
    "brand-lime-rgb": "167, 187, 124",
    "brand-coral-rgb": "226, 138, 118",
    "accent-a": "#dda86a",
    "accent-b": "#c398ad",
    "accent-c": "#82b4ab",
    "accent-warm": "#dda86a",
    "accent-cool": "#93aabd",
    "accent-a-ink": "#dda86a",
    "accent-b-ink": "#c398ad",
    "accent-c-ink": "#82b4ab",
    "accent-warm-ink": "#dda86a",
    "accent-cool-ink": "#93aabd",
    "accent-coral-ink": "#e28a76",
    "syntax-foreground": "#f0e6da",
    "syntax-background": "#130e0b",
    "syntax-token-comment": "color-mix(in srgb, #f0e6da 55%, #130e0b)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0e6da 72%, #130e0b)",
    "syntax-token-keyword": "#c398ad",
    "syntax-token-string": "#a7bb7c",
    "syntax-token-string-expression": "#a7bb7c",
    "syntax-token-constant": "#dda86a",
    "syntax-token-function": "#93aabd",
    "syntax-token-parameter": "#e28a76",
    "syntax-token-link": "#82b4ab",
  },
};
