import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Retro — Warm amber phosphor terminal.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const retro: ThemeConfig = {
  name: "retro",
  colors: {
    primary: "#a8500a",
    primaryHover: "#8a4008",
    background: "#f4ecd8",
    backgroundAlt: "#e8dcc0",
    text: "#3b2f1e",
    textMuted: "#756647",
    border: "#c9b895",
    codeBackground: "#2b2108",
    codeBackgroundTop: "#2b2108",
    codeText: "#ffb000",
  },
  darkColors: {
    primary: "#ffcc33",
    primaryHover: "#ffe066",
    background: "#140f04",
    backgroundAlt: "#211906",
    text: "#ffb000",
    textMuted: "#a8741a",
    border: "#4a3608",
    codeBackground: "#0d0902",
    codeBackgroundTop: "#0d0902",
    codeText: "#ffb000",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5b5330 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #a8700a 18%, transparent)",
    "color-code-line-warning-border": "#a8700a",
    "color-code-line-error": "color-mix(in srgb, #b32d1c 20%, transparent)",
    "color-code-line-error-border": "#b32d1c",
    "color-code-line-add": "color-mix(in srgb, #5c6f0e 16%, transparent)",
    "color-code-line-add-border": "#5c6f0e",
    "color-code-line-remove": "color-mix(in srgb, #b32d1c 14%, transparent)",
    "color-code-line-remove-border": "#b32d1c",
    "color-code-line-focus": "color-mix(in srgb, #a8500a 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #2b2108 92%, #ffb000)",
    "color-code-title-text": "color-mix(in srgb, #ffb000 88%, #2b2108)",
    "color-code-title-border": "color-mix(in srgb, #ffb000 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffb000 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #c9b895 92%, transparent)",
    "color-backdrop": "rgba(85, 83, 76, 0.62)",
    "surface-glass": "color-mix(in srgb, #e8dcc0 62%, #f4ecd8)",
    "surface-line": "color-mix(in srgb, #c9b895 72%, #f4ecd8)",
    "brand-violet": "#8f3a5c",
    "brand-cyan": "#37665e",
    "brand-lime": "#5c6f0e",
    "brand-coral": "#b32d1c",
    "brand-navy": "color-mix(in srgb, #3b2f1e 70%, #f4ecd8)",
    "brand-violet-rgb": "143, 58, 92",
    "brand-cyan-rgb": "55, 102, 94",
    "brand-lime-rgb": "92, 111, 14",
    "brand-coral-rgb": "179, 45, 28",
    "accent-a": "#a8500a",
    "accent-b": "#8f3a5c",
    "accent-c": "#37665e",
    "accent-warm": "#a8700a",
    "accent-cool": "#5b5330",
    "accent-a-ink": "#a8500a",
    "accent-b-ink": "#8f3a5c",
    "accent-c-ink": "#37665e",
    "accent-warm-ink": "#8d5e08",
    "accent-cool-ink": "#5b5330",
    "accent-coral-ink": "#b32d1c",
    "shiki-foreground": "#ffb000",
    "shiki-background": "#2b2108",
    "shiki-token-comment": "color-mix(in srgb, #ffb000 55%, #2b2108)",
    "shiki-token-punctuation": "color-mix(in srgb, #ffb000 72%, #2b2108)",
    "shiki-token-keyword": "#ff8c42",
    "shiki-token-string": "#b8d000",
    "shiki-token-string-expression": "#b8d000",
    "shiki-token-constant": "#ffcc33",
    "shiki-token-function": "#ffa030",
    "shiki-token-parameter": "#ff5f1f",
    "shiki-token-link": "#e8d44d",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #ffa030 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffcc33 18%, transparent)",
    "color-code-line-warning-border": "#ffcc33",
    "color-code-line-error": "color-mix(in srgb, #ff5f1f 20%, transparent)",
    "color-code-line-error-border": "#ff5f1f",
    "color-code-line-add": "color-mix(in srgb, #b8d000 16%, transparent)",
    "color-code-line-add-border": "#b8d000",
    "color-code-line-remove": "color-mix(in srgb, #ff5f1f 14%, transparent)",
    "color-code-line-remove-border": "#ff5f1f",
    "color-code-line-focus": "color-mix(in srgb, #ffcc33 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0d0902 92%, #ffb000)",
    "color-code-title-text": "color-mix(in srgb, #ffb000 88%, #0d0902)",
    "color-code-title-border": "color-mix(in srgb, #ffb000 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffb000 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #4a3608 92%, transparent)",
    "color-backdrop": "rgba(7, 5, 1, 0.62)",
    "surface-glass": "color-mix(in srgb, #211906 62%, #140f04)",
    "surface-line": "color-mix(in srgb, #4a3608 72%, #140f04)",
    "brand-violet": "#ff8c42",
    "brand-cyan": "#e8d44d",
    "brand-lime": "#b8d000",
    "brand-coral": "#ff5f1f",
    "brand-navy": "color-mix(in srgb, #ffb000 70%, #140f04)",
    "brand-violet-rgb": "255, 140, 66",
    "brand-cyan-rgb": "232, 212, 77",
    "brand-lime-rgb": "184, 208, 0",
    "brand-coral-rgb": "255, 95, 31",
    "accent-a": "#ffcc33",
    "accent-b": "#ff8c42",
    "accent-c": "#e8d44d",
    "accent-warm": "#ffcc33",
    "accent-cool": "#ffa030",
    "accent-a-ink": "#ffcc33",
    "accent-b-ink": "#ff8c42",
    "accent-c-ink": "#e8d44d",
    "accent-warm-ink": "#ffcc33",
    "accent-cool-ink": "#ffa030",
    "accent-coral-ink": "#ff5f1f",
    "shiki-foreground": "#ffb000",
    "shiki-background": "#0d0902",
    "shiki-token-comment": "color-mix(in srgb, #ffb000 55%, #0d0902)",
    "shiki-token-punctuation": "color-mix(in srgb, #ffb000 72%, #0d0902)",
    "shiki-token-keyword": "#ff8c42",
    "shiki-token-string": "#b8d000",
    "shiki-token-string-expression": "#b8d000",
    "shiki-token-constant": "#ffcc33",
    "shiki-token-function": "#ffa030",
    "shiki-token-parameter": "#ff5f1f",
    "shiki-token-link": "#e8d44d",
  },
};

export default retro;
