import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Commander — CGA cyan panels by day, the bare console prompt by night.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const commander: ThemeConfig = {
  name: "commander",
  colors: {
    primary: "#0000aa",
    primaryHover: "#000077",
    background: "#cfeceb",
    backgroundAlt: "#b8e0df",
    text: "#00292b",
    textMuted: "#12565a",
    border: "#7fc4c2",
    codeBackground: "#0000aa",
    codeBackgroundTop: "#0000aa",
    codeText: "#ffffff",
  },
  darkColors: {
    primary: "#55ffff",
    primaryHover: "#aaffff",
    background: "#000000",
    backgroundAlt: "#0d0d0d",
    text: "#aaaaaa",
    textMuted: "#7f7f7f",
    border: "#555555",
    codeBackground: "#0000aa",
    codeBackgroundTop: "#0000aa",
    codeText: "#ffffff",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0000aa 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #553300 18%, transparent)",
    "color-code-line-warning-border": "#553300",
    "color-code-line-error": "color-mix(in srgb, #aa0000 20%, transparent)",
    "color-code-line-error-border": "#aa0000",
    "color-code-line-add": "color-mix(in srgb, #005500 16%, transparent)",
    "color-code-line-add-border": "#005500",
    "color-code-line-remove": "color-mix(in srgb, #aa0000 14%, transparent)",
    "color-code-line-remove-border": "#aa0000",
    "color-code-line-focus": "color-mix(in srgb, #0000aa 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #0000aa 92%, #ffffff)",
    "color-code-title-text": "color-mix(in srgb, #ffffff 88%, #0000aa)",
    "color-code-title-border": "color-mix(in srgb, #ffffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #7fc4c2 92%, transparent)",
    "color-backdrop": "rgba(72, 83, 82, 0.62)",
    "surface-glass": "color-mix(in srgb, #b8e0df 62%, #cfeceb)",
    "surface-line": "color-mix(in srgb, #7fc4c2 72%, #cfeceb)",
    "brand-violet": "#aa00aa",
    "brand-cyan": "#005555",
    "brand-lime": "#005500",
    "brand-coral": "#aa0000",
    "brand-navy": "color-mix(in srgb, #00292b 70%, #cfeceb)",
    "brand-violet-rgb": "170, 0, 170",
    "brand-cyan-rgb": "0, 85, 85",
    "brand-lime-rgb": "0, 85, 0",
    "brand-coral-rgb": "170, 0, 0",
    "accent-a": "#0000aa",
    "accent-b": "#aa00aa",
    "accent-c": "#005555",
    "accent-warm": "#553300",
    "accent-cool": "#0000aa",
    "accent-a-ink": "#0000aa",
    "accent-b-ink": "#aa00aa",
    "accent-c-ink": "#005555",
    "accent-warm-ink": "#553300",
    "accent-cool-ink": "#0000aa",
    "accent-coral-ink": "#aa0000",
    "syntax-foreground": "#ffffff",
    "syntax-background": "#0000aa",
    "syntax-token-comment": "color-mix(in srgb, #ffffff 55%, #0000aa)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffffff 72%, #0000aa)",
    "syntax-token-keyword": "#ff55ff",
    "syntax-token-string": "#55ff55",
    "syntax-token-string-expression": "#55ff55",
    "syntax-token-constant": "#ffff55",
    "syntax-token-function": "#5555ff",
    "syntax-token-parameter": "#ff5555",
    "syntax-token-link": "#55ffff",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5555ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffff55 18%, transparent)",
    "color-code-line-warning-border": "#ffff55",
    "color-code-line-error": "color-mix(in srgb, #ff5555 20%, transparent)",
    "color-code-line-error-border": "#ff5555",
    "color-code-line-add": "color-mix(in srgb, #55ff55 16%, transparent)",
    "color-code-line-add-border": "#55ff55",
    "color-code-line-remove": "color-mix(in srgb, #ff5555 14%, transparent)",
    "color-code-line-remove-border": "#ff5555",
    "color-code-line-focus": "color-mix(in srgb, #55ffff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0000aa 92%, #ffffff)",
    "color-code-title-text": "color-mix(in srgb, #ffffff 88%, #0000aa)",
    "color-code-title-border": "color-mix(in srgb, #ffffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #555555 92%, transparent)",
    "color-backdrop": "rgba(0, 0, 0, 0.62)",
    "surface-glass": "color-mix(in srgb, #0d0d0d 62%, #000000)",
    "surface-line": "color-mix(in srgb, #555555 72%, #000000)",
    "brand-violet": "#ff55ff",
    "brand-cyan": "#55ffff",
    "brand-lime": "#55ff55",
    "brand-coral": "#ff5555",
    "brand-navy": "color-mix(in srgb, #aaaaaa 70%, #000000)",
    "brand-violet-rgb": "255, 85, 255",
    "brand-cyan-rgb": "85, 255, 255",
    "brand-lime-rgb": "85, 255, 85",
    "brand-coral-rgb": "255, 85, 85",
    "accent-a": "#55ffff",
    "accent-b": "#ff55ff",
    "accent-c": "#55ffff",
    "accent-warm": "#ffff55",
    "accent-cool": "#5555ff",
    "accent-a-ink": "#55ffff",
    "accent-b-ink": "#ff55ff",
    "accent-c-ink": "#55ffff",
    "accent-warm-ink": "#ffff55",
    "accent-cool-ink": "#6363ff",
    "accent-coral-ink": "#ff5555",
    "syntax-foreground": "#ffffff",
    "syntax-background": "#0000aa",
    "syntax-token-comment": "color-mix(in srgb, #ffffff 55%, #0000aa)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffffff 72%, #0000aa)",
    "syntax-token-keyword": "#ff55ff",
    "syntax-token-string": "#55ff55",
    "syntax-token-string-expression": "#55ff55",
    "syntax-token-constant": "#ffff55",
    "syntax-token-function": "#5555ff",
    "syntax-token-parameter": "#ff5555",
    "syntax-token-link": "#55ffff",
  },
};

export default commander;
