import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * One Dark — Atom One Light and One Dark.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const oneDark: ThemeConfig = {
  name: "one-dark",
  colors: {
    primary: "#386ad5",
    primaryHover: "#2a5fd4",
    background: "#fafafa",
    backgroundAlt: "#eaeaeb",
    text: "#383a42",
    textMuted: "#696c77",
    border: "#d0d0d1",
    codeBackground: "#eaeaeb",
    codeBackgroundTop: "#eaeaeb",
    codeText: "#383a42",
  },
  darkColors: {
    primary: "#61afef",
    primaryHover: "#8ac6f4",
    background: "#282c34",
    backgroundAlt: "#21252b",
    text: "#abb2bf",
    textMuted: "#8e939c",
    border: "#3e4451",
    codeBackground: "#21252b",
    codeBackgroundTop: "#21252b",
    codeText: "#abb2bf",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4078f2 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #c18401 18%, transparent)",
    "color-code-line-warning-border": "#c18401",
    "color-code-line-error": "color-mix(in srgb, #e45649 20%, transparent)",
    "color-code-line-error-border": "#e45649",
    "color-code-line-add": "color-mix(in srgb, #50a14f 16%, transparent)",
    "color-code-line-add-border": "#50a14f",
    "color-code-line-remove": "color-mix(in srgb, #e45649 14%, transparent)",
    "color-code-line-remove-border": "#e45649",
    "color-code-line-focus": "color-mix(in srgb, #386ad5 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #eaeaeb 92%, #383a42)",
    "color-code-title-text": "color-mix(in srgb, #383a42 88%, #eaeaeb)",
    "color-code-title-border": "color-mix(in srgb, #383a42 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #383a42 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d0d1 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eaeaeb 62%, #fafafa)",
    "surface-line": "color-mix(in srgb, #d0d0d1 72%, #fafafa)",
    "brand-violet": "#a626a4",
    "brand-cyan": "#0184bc",
    "brand-lime": "#50a14f",
    "brand-coral": "#e45649",
    "brand-navy": "color-mix(in srgb, #383a42 70%, #fafafa)",
    "brand-violet-rgb": "166, 38, 164",
    "brand-cyan-rgb": "1, 132, 188",
    "brand-lime-rgb": "80, 161, 79",
    "brand-coral-rgb": "228, 86, 73",
    "accent-a": "#386ad5",
    "accent-b": "#a626a4",
    "accent-c": "#0184bc",
    "accent-warm": "#c18401",
    "accent-cool": "#4078f2",
    "accent-a-ink": "#386ad5",
    "accent-b-ink": "#a626a4",
    "accent-c-ink": "#0179ad",
    "accent-warm-ink": "#9a6a01",
    "accent-cool-ink": "#386ad5",
    "accent-coral-ink": "#c0483d",
    "syntax-foreground": "#383a42",
    "syntax-background": "#eaeaeb",
    "syntax-token-comment": "color-mix(in srgb, #383a42 55%, #eaeaeb)",
    "syntax-token-punctuation": "color-mix(in srgb, #383a42 72%, #eaeaeb)",
    "syntax-token-keyword": "#a626a4",
    "syntax-token-string": "#50a14f",
    "syntax-token-string-expression": "#50a14f",
    "syntax-token-constant": "#c18401",
    "syntax-token-function": "#4078f2",
    "syntax-token-parameter": "#e45649",
    "syntax-token-link": "#0184bc",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #61afef 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e5c07b 18%, transparent)",
    "color-code-line-warning-border": "#e5c07b",
    "color-code-line-error": "color-mix(in srgb, #e06c75 20%, transparent)",
    "color-code-line-error-border": "#e06c75",
    "color-code-line-add": "color-mix(in srgb, #98c379 16%, transparent)",
    "color-code-line-add-border": "#98c379",
    "color-code-line-remove": "color-mix(in srgb, #e06c75 14%, transparent)",
    "color-code-line-remove-border": "#e06c75",
    "color-code-line-focus": "color-mix(in srgb, #61afef 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #21252b 92%, #abb2bf)",
    "color-code-title-text": "color-mix(in srgb, #abb2bf 88%, #21252b)",
    "color-code-title-border": "color-mix(in srgb, #abb2bf 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #abb2bf 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3e4451 92%, transparent)",
    "color-backdrop": "rgba(14, 15, 18, 0.62)",
    "surface-glass": "color-mix(in srgb, #21252b 62%, #282c34)",
    "surface-line": "color-mix(in srgb, #3e4451 72%, #282c34)",
    "brand-violet": "#c678dd",
    "brand-cyan": "#56b6c2",
    "brand-lime": "#98c379",
    "brand-coral": "#e06c75",
    "brand-navy": "color-mix(in srgb, #abb2bf 70%, #282c34)",
    "brand-violet-rgb": "198, 120, 221",
    "brand-cyan-rgb": "86, 182, 194",
    "brand-lime-rgb": "152, 195, 121",
    "brand-coral-rgb": "224, 108, 117",
    "accent-a": "#61afef",
    "accent-b": "#c678dd",
    "accent-c": "#56b6c2",
    "accent-warm": "#e5c07b",
    "accent-cool": "#61afef",
    "accent-a-ink": "#61afef",
    "accent-b-ink": "#c678dd",
    "accent-c-ink": "#56b6c2",
    "accent-warm-ink": "#e5c07b",
    "accent-cool-ink": "#61afef",
    "accent-coral-ink": "#e1727b",
    "syntax-foreground": "#abb2bf",
    "syntax-background": "#21252b",
    "syntax-token-comment": "color-mix(in srgb, #abb2bf 55%, #21252b)",
    "syntax-token-punctuation": "color-mix(in srgb, #abb2bf 72%, #21252b)",
    "syntax-token-keyword": "#c678dd",
    "syntax-token-string": "#98c379",
    "syntax-token-string-expression": "#98c379",
    "syntax-token-constant": "#e5c07b",
    "syntax-token-function": "#61afef",
    "syntax-token-parameter": "#e06c75",
    "syntax-token-link": "#56b6c2",
  },
};

export default oneDark;
