import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * One Dark — One Light and One Dark Pro.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const oneDarkPro: ThemeConfig = {
  name: "one-dark-pro",
  colors: {
    primary: "#121417",
    primaryHover: "#5669be",
    background: "#fafafa",
    backgroundAlt: "#eaeaeb",
    text: "#383a42",
    textMuted: "#6d6d72",
    border: "#dbdbdc",
    codeBackground: "#fafafa",
    codeBackgroundTop: "#fafafa",
    codeText: "#383a42",
  },
  darkColors: {
    primary: "#61afef",
    primaryHover: "#5990ff",
    background: "#282c34",
    backgroundAlt: "#21252b",
    text: "#abb2bf",
    textMuted: "#90959e",
    border: "#181a1f",
    codeBackground: "#282c34",
    codeBackgroundTop: "#282c34",
    codeText: "#abb2bf",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #526fff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #986801 18%, transparent)",
    "color-code-line-warning-border": "#986801",
    "color-code-line-error": "color-mix(in srgb, #000000 20%, transparent)",
    "color-code-line-error-border": "#000000",
    "color-code-line-add": "color-mix(in srgb, #50a14f 16%, transparent)",
    "color-code-line-add-border": "#50a14f",
    "color-code-line-remove": "color-mix(in srgb, #000000 14%, transparent)",
    "color-code-line-remove-border": "#000000",
    "color-code-line-focus": "color-mix(in srgb, #121417 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #fafafa 92%, #383a42)",
    "color-code-title-text": "color-mix(in srgb, #383a42 88%, #fafafa)",
    "color-code-title-border": "color-mix(in srgb, #383a42 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #383a42 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dbdbdc 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eaeaeb 62%, #fafafa)",
    "surface-line": "color-mix(in srgb, #dbdbdc 72%, #fafafa)",
    "brand-violet": "#4078f2",
    "brand-cyan": "#526fff",
    "brand-lime": "#50a14f",
    "brand-coral": "#000000",
    "brand-navy": "color-mix(in srgb, #383a42 70%, #fafafa)",
    "brand-violet-rgb": "64, 120, 242",
    "brand-cyan-rgb": "82, 111, 255",
    "brand-lime-rgb": "80, 161, 79",
    "brand-coral-rgb": "0, 0, 0",
    "accent-a": "#121417",
    "accent-b": "#4078f2",
    "accent-c": "#526fff",
    "accent-warm": "#986801",
    "accent-cool": "#526fff",
    "accent-a-ink": "#121417",
    "accent-b-ink": "#386ad5",
    "accent-c-ink": "#4b66eb",
    "accent-warm-ink": "#986801",
    "accent-cool-ink": "#4b66eb",
    "accent-coral-ink": "#000000",
    "syntax-foreground": "#383a42",
    "syntax-background": "#fafafa",
    "syntax-token-comment": "#a0a1a7",
    "syntax-token-punctuation": "#a0a1a7",
    "syntax-token-keyword": "#a626a4",
    "syntax-token-string": "#50a14f",
    "syntax-token-string-expression": "#50a14f",
    "syntax-token-constant": "#986801",
    "syntax-token-function": "#0184bc",
    "syntax-token-parameter": "#383a42",
    "syntax-token-link": "#e45649",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4aa5f0 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d18f52 18%, transparent)",
    "color-code-line-warning-border": "#d18f52",
    "color-code-line-error": "color-mix(in srgb, #e05561 20%, transparent)",
    "color-code-line-error-border": "#e05561",
    "color-code-line-add": "color-mix(in srgb, #8cc265 16%, transparent)",
    "color-code-line-add-border": "#8cc265",
    "color-code-line-remove": "color-mix(in srgb, #e05561 14%, transparent)",
    "color-code-line-remove-border": "#e05561",
    "color-code-line-focus": "color-mix(in srgb, #61afef 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #282c34 92%, #abb2bf)",
    "color-code-title-text": "color-mix(in srgb, #abb2bf 88%, #282c34)",
    "color-code-title-border": "color-mix(in srgb, #abb2bf 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #abb2bf 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #181a1f 92%, transparent)",
    "color-backdrop": "rgba(14, 15, 18, 0.62)",
    "surface-glass": "color-mix(in srgb, #21252b 62%, #282c34)",
    "surface-line": "color-mix(in srgb, #181a1f 72%, #282c34)",
    "brand-violet": "#c162de",
    "brand-cyan": "#42b3c2",
    "brand-lime": "#8cc265",
    "brand-coral": "#e05561",
    "brand-navy": "color-mix(in srgb, #abb2bf 70%, #282c34)",
    "brand-violet-rgb": "193, 98, 222",
    "brand-cyan-rgb": "66, 179, 194",
    "brand-lime-rgb": "140, 194, 101",
    "brand-coral-rgb": "224, 85, 97",
    "accent-a": "#61afef",
    "accent-b": "#c162de",
    "accent-c": "#42b3c2",
    "accent-warm": "#d18f52",
    "accent-cool": "#4aa5f0",
    "accent-a-ink": "#61afef",
    "accent-b-ink": "#c66fe1",
    "accent-c-ink": "#42b3c2",
    "accent-warm-ink": "#d18f52",
    "accent-cool-ink": "#4aa5f0",
    "accent-coral-ink": "#e5707a",
    "syntax-foreground": "#abb2bf",
    "syntax-background": "#282c34",
    "syntax-token-comment": "#5c6370",
    "syntax-token-punctuation": "#e06c75",
    "syntax-token-keyword": "#c678dd",
    "syntax-token-string": "#98c379",
    "syntax-token-string-expression": "#98c379",
    "syntax-token-constant": "#d19a66",
    "syntax-token-function": "#61afef",
    "syntax-token-parameter": "#e5c07b",
    "syntax-token-link": "#61afef",
  },
};
