import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Melange — Muted earth tones, warm and unhurried.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const melange: ThemeConfig = {
  name: "melange",
  colors: {
    primary: "#7d5c39",
    primaryHover: "#63482c",
    background: "#f1f1f1",
    backgroundAlt: "#e9e1db",
    text: "#54433a",
    textMuted: "#7d6658",
    border: "#d9cdc3",
    codeBackground: "#e9e1db",
    codeBackgroundTop: "#e9e1db",
    codeText: "#54433a",
  },
  darkColors: {
    primary: "#ebc06d",
    primaryHover: "#f2d192",
    background: "#292522",
    backgroundAlt: "#34302c",
    text: "#ece1d7",
    textMuted: "#a08e7a",
    border: "#403a35",
    codeBackground: "#211f1c",
    codeBackgroundTop: "#211f1c",
    codeText: "#ece1d7",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5a6b8a 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8a6f2a 18%, transparent)",
    "color-code-line-warning-border": "#8a6f2a",
    "color-code-line-error": "color-mix(in srgb, #a8503a 20%, transparent)",
    "color-code-line-error-border": "#a8503a",
    "color-code-line-add": "color-mix(in srgb, #5c6f3f 16%, transparent)",
    "color-code-line-add-border": "#5c6f3f",
    "color-code-line-remove": "color-mix(in srgb, #a8503a 14%, transparent)",
    "color-code-line-remove-border": "#a8503a",
    "color-code-line-focus": "color-mix(in srgb, #7d5c39 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #e9e1db 92%, #54433a)",
    "color-code-title-text": "color-mix(in srgb, #54433a 88%, #e9e1db)",
    "color-code-title-border": "color-mix(in srgb, #54433a 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #54433a 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d9cdc3 92%, transparent)",
    "color-backdrop": "rgba(84, 84, 84, 0.62)",
    "surface-glass": "color-mix(in srgb, #e9e1db 62%, #f1f1f1)",
    "surface-line": "color-mix(in srgb, #d9cdc3 72%, #f1f1f1)",
    "brand-violet": "#8a5570",
    "brand-cyan": "#4f7068",
    "brand-lime": "#5c6f3f",
    "brand-coral": "#a8503a",
    "brand-navy": "color-mix(in srgb, #54433a 70%, #f1f1f1)",
    "brand-violet-rgb": "138, 85, 112",
    "brand-cyan-rgb": "79, 112, 104",
    "brand-lime-rgb": "92, 111, 63",
    "brand-coral-rgb": "168, 80, 58",
    "accent-a": "#7d5c39",
    "accent-b": "#8a5570",
    "accent-c": "#4f7068",
    "accent-warm": "#8a6f2a",
    "accent-cool": "#5a6b8a",
    "accent-a-ink": "#7d5c39",
    "accent-b-ink": "#8a5570",
    "accent-c-ink": "#4f7068",
    "accent-warm-ink": "#846b28",
    "accent-cool-ink": "#5a6b8a",
    "accent-coral-ink": "#a8503a",
    "syntax-foreground": "#54433a",
    "syntax-background": "#e9e1db",
    "syntax-token-comment": "color-mix(in srgb, #54433a 55%, #e9e1db)",
    "syntax-token-punctuation": "color-mix(in srgb, #54433a 72%, #e9e1db)",
    "syntax-token-keyword": "#8a5570",
    "syntax-token-string": "#5c6f3f",
    "syntax-token-string-expression": "#5c6f3f",
    "syntax-token-constant": "#8a6f2a",
    "syntax-token-function": "#5a6b8a",
    "syntax-token-parameter": "#a8503a",
    "syntax-token-link": "#4f7068",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #a3a9ce 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ebc06d 18%, transparent)",
    "color-code-line-warning-border": "#ebc06d",
    "color-code-line-error": "color-mix(in srgb, #d47766 20%, transparent)",
    "color-code-line-error-border": "#d47766",
    "color-code-line-add": "color-mix(in srgb, #85b695 16%, transparent)",
    "color-code-line-add-border": "#85b695",
    "color-code-line-remove": "color-mix(in srgb, #d47766 14%, transparent)",
    "color-code-line-remove-border": "#d47766",
    "color-code-line-focus": "color-mix(in srgb, #ebc06d 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #211f1c 92%, #ece1d7)",
    "color-code-title-text": "color-mix(in srgb, #ece1d7 88%, #211f1c)",
    "color-code-title-border": "color-mix(in srgb, #ece1d7 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ece1d7 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #403a35 92%, transparent)",
    "color-backdrop": "rgba(14, 13, 12, 0.62)",
    "surface-glass": "color-mix(in srgb, #34302c 62%, #292522)",
    "surface-line": "color-mix(in srgb, #403a35 72%, #292522)",
    "brand-violet": "#cf9bc2",
    "brand-cyan": "#89b3b6",
    "brand-lime": "#85b695",
    "brand-coral": "#d47766",
    "brand-navy": "color-mix(in srgb, #ece1d7 70%, #292522)",
    "brand-violet-rgb": "207, 155, 194",
    "brand-cyan-rgb": "137, 179, 182",
    "brand-lime-rgb": "133, 182, 149",
    "brand-coral-rgb": "212, 119, 102",
    "accent-a": "#ebc06d",
    "accent-b": "#cf9bc2",
    "accent-c": "#89b3b6",
    "accent-warm": "#ebc06d",
    "accent-cool": "#a3a9ce",
    "accent-a-ink": "#ebc06d",
    "accent-b-ink": "#cf9bc2",
    "accent-c-ink": "#89b3b6",
    "accent-warm-ink": "#ebc06d",
    "accent-cool-ink": "#a3a9ce",
    "accent-coral-ink": "#d47766",
    "syntax-foreground": "#ece1d7",
    "syntax-background": "#211f1c",
    "syntax-token-comment": "color-mix(in srgb, #ece1d7 55%, #211f1c)",
    "syntax-token-punctuation": "color-mix(in srgb, #ece1d7 72%, #211f1c)",
    "syntax-token-keyword": "#cf9bc2",
    "syntax-token-string": "#85b695",
    "syntax-token-string-expression": "#85b695",
    "syntax-token-constant": "#ebc06d",
    "syntax-token-function": "#a3a9ce",
    "syntax-token-parameter": "#d47766",
    "syntax-token-link": "#89b3b6",
  },
};
