import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Sepia — Low-glare sepia tuned for long reading sessions.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const sepia: ThemeConfig = {
  name: "sepia",
  colors: {
    primary: "#8a5a2b",
    primaryHover: "#6d4520",
    background: "#f6efe3",
    backgroundAlt: "#efe6d6",
    text: "#3a3229",
    textMuted: "#6f6355",
    border: "#ddd0ba",
    codeBackground: "#efe6d6",
    codeBackgroundTop: "#efe6d6",
    codeText: "#3a3229",
  },
  darkColors: {
    primary: "#d9a066",
    primaryHover: "#e8bd8e",
    background: "#1c1814",
    backgroundAlt: "#26211b",
    text: "#e8dcc8",
    textMuted: "#a5977f",
    border: "#3a322a",
    codeBackground: "#161310",
    codeBackgroundTop: "#161310",
    codeText: "#e8dcc8",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4a6478 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #96702a 18%, transparent)",
    "color-code-line-warning-border": "#96702a",
    "color-code-line-error": "color-mix(in srgb, #a63d40 20%, transparent)",
    "color-code-line-error-border": "#a63d40",
    "color-code-line-add": "color-mix(in srgb, #5f6f3f 16%, transparent)",
    "color-code-line-add-border": "#5f6f3f",
    "color-code-line-remove": "color-mix(in srgb, #a63d40 14%, transparent)",
    "color-code-line-remove-border": "#a63d40",
    "color-code-line-focus": "color-mix(in srgb, #8a5a2b 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #efe6d6 92%, #3a3229)",
    "color-code-title-text": "color-mix(in srgb, #3a3229 88%, #efe6d6)",
    "color-code-title-border": "color-mix(in srgb, #3a3229 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #3a3229 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ddd0ba 92%, transparent)",
    "color-backdrop": "rgba(86, 84, 79, 0.62)",
    "surface-glass": "color-mix(in srgb, #efe6d6 62%, #f6efe3)",
    "surface-line": "color-mix(in srgb, #ddd0ba 72%, #f6efe3)",
    "brand-violet": "#7c5271",
    "brand-cyan": "#3f6f68",
    "brand-lime": "#5f6f3f",
    "brand-coral": "#a63d40",
    "brand-navy": "color-mix(in srgb, #3a3229 70%, #f6efe3)",
    "brand-violet-rgb": "124, 82, 113",
    "brand-cyan-rgb": "63, 111, 104",
    "brand-lime-rgb": "95, 111, 63",
    "brand-coral-rgb": "166, 61, 64",
    "accent-a": "#8a5a2b",
    "accent-b": "#7c5271",
    "accent-c": "#3f6f68",
    "accent-warm": "#96702a",
    "accent-cool": "#4a6478",
    "accent-a-ink": "#8a5a2b",
    "accent-b-ink": "#7c5271",
    "accent-c-ink": "#3f6f68",
    "accent-warm-ink": "#8a6727",
    "accent-cool-ink": "#4a6478",
    "accent-coral-ink": "#a63d40",
    "syntax-foreground": "#3a3229",
    "syntax-background": "#efe6d6",
    "syntax-token-comment": "color-mix(in srgb, #3a3229 55%, #efe6d6)",
    "syntax-token-punctuation": "color-mix(in srgb, #3a3229 72%, #efe6d6)",
    "syntax-token-keyword": "#7c5271",
    "syntax-token-string": "#5f6f3f",
    "syntax-token-string-expression": "#5f6f3f",
    "syntax-token-constant": "#96702a",
    "syntax-token-function": "#4a6478",
    "syntax-token-parameter": "#a63d40",
    "syntax-token-link": "#3f6f68",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8fa8bc 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dcbb7a 18%, transparent)",
    "color-code-line-warning-border": "#dcbb7a",
    "color-code-line-error": "color-mix(in srgb, #d38b7f 20%, transparent)",
    "color-code-line-error-border": "#d38b7f",
    "color-code-line-add": "color-mix(in srgb, #a3b077 16%, transparent)",
    "color-code-line-add-border": "#a3b077",
    "color-code-line-remove": "color-mix(in srgb, #d38b7f 14%, transparent)",
    "color-code-line-remove-border": "#d38b7f",
    "color-code-line-focus": "color-mix(in srgb, #d9a066 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #161310 92%, #e8dcc8)",
    "color-code-title-text": "color-mix(in srgb, #e8dcc8 88%, #161310)",
    "color-code-title-border": "color-mix(in srgb, #e8dcc8 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e8dcc8 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3a322a 92%, transparent)",
    "color-backdrop": "rgba(10, 8, 7, 0.62)",
    "surface-glass": "color-mix(in srgb, #26211b 62%, #1c1814)",
    "surface-line": "color-mix(in srgb, #3a322a 72%, #1c1814)",
    "brand-violet": "#c096b4",
    "brand-cyan": "#84b0a8",
    "brand-lime": "#a3b077",
    "brand-coral": "#d38b7f",
    "brand-navy": "color-mix(in srgb, #e8dcc8 70%, #1c1814)",
    "brand-violet-rgb": "192, 150, 180",
    "brand-cyan-rgb": "132, 176, 168",
    "brand-lime-rgb": "163, 176, 119",
    "brand-coral-rgb": "211, 139, 127",
    "accent-a": "#d9a066",
    "accent-b": "#c096b4",
    "accent-c": "#84b0a8",
    "accent-warm": "#dcbb7a",
    "accent-cool": "#8fa8bc",
    "accent-a-ink": "#d9a066",
    "accent-b-ink": "#c096b4",
    "accent-c-ink": "#84b0a8",
    "accent-warm-ink": "#dcbb7a",
    "accent-cool-ink": "#8fa8bc",
    "accent-coral-ink": "#d38b7f",
    "syntax-foreground": "#e8dcc8",
    "syntax-background": "#161310",
    "syntax-token-comment": "color-mix(in srgb, #e8dcc8 55%, #161310)",
    "syntax-token-punctuation": "color-mix(in srgb, #e8dcc8 72%, #161310)",
    "syntax-token-keyword": "#c096b4",
    "syntax-token-string": "#a3b077",
    "syntax-token-string-expression": "#a3b077",
    "syntax-token-constant": "#dcbb7a",
    "syntax-token-function": "#8fa8bc",
    "syntax-token-parameter": "#d38b7f",
    "syntax-token-link": "#84b0a8",
  },
};
