import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Mono — Pure monochrome, zero hue.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const mono: ThemeConfig = {
  name: "mono",
  colors: {
    primary: "#111111",
    primaryHover: "#000000",
    background: "#ffffff",
    backgroundAlt: "#f2f2f2",
    text: "#111111",
    textMuted: "#666666",
    border: "#d4d4d4",
    codeBackground: "#141414",
    codeBackgroundTop: "#141414",
    codeText: "#f2f2f2",
  },
  darkColors: {
    primary: "#f5f5f5",
    primaryHover: "#ffffff",
    background: "#0a0a0a",
    backgroundAlt: "#161616",
    text: "#f5f5f5",
    textMuted: "#9b9b9b",
    border: "#2e2e2e",
    codeBackground: "#111111",
    codeBackgroundTop: "#111111",
    codeText: "#ededed",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3a3a3a 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #6e6e6e 18%, transparent)",
    "color-code-line-warning-border": "#6e6e6e",
    "color-code-line-error": "color-mix(in srgb, #4a4a4a 20%, transparent)",
    "color-code-line-error-border": "#4a4a4a",
    "color-code-line-add": "color-mix(in srgb, #5c5c5c 16%, transparent)",
    "color-code-line-add-border": "#5c5c5c",
    "color-code-line-remove": "color-mix(in srgb, #4a4a4a 14%, transparent)",
    "color-code-line-remove-border": "#4a4a4a",
    "color-code-line-focus": "color-mix(in srgb, #111111 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #141414 92%, #f2f2f2)",
    "color-code-title-text": "color-mix(in srgb, #f2f2f2 88%, #141414)",
    "color-code-title-border": "color-mix(in srgb, #f2f2f2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f2f2f2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d4d4d4 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f2f2f2 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d4d4d4 72%, #ffffff)",
    "brand-violet": "#2b2b2b",
    "brand-cyan": "#818181",
    "brand-lime": "#5c5c5c",
    "brand-coral": "#4a4a4a",
    "brand-navy": "color-mix(in srgb, #111111 70%, #ffffff)",
    "brand-violet-rgb": "43, 43, 43",
    "brand-cyan-rgb": "129, 129, 129",
    "brand-lime-rgb": "92, 92, 92",
    "brand-coral-rgb": "74, 74, 74",
    "accent-a": "#111111",
    "accent-b": "#2b2b2b",
    "accent-c": "#818181",
    "accent-warm": "#6e6e6e",
    "accent-cool": "#3a3a3a",
    "accent-a-ink": "#111111",
    "accent-b-ink": "#2b2b2b",
    "accent-c-ink": "#727272",
    "accent-warm-ink": "#6e6e6e",
    "accent-cool-ink": "#3a3a3a",
    "accent-coral-ink": "#4a4a4a",
    "shiki-foreground": "#f2f2f2",
    "shiki-background": "#141414",
    "shiki-token-comment": "color-mix(in srgb, #f2f2f2 55%, #141414)",
    "shiki-token-punctuation": "color-mix(in srgb, #f2f2f2 72%, #141414)",
    "shiki-token-keyword": "#e6e6e6",
    "shiki-token-string": "#b4b4b4",
    "shiki-token-string-expression": "#b4b4b4",
    "shiki-token-constant": "#a0a0a0",
    "shiki-token-function": "#d8d8d8",
    "shiki-token-parameter": "#c9c9c9",
    "shiki-token-link": "#8c8c8c",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #d8d8d8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #a0a0a0 18%, transparent)",
    "color-code-line-warning-border": "#a0a0a0",
    "color-code-line-error": "color-mix(in srgb, #c9c9c9 20%, transparent)",
    "color-code-line-error-border": "#c9c9c9",
    "color-code-line-add": "color-mix(in srgb, #b4b4b4 16%, transparent)",
    "color-code-line-add-border": "#b4b4b4",
    "color-code-line-remove": "color-mix(in srgb, #c9c9c9 14%, transparent)",
    "color-code-line-remove-border": "#c9c9c9",
    "color-code-line-focus": "color-mix(in srgb, #f5f5f5 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #111111 92%, #ededed)",
    "color-code-title-text": "color-mix(in srgb, #ededed 88%, #111111)",
    "color-code-title-border": "color-mix(in srgb, #ededed 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ededed 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2e2e2e 92%, transparent)",
    "color-backdrop": "rgba(4, 4, 4, 0.62)",
    "surface-glass": "color-mix(in srgb, #161616 62%, #0a0a0a)",
    "surface-line": "color-mix(in srgb, #2e2e2e 72%, #0a0a0a)",
    "brand-violet": "#e6e6e6",
    "brand-cyan": "#8c8c8c",
    "brand-lime": "#b4b4b4",
    "brand-coral": "#c9c9c9",
    "brand-navy": "color-mix(in srgb, #f5f5f5 70%, #0a0a0a)",
    "brand-violet-rgb": "230, 230, 230",
    "brand-cyan-rgb": "140, 140, 140",
    "brand-lime-rgb": "180, 180, 180",
    "brand-coral-rgb": "201, 201, 201",
    "accent-a": "#f5f5f5",
    "accent-b": "#e6e6e6",
    "accent-c": "#8c8c8c",
    "accent-warm": "#a0a0a0",
    "accent-cool": "#d8d8d8",
    "accent-a-ink": "#f5f5f5",
    "accent-b-ink": "#e6e6e6",
    "accent-c-ink": "#8c8c8c",
    "accent-warm-ink": "#a0a0a0",
    "accent-cool-ink": "#d8d8d8",
    "accent-coral-ink": "#c9c9c9",
    "shiki-foreground": "#ededed",
    "shiki-background": "#111111",
    "shiki-token-comment": "color-mix(in srgb, #ededed 55%, #111111)",
    "shiki-token-punctuation": "color-mix(in srgb, #ededed 72%, #111111)",
    "shiki-token-keyword": "#e6e6e6",
    "shiki-token-string": "#b4b4b4",
    "shiki-token-string-expression": "#b4b4b4",
    "shiki-token-constant": "#a0a0a0",
    "shiki-token-function": "#d8d8d8",
    "shiki-token-parameter": "#c9c9c9",
    "shiki-token-link": "#8c8c8c",
  },
};

export default mono;
