import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Night Owl — Sarah Drasner's Light Owl and Night Owl.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const nightOwl: ThemeConfig = {
  name: "night-owl",
  colors: {
    primary: "#0a7e82",
    primaryHover: "#0a7a7e",
    background: "#fbfbfb",
    backgroundAlt: "#f0f0f0",
    text: "#403f53",
    textMuted: "#706f7b",
    border: "#d9d9d9",
    codeBackground: "#f0f0f0",
    codeBackgroundTop: "#f0f0f0",
    codeText: "#403f53",
  },
  darkColors: {
    primary: "#82aaff",
    primaryHover: "#a6c4ff",
    background: "#011627",
    backgroundAlt: "#0b2942",
    text: "#d6deeb",
    textMuted: "#8badc1",
    border: "#1d3b53",
    codeBackground: "#011425",
    codeBackgroundTop: "#011425",
    codeText: "#d6deeb",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #288ed7 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #daaa01 18%, transparent)",
    "color-code-line-warning-border": "#daaa01",
    "color-code-line-error": "color-mix(in srgb, #de3d3b 20%, transparent)",
    "color-code-line-error-border": "#de3d3b",
    "color-code-line-add": "color-mix(in srgb, #08916a 16%, transparent)",
    "color-code-line-add-border": "#08916a",
    "color-code-line-remove": "color-mix(in srgb, #de3d3b 14%, transparent)",
    "color-code-line-remove-border": "#de3d3b",
    "color-code-line-focus": "color-mix(in srgb, #0a7e82 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f0f0f0 92%, #403f53)",
    "color-code-title-text": "color-mix(in srgb, #403f53 88%, #f0f0f0)",
    "color-code-title-border": "color-mix(in srgb, #403f53 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #403f53 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d9d9d9 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f0f0f0 62%, #fbfbfb)",
    "surface-line": "color-mix(in srgb, #d9d9d9 72%, #fbfbfb)",
    "brand-violet": "#994cc3",
    "brand-cyan": "#0c969b",
    "brand-lime": "#08916a",
    "brand-coral": "#de3d3b",
    "brand-navy": "color-mix(in srgb, #403f53 70%, #fbfbfb)",
    "brand-violet-rgb": "153, 76, 195",
    "brand-cyan-rgb": "12, 150, 155",
    "brand-lime-rgb": "8, 145, 106",
    "brand-coral-rgb": "222, 61, 59",
    "accent-a": "#0a7e82",
    "accent-b": "#994cc3",
    "accent-c": "#0c969b",
    "accent-warm": "#daaa01",
    "accent-cool": "#288ed7",
    "accent-a-ink": "#0a7e82",
    "accent-b-ink": "#994cc3",
    "accent-c-ink": "#0a7e82",
    "accent-warm-ink": "#8c6d01",
    "accent-cool-ink": "#2277b5",
    "accent-coral-ink": "#cc3836",
    "syntax-foreground": "#403f53",
    "syntax-background": "#f0f0f0",
    "syntax-token-comment": "color-mix(in srgb, #403f53 55%, #f0f0f0)",
    "syntax-token-punctuation": "color-mix(in srgb, #403f53 72%, #f0f0f0)",
    "syntax-token-keyword": "#994cc3",
    "syntax-token-string": "#08916a",
    "syntax-token-string-expression": "#08916a",
    "syntax-token-constant": "#daaa01",
    "syntax-token-function": "#288ed7",
    "syntax-token-parameter": "#de3d3b",
    "syntax-token-link": "#0c969b",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #82aaff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ecc48d 18%, transparent)",
    "color-code-line-warning-border": "#ecc48d",
    "color-code-line-error": "color-mix(in srgb, #ef5350 20%, transparent)",
    "color-code-line-error-border": "#ef5350",
    "color-code-line-add": "color-mix(in srgb, #addb67 16%, transparent)",
    "color-code-line-add-border": "#addb67",
    "color-code-line-remove": "color-mix(in srgb, #ef5350 14%, transparent)",
    "color-code-line-remove-border": "#ef5350",
    "color-code-line-focus": "color-mix(in srgb, #82aaff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #011425 92%, #d6deeb)",
    "color-code-title-text": "color-mix(in srgb, #d6deeb 88%, #011425)",
    "color-code-title-border": "color-mix(in srgb, #d6deeb 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #d6deeb 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1d3b53 92%, transparent)",
    "color-backdrop": "rgba(0, 8, 14, 0.62)",
    "surface-glass": "color-mix(in srgb, #0b2942 62%, #011627)",
    "surface-line": "color-mix(in srgb, #1d3b53 72%, #011627)",
    "brand-violet": "#c792ea",
    "brand-cyan": "#7fdbca",
    "brand-lime": "#addb67",
    "brand-coral": "#ef5350",
    "brand-navy": "color-mix(in srgb, #d6deeb 70%, #011627)",
    "brand-violet-rgb": "199, 146, 234",
    "brand-cyan-rgb": "127, 219, 202",
    "brand-lime-rgb": "173, 219, 103",
    "brand-coral-rgb": "239, 83, 80",
    "accent-a": "#82aaff",
    "accent-b": "#c792ea",
    "accent-c": "#7fdbca",
    "accent-warm": "#ecc48d",
    "accent-cool": "#82aaff",
    "accent-a-ink": "#82aaff",
    "accent-b-ink": "#c792ea",
    "accent-c-ink": "#7fdbca",
    "accent-warm-ink": "#ecc48d",
    "accent-cool-ink": "#82aaff",
    "accent-coral-ink": "#ef5350",
    "syntax-foreground": "#d6deeb",
    "syntax-background": "#011425",
    "syntax-token-comment": "color-mix(in srgb, #d6deeb 55%, #011425)",
    "syntax-token-punctuation": "color-mix(in srgb, #d6deeb 72%, #011425)",
    "syntax-token-keyword": "#c792ea",
    "syntax-token-string": "#addb67",
    "syntax-token-string-expression": "#addb67",
    "syntax-token-constant": "#ecc48d",
    "syntax-token-function": "#82aaff",
    "syntax-token-parameter": "#ef5350",
    "syntax-token-link": "#7fdbca",
  },
};

export default nightOwl;
