import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Porcelain — Soft warm white with muted blue-grey.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const porcelain: ThemeConfig = {
  name: "porcelain",
  colors: {
    primary: "#4b6b8a",
    primaryHover: "#37516a",
    background: "#fcfbf9",
    backgroundAlt: "#f3f1ec",
    text: "#1c1b19",
    textMuted: "#6f6c66",
    border: "#e6e3dc",
    codeBackground: "#f3f1ec",
    codeBackgroundTop: "#f3f1ec",
    codeText: "#1c1b19",
  },
  darkColors: {
    primary: "#9dbcd8",
    primaryHover: "#bcd3e8",
    background: "#171614",
    backgroundAlt: "#1f1e1b",
    text: "#eceae4",
    textMuted: "#9a978f",
    border: "#2c2a26",
    codeBackground: "#111110",
    codeBackgroundTop: "#111110",
    codeText: "#eceae4",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4b6b8a 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8c6c24 18%, transparent)",
    "color-code-line-warning-border": "#8c6c24",
    "color-code-line-error": "color-mix(in srgb, #a94a42 20%, transparent)",
    "color-code-line-error-border": "#a94a42",
    "color-code-line-add": "color-mix(in srgb, #4d7050 16%, transparent)",
    "color-code-line-add-border": "#4d7050",
    "color-code-line-remove": "color-mix(in srgb, #a94a42 14%, transparent)",
    "color-code-line-remove-border": "#a94a42",
    "color-code-line-focus": "color-mix(in srgb, #4b6b8a 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f3f1ec 92%, #1c1b19)",
    "color-code-title-text": "color-mix(in srgb, #1c1b19 88%, #f3f1ec)",
    "color-code-title-border": "color-mix(in srgb, #1c1b19 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1c1b19 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e6e3dc 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 87, 0.62)",
    "surface-glass": "color-mix(in srgb, #f3f1ec 62%, #fcfbf9)",
    "surface-line": "color-mix(in srgb, #e6e3dc 72%, #fcfbf9)",
    "brand-violet": "#7a5480",
    "brand-cyan": "#3d6f72",
    "brand-lime": "#4d7050",
    "brand-coral": "#a94a42",
    "brand-navy": "color-mix(in srgb, #1c1b19 70%, #fcfbf9)",
    "brand-violet-rgb": "122, 84, 128",
    "brand-cyan-rgb": "61, 111, 114",
    "brand-lime-rgb": "77, 112, 80",
    "brand-coral-rgb": "169, 74, 66",
    "accent-a": "#4b6b8a",
    "accent-b": "#7a5480",
    "accent-c": "#3d6f72",
    "accent-warm": "#8c6c24",
    "accent-cool": "#4b6b8a",
    "accent-a-ink": "#4b6b8a",
    "accent-b-ink": "#7a5480",
    "accent-c-ink": "#3d6f72",
    "accent-warm-ink": "#8c6c24",
    "accent-cool-ink": "#4b6b8a",
    "accent-coral-ink": "#a94a42",
    "syntax-foreground": "#1c1b19",
    "syntax-background": "#f3f1ec",
    "syntax-token-comment": "color-mix(in srgb, #1c1b19 55%, #f3f1ec)",
    "syntax-token-punctuation": "color-mix(in srgb, #1c1b19 72%, #f3f1ec)",
    "syntax-token-keyword": "#7a5480",
    "syntax-token-string": "#4d7050",
    "syntax-token-string-expression": "#4d7050",
    "syntax-token-constant": "#8c6c24",
    "syntax-token-function": "#4b6b8a",
    "syntax-token-parameter": "#a94a42",
    "syntax-token-link": "#3d6f72",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #9dbcd8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dcbe86 18%, transparent)",
    "color-code-line-warning-border": "#dcbe86",
    "color-code-line-error": "color-mix(in srgb, #e59187 20%, transparent)",
    "color-code-line-error-border": "#e59187",
    "color-code-line-add": "color-mix(in srgb, #9cc39e 16%, transparent)",
    "color-code-line-add-border": "#9cc39e",
    "color-code-line-remove": "color-mix(in srgb, #e59187 14%, transparent)",
    "color-code-line-remove-border": "#e59187",
    "color-code-line-focus": "color-mix(in srgb, #9dbcd8 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #111110 92%, #eceae4)",
    "color-code-title-text": "color-mix(in srgb, #eceae4 88%, #111110)",
    "color-code-title-border": "color-mix(in srgb, #eceae4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #eceae4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2c2a26 92%, transparent)",
    "color-backdrop": "rgba(8, 8, 7, 0.62)",
    "surface-glass": "color-mix(in srgb, #1f1e1b 62%, #171614)",
    "surface-line": "color-mix(in srgb, #2c2a26 72%, #171614)",
    "brand-violet": "#bfa0c6",
    "brand-cyan": "#88bfc2",
    "brand-lime": "#9cc39e",
    "brand-coral": "#e59187",
    "brand-navy": "color-mix(in srgb, #eceae4 70%, #171614)",
    "brand-violet-rgb": "191, 160, 198",
    "brand-cyan-rgb": "136, 191, 194",
    "brand-lime-rgb": "156, 195, 158",
    "brand-coral-rgb": "229, 145, 135",
    "accent-a": "#9dbcd8",
    "accent-b": "#bfa0c6",
    "accent-c": "#88bfc2",
    "accent-warm": "#dcbe86",
    "accent-cool": "#9dbcd8",
    "accent-a-ink": "#9dbcd8",
    "accent-b-ink": "#bfa0c6",
    "accent-c-ink": "#88bfc2",
    "accent-warm-ink": "#dcbe86",
    "accent-cool-ink": "#9dbcd8",
    "accent-coral-ink": "#e59187",
    "syntax-foreground": "#eceae4",
    "syntax-background": "#111110",
    "syntax-token-comment": "color-mix(in srgb, #eceae4 55%, #111110)",
    "syntax-token-punctuation": "color-mix(in srgb, #eceae4 72%, #111110)",
    "syntax-token-keyword": "#bfa0c6",
    "syntax-token-string": "#9cc39e",
    "syntax-token-string-expression": "#9cc39e",
    "syntax-token-constant": "#dcbe86",
    "syntax-token-function": "#9dbcd8",
    "syntax-token-parameter": "#e59187",
    "syntax-token-link": "#88bfc2",
  },
};
