import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Snow — Crisp snow white over deep slate.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const snow: ThemeConfig = {
  name: "snow",
  colors: {
    primary: "#0b7db1",
    primaryHover: "#0279b7",
    background: "#ffffff",
    backgroundAlt: "#f4f7fb",
    text: "#0f172a",
    textMuted: "#64748b",
    border: "#dbe3ee",
    codeBackground: "#0f172a",
    codeBackgroundTop: "#0f172a",
    codeText: "#e2e8f0",
  },
  darkColors: {
    primary: "#38bdf8",
    primaryHover: "#7dd3fc",
    background: "#0b1120",
    backgroundAlt: "#131c31",
    text: "#e2e8f0",
    textMuted: "#94a3b8",
    border: "#26324a",
    codeBackground: "#0b1120",
    codeBackgroundTop: "#0b1120",
    codeText: "#e2e8f0",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0ea5e9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d97706 18%, transparent)",
    "color-code-line-warning-border": "#d97706",
    "color-code-line-error": "color-mix(in srgb, #e11d48 20%, transparent)",
    "color-code-line-error-border": "#e11d48",
    "color-code-line-add": "color-mix(in srgb, #059669 16%, transparent)",
    "color-code-line-add-border": "#059669",
    "color-code-line-remove": "color-mix(in srgb, #e11d48 14%, transparent)",
    "color-code-line-remove-border": "#e11d48",
    "color-code-line-focus": "color-mix(in srgb, #0b7db1 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #0f172a 92%, #e2e8f0)",
    "color-code-title-text": "color-mix(in srgb, #e2e8f0 88%, #0f172a)",
    "color-code-title-border": "color-mix(in srgb, #e2e8f0 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e2e8f0 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dbe3ee 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f4f7fb 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #dbe3ee 72%, #ffffff)",
    "brand-violet": "#7c3aed",
    "brand-cyan": "#06b6d4",
    "brand-lime": "#059669",
    "brand-coral": "#e11d48",
    "brand-navy": "color-mix(in srgb, #0f172a 70%, #ffffff)",
    "brand-violet-rgb": "124, 58, 237",
    "brand-cyan-rgb": "6, 182, 212",
    "brand-lime-rgb": "5, 150, 105",
    "brand-coral-rgb": "225, 29, 72",
    "accent-a": "#0b7db1",
    "accent-b": "#7c3aed",
    "accent-c": "#06b6d4",
    "accent-warm": "#d97706",
    "accent-cool": "#0ea5e9",
    "accent-a-ink": "#0b7db1",
    "accent-b-ink": "#7c3aed",
    "accent-c-ink": "#047c90",
    "accent-warm-ink": "#ae5f05",
    "accent-cool-ink": "#0b7db1",
    "accent-coral-ink": "#e11d48",
    "syntax-foreground": "#e2e8f0",
    "syntax-background": "#0f172a",
    "syntax-token-comment": "color-mix(in srgb, #e2e8f0 55%, #0f172a)",
    "syntax-token-punctuation": "color-mix(in srgb, #e2e8f0 72%, #0f172a)",
    "syntax-token-keyword": "#a78bfa",
    "syntax-token-string": "#34d399",
    "syntax-token-string-expression": "#34d399",
    "syntax-token-constant": "#fbbf24",
    "syntax-token-function": "#38bdf8",
    "syntax-token-parameter": "#fb7185",
    "syntax-token-link": "#22d3ee",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #38bdf8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fbbf24 18%, transparent)",
    "color-code-line-warning-border": "#fbbf24",
    "color-code-line-error": "color-mix(in srgb, #fb7185 20%, transparent)",
    "color-code-line-error-border": "#fb7185",
    "color-code-line-add": "color-mix(in srgb, #34d399 16%, transparent)",
    "color-code-line-add-border": "#34d399",
    "color-code-line-remove": "color-mix(in srgb, #fb7185 14%, transparent)",
    "color-code-line-remove-border": "#fb7185",
    "color-code-line-focus": "color-mix(in srgb, #38bdf8 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0b1120 92%, #e2e8f0)",
    "color-code-title-text": "color-mix(in srgb, #e2e8f0 88%, #0b1120)",
    "color-code-title-border": "color-mix(in srgb, #e2e8f0 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e2e8f0 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #26324a 92%, transparent)",
    "color-backdrop": "rgba(4, 6, 11, 0.62)",
    "surface-glass": "color-mix(in srgb, #131c31 62%, #0b1120)",
    "surface-line": "color-mix(in srgb, #26324a 72%, #0b1120)",
    "brand-violet": "#a78bfa",
    "brand-cyan": "#22d3ee",
    "brand-lime": "#34d399",
    "brand-coral": "#fb7185",
    "brand-navy": "color-mix(in srgb, #e2e8f0 70%, #0b1120)",
    "brand-violet-rgb": "167, 139, 250",
    "brand-cyan-rgb": "34, 211, 238",
    "brand-lime-rgb": "52, 211, 153",
    "brand-coral-rgb": "251, 113, 133",
    "accent-a": "#38bdf8",
    "accent-b": "#a78bfa",
    "accent-c": "#22d3ee",
    "accent-warm": "#fbbf24",
    "accent-cool": "#38bdf8",
    "accent-a-ink": "#38bdf8",
    "accent-b-ink": "#a78bfa",
    "accent-c-ink": "#22d3ee",
    "accent-warm-ink": "#fbbf24",
    "accent-cool-ink": "#38bdf8",
    "accent-coral-ink": "#fb7185",
    "syntax-foreground": "#e2e8f0",
    "syntax-background": "#0b1120",
    "syntax-token-comment": "color-mix(in srgb, #e2e8f0 55%, #0b1120)",
    "syntax-token-punctuation": "color-mix(in srgb, #e2e8f0 72%, #0b1120)",
    "syntax-token-keyword": "#a78bfa",
    "syntax-token-string": "#34d399",
    "syntax-token-string-expression": "#34d399",
    "syntax-token-constant": "#fbbf24",
    "syntax-token-function": "#38bdf8",
    "syntax-token-parameter": "#fb7185",
    "syntax-token-link": "#22d3ee",
  },
};
