/**
 * Opt-in hosted search provider for `virtual:ox-content/search`.
 *
 * Local BM25 stays the default. Hosted queries use a generic HTTP adapter and
 * a public search-only key. Write and admin keys are rejected.
 */

import type { ResolvedSearchOptions, SearchOptions } from "./types";
import {
  DEFAULT_HOSTED_ENDPOINT,
  embedSearchJson,
  failClosedSearchModule,
  hostedClientOptions,
} from "./search/hosted-module";
import { HOSTED_SEARCH_RUNTIME } from "./search/hosted-runtime";

const FORBIDDEN_KEY_NAMES = new Set(["adminkey", "writekey", "apikey"]);

export { embedSearchJson };

export type HostedSearchConfig = {
  appId: string;
  indexName: string;
  searchKey: string;
  endpoint: string;
};

function normalizeOptionKey(name: string): string {
  return name.replace(/[_-]/g, "").toLowerCase();
}

function readNonEmpty(value: unknown): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

/**
 * Returns true when the options object names a write or admin credential.
 */
export function hasForbiddenSearchCredentialFields(options: object): boolean {
  return Object.keys(options).some((key) => FORBIDDEN_KEY_NAMES.has(normalizeOptionKey(key)));
}

/**
 * Resolves hosted credentials from config or env. Missing or forbidden keys
 * fail closed and return null without echoing secrets.
 */
export function resolveHostedSearchConfig(
  options: SearchOptions,
  env: NodeJS.ProcessEnv = process.env,
): HostedSearchConfig | null {
  if (hasForbiddenSearchCredentialFields(options)) {
    return null;
  }

  const appId = readNonEmpty(options.appId) ?? readNonEmpty(env.OX_CONTENT_SEARCH_APP_ID);
  const indexName =
    readNonEmpty(options.indexName) ?? readNonEmpty(env.OX_CONTENT_SEARCH_INDEX_NAME);
  const searchKey =
    readNonEmpty(options.searchKey) ??
    readNonEmpty(options.publicKey) ??
    readNonEmpty(env.OX_CONTENT_SEARCH_KEY) ??
    readNonEmpty(env.OX_CONTENT_SEARCH_PUBLIC_KEY);
  const endpoint =
    readNonEmpty(options.endpoint) ??
    readNonEmpty(env.OX_CONTENT_SEARCH_ENDPOINT) ??
    DEFAULT_HOSTED_ENDPOINT;

  if (!appId || !indexName || !searchKey) {
    return null;
  }

  return { appId, indexName, searchKey, endpoint };
}

/**
 * Client runtime that queries the hosted HTTP adapter.
 *
 * Misconfigured hosted search emits a no-op client so the UI never calls a
 * broken endpoint.
 */
export function generateHostedSearchModule(options: ResolvedSearchOptions): string {
  if (!options.appId || !options.indexName || !options.searchKey) {
    return failClosedSearchModule(options);
  }

  const searchOptions = {
    ...hostedClientOptions(options),
    hosted: {
      appId: options.appId,
      indexName: options.indexName,
      searchKey: options.searchKey,
      endpoint: options.endpoint ?? DEFAULT_HOSTED_ENDPOINT,
    },
  };

  return `// Search module generated by ox-content
const searchOptions = ${embedSearchJson(searchOptions)};
${HOSTED_SEARCH_RUNTIME}`;
}

/**
 * Runtime fields accepted by the native local BM25 module generator.
 */
export function toLocalSearchRuntimeOptions(options: ResolvedSearchOptions) {
  return {
    enabled: options.enabled,
    limit: options.limit,
    prefix: options.prefix,
    fuzzy: options.fuzzy,
    placeholder: options.placeholder,
    hotkey: options.hotkey,
  };
}
