import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Arctic — Cold white with glacier cyan.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const arctic: ThemeConfig = {
  name: "arctic",
  colors: {
    primary: "#0f6f86",
    primaryHover: "#0a5364",
    background: "#f9fbfc",
    backgroundAlt: "#eef3f6",
    text: "#0f1a1f",
    textMuted: "#5b6c75",
    border: "#dde7ec",
    codeBackground: "#0f1a1f",
    codeBackgroundTop: "#0f1a1f",
    codeText: "#e4eef2",
  },
  darkColors: {
    primary: "#6fd0e0",
    primaryHover: "#9ae0eb",
    background: "#0b1216",
    backgroundAlt: "#121b21",
    text: "#e4eef2",
    textMuted: "#7f929c",
    border: "#1d272d",
    codeBackground: "#070d10",
    codeBackgroundTop: "#070d10",
    codeText: "#e4eef2",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2a5f96 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8a6b1c 18%, transparent)",
    "color-code-line-warning-border": "#8a6b1c",
    "color-code-line-error": "color-mix(in srgb, #b53f4a 20%, transparent)",
    "color-code-line-error-border": "#b53f4a",
    "color-code-line-add": "color-mix(in srgb, #2f7259 16%, transparent)",
    "color-code-line-add-border": "#2f7259",
    "color-code-line-remove": "color-mix(in srgb, #b53f4a 14%, transparent)",
    "color-code-line-remove-border": "#b53f4a",
    "color-code-line-focus": "color-mix(in srgb, #0f6f86 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #0f1a1f 92%, #e4eef2)",
    "color-code-title-text": "color-mix(in srgb, #e4eef2 88%, #0f1a1f)",
    "color-code-title-border": "color-mix(in srgb, #e4eef2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e4eef2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dde7ec 92%, transparent)",
    "color-backdrop": "rgba(87, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eef3f6 62%, #f9fbfc)",
    "surface-line": "color-mix(in srgb, #dde7ec 72%, #f9fbfc)",
    "brand-violet": "#6d4d95",
    "brand-cyan": "#0f6f86",
    "brand-lime": "#2f7259",
    "brand-coral": "#b53f4a",
    "brand-navy": "color-mix(in srgb, #0f1a1f 70%, #f9fbfc)",
    "brand-violet-rgb": "109, 77, 149",
    "brand-cyan-rgb": "15, 111, 134",
    "brand-lime-rgb": "47, 114, 89",
    "brand-coral-rgb": "181, 63, 74",
    "accent-a": "#0f6f86",
    "accent-b": "#6d4d95",
    "accent-c": "#0f6f86",
    "accent-warm": "#8a6b1c",
    "accent-cool": "#2a5f96",
    "accent-a-ink": "#0f6f86",
    "accent-b-ink": "#6d4d95",
    "accent-c-ink": "#0f6f86",
    "accent-warm-ink": "#8a6b1c",
    "accent-cool-ink": "#2a5f96",
    "accent-coral-ink": "#b53f4a",
    "syntax-foreground": "#e4eef2",
    "syntax-background": "#0f1a1f",
    "syntax-token-comment": "color-mix(in srgb, #e4eef2 55%, #0f1a1f)",
    "syntax-token-punctuation": "color-mix(in srgb, #e4eef2 72%, #0f1a1f)",
    "syntax-token-keyword": "#ae9ae0",
    "syntax-token-string": "#7ecaa5",
    "syntax-token-string-expression": "#7ecaa5",
    "syntax-token-constant": "#e0c184",
    "syntax-token-function": "#82b0e2",
    "syntax-token-parameter": "#ef8590",
    "syntax-token-link": "#6fd0e0",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #82b0e2 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e0c184 18%, transparent)",
    "color-code-line-warning-border": "#e0c184",
    "color-code-line-error": "color-mix(in srgb, #ef8590 20%, transparent)",
    "color-code-line-error-border": "#ef8590",
    "color-code-line-add": "color-mix(in srgb, #7ecaa5 16%, transparent)",
    "color-code-line-add-border": "#7ecaa5",
    "color-code-line-remove": "color-mix(in srgb, #ef8590 14%, transparent)",
    "color-code-line-remove-border": "#ef8590",
    "color-code-line-focus": "color-mix(in srgb, #6fd0e0 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #070d10 92%, #e4eef2)",
    "color-code-title-text": "color-mix(in srgb, #e4eef2 88%, #070d10)",
    "color-code-title-border": "color-mix(in srgb, #e4eef2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e4eef2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1d272d 92%, transparent)",
    "color-backdrop": "rgba(4, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #121b21 62%, #0b1216)",
    "surface-line": "color-mix(in srgb, #1d272d 72%, #0b1216)",
    "brand-violet": "#ae9ae0",
    "brand-cyan": "#6fd0e0",
    "brand-lime": "#7ecaa5",
    "brand-coral": "#ef8590",
    "brand-navy": "color-mix(in srgb, #e4eef2 70%, #0b1216)",
    "brand-violet-rgb": "174, 154, 224",
    "brand-cyan-rgb": "111, 208, 224",
    "brand-lime-rgb": "126, 202, 165",
    "brand-coral-rgb": "239, 133, 144",
    "accent-a": "#6fd0e0",
    "accent-b": "#ae9ae0",
    "accent-c": "#6fd0e0",
    "accent-warm": "#e0c184",
    "accent-cool": "#82b0e2",
    "accent-a-ink": "#6fd0e0",
    "accent-b-ink": "#ae9ae0",
    "accent-c-ink": "#6fd0e0",
    "accent-warm-ink": "#e0c184",
    "accent-cool-ink": "#82b0e2",
    "accent-coral-ink": "#ef8590",
    "syntax-foreground": "#e4eef2",
    "syntax-background": "#070d10",
    "syntax-token-comment": "color-mix(in srgb, #e4eef2 55%, #070d10)",
    "syntax-token-punctuation": "color-mix(in srgb, #e4eef2 72%, #070d10)",
    "syntax-token-keyword": "#ae9ae0",
    "syntax-token-string": "#7ecaa5",
    "syntax-token-string-expression": "#7ecaa5",
    "syntax-token-constant": "#e0c184",
    "syntax-token-function": "#82b0e2",
    "syntax-token-parameter": "#ef8590",
    "syntax-token-link": "#6fd0e0",
  },
};

export default arctic;
