import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light Default and Dark Default.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubDefault: ThemeConfig = {
  name: "github-default",
  colors: {
    primary: "#0969da",
    primaryHover: "#0969da",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#6e7781",
    border: "#d0d7de",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#2f81f7",
    primaryHover: "#2f81f7",
    background: "#0d1117",
    backgroundAlt: "#010409",
    text: "#e6edf3",
    textMuted: "#8b949e",
    border: "#30363d",
    codeBackground: "#0d1117",
    codeBackgroundTop: "#0d1117",
    codeText: "#e6edf3",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #4d2d00 18%, transparent)",
    "color-code-line-warning-border": "#4d2d00",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #116329 16%, transparent)",
    "color-code-line-add-border": "#116329",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d7de 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d0d7de 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#116329",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "17, 99, 41",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#4d2d00",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#4d2d00",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6e7781",
    "syntax-token-punctuation": "#6e7781",
    "syntax-token-keyword": "#cf222e",
    "syntax-token-string": "#0a3069",
    "syntax-token-string-expression": "#0a3069",
    "syntax-token-constant": "#0550ae",
    "syntax-token-function": "#8250df",
    "syntax-token-parameter": "#1f2328",
    "syntax-token-link": "#0a3069",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #58a6ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d29922 18%, transparent)",
    "color-code-line-warning-border": "#d29922",
    "color-code-line-error": "color-mix(in srgb, #ff7b72 20%, transparent)",
    "color-code-line-error-border": "#ff7b72",
    "color-code-line-add": "color-mix(in srgb, #3fb950 16%, transparent)",
    "color-code-line-add-border": "#3fb950",
    "color-code-line-remove": "color-mix(in srgb, #ff7b72 14%, transparent)",
    "color-code-line-remove-border": "#ff7b72",
    "color-code-line-focus": "color-mix(in srgb, #2f81f7 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0d1117 92%, #e6edf3)",
    "color-code-title-text": "color-mix(in srgb, #e6edf3 88%, #0d1117)",
    "color-code-title-border": "color-mix(in srgb, #e6edf3 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6edf3 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #30363d 92%, transparent)",
    "color-backdrop": "rgba(5, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #010409 62%, #0d1117)",
    "surface-line": "color-mix(in srgb, #30363d 72%, #0d1117)",
    "brand-violet": "#bc8cff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#3fb950",
    "brand-coral": "#ff7b72",
    "brand-navy": "color-mix(in srgb, #e6edf3 70%, #0d1117)",
    "brand-violet-rgb": "188, 140, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "63, 185, 80",
    "brand-coral-rgb": "255, 123, 114",
    "accent-a": "#2f81f7",
    "accent-b": "#bc8cff",
    "accent-c": "#39c5cf",
    "accent-warm": "#d29922",
    "accent-cool": "#58a6ff",
    "accent-a-ink": "#2f81f7",
    "accent-b-ink": "#bc8cff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#d29922",
    "accent-cool-ink": "#58a6ff",
    "accent-coral-ink": "#ff7b72",
    "syntax-foreground": "#e6edf3",
    "syntax-background": "#0d1117",
    "syntax-token-comment": "#8b949e",
    "syntax-token-punctuation": "#8b949e",
    "syntax-token-keyword": "#ff7b72",
    "syntax-token-string": "#a5d6ff",
    "syntax-token-string-expression": "#a5d6ff",
    "syntax-token-constant": "#79c0ff",
    "syntax-token-function": "#d2a8ff",
    "syntax-token-parameter": "#e6edf3",
    "syntax-token-link": "#a5d6ff",
  },
};
