import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light and Dark from @shikijs/themes.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubClassic: ThemeConfig = {
  name: "github-classic",
  colors: {
    primary: "#0366d6",
    primaryHover: "#005cc5",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#24292e",
    textMuted: "#6a737d",
    border: "#e1e4e8",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#24292e",
  },
  darkColors: {
    primary: "#79b8ff",
    primaryHover: "#c8e1ff",
    background: "#24292e",
    backgroundAlt: "#1f2428",
    text: "#e1e4e8",
    textMuted: "#8e959c",
    border: "#1b1f23",
    codeBackground: "#24292e",
    codeBackgroundTop: "#24292e",
    codeText: "#e1e4e8",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0366d6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dbab09 18%, transparent)",
    "color-code-line-warning-border": "#dbab09",
    "color-code-line-error": "color-mix(in srgb, #d73a49 20%, transparent)",
    "color-code-line-error-border": "#d73a49",
    "color-code-line-add": "color-mix(in srgb, #28a745 16%, transparent)",
    "color-code-line-add-border": "#28a745",
    "color-code-line-remove": "color-mix(in srgb, #d73a49 14%, transparent)",
    "color-code-line-remove-border": "#d73a49",
    "color-code-line-focus": "color-mix(in srgb, #0366d6 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #24292e)",
    "color-code-title-text": "color-mix(in srgb, #24292e 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #24292e 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #24292e 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e1e4e8 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #e1e4e8 72%, #ffffff)",
    "brand-violet": "#5a32a3",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#28a745",
    "brand-coral": "#d73a49",
    "brand-navy": "color-mix(in srgb, #24292e 70%, #ffffff)",
    "brand-violet-rgb": "90, 50, 163",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "40, 167, 69",
    "brand-coral-rgb": "215, 58, 73",
    "accent-a": "#0366d6",
    "accent-b": "#5a32a3",
    "accent-c": "#1b7c83",
    "accent-warm": "#dbab09",
    "accent-cool": "#0366d6",
    "accent-a-ink": "#0366d6",
    "accent-b-ink": "#5a32a3",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#8c6d06",
    "accent-cool-ink": "#0366d6",
    "accent-coral-ink": "#d73a49",
    "syntax-foreground": "#24292e",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6a737d",
    "syntax-token-punctuation": "#6a737d",
    "syntax-token-keyword": "#d73a49",
    "syntax-token-string": "#032f62",
    "syntax-token-string-expression": "#032f62",
    "syntax-token-constant": "#005cc5",
    "syntax-token-function": "#0366d6",
    "syntax-token-parameter": "#24292e",
    "syntax-token-link": "#032f62",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2188ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffea7f 18%, transparent)",
    "color-code-line-warning-border": "#ffea7f",
    "color-code-line-error": "color-mix(in srgb, #ea4a5a 20%, transparent)",
    "color-code-line-error-border": "#ea4a5a",
    "color-code-line-add": "color-mix(in srgb, #34d058 16%, transparent)",
    "color-code-line-add-border": "#34d058",
    "color-code-line-remove": "color-mix(in srgb, #ea4a5a 14%, transparent)",
    "color-code-line-remove-border": "#ea4a5a",
    "color-code-line-focus": "color-mix(in srgb, #79b8ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #24292e 92%, #e1e4e8)",
    "color-code-title-text": "color-mix(in srgb, #e1e4e8 88%, #24292e)",
    "color-code-title-border": "color-mix(in srgb, #e1e4e8 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e1e4e8 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1b1f23 92%, transparent)",
    "color-backdrop": "rgba(13, 14, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #1f2428 62%, #24292e)",
    "surface-line": "color-mix(in srgb, #1b1f23 72%, #24292e)",
    "brand-violet": "#b392f0",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#34d058",
    "brand-coral": "#ea4a5a",
    "brand-navy": "color-mix(in srgb, #e1e4e8 70%, #24292e)",
    "brand-violet-rgb": "179, 146, 240",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "52, 208, 88",
    "brand-coral-rgb": "234, 74, 90",
    "accent-a": "#79b8ff",
    "accent-b": "#b392f0",
    "accent-c": "#39c5cf",
    "accent-warm": "#ffea7f",
    "accent-cool": "#2188ff",
    "accent-a-ink": "#79b8ff",
    "accent-b-ink": "#b392f0",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#ffea7f",
    "accent-cool-ink": "#3392ff",
    "accent-coral-ink": "#ed606e",
    "syntax-foreground": "#e1e4e8",
    "syntax-background": "#24292e",
    "syntax-token-comment": "#6a737d",
    "syntax-token-punctuation": "#6a737d",
    "syntax-token-keyword": "#f97583",
    "syntax-token-string": "#9ecbff",
    "syntax-token-string-expression": "#9ecbff",
    "syntax-token-constant": "#79b8ff",
    "syntax-token-function": "#2188ff",
    "syntax-token-parameter": "#e1e4e8",
    "syntax-token-link": "#dbedff",
  },
};
