import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light Default and Dark Dimmed.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubDimmed: ThemeConfig = {
  name: "github-dimmed",
  colors: {
    primary: "#0969da",
    primaryHover: "#0969da",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#6e7781",
    border: "#d0d7de",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#539bf5",
    primaryHover: "#539bf5",
    background: "#22272e",
    backgroundAlt: "#1c2128",
    text: "#adbac7",
    textMuted: "#86929d",
    border: "#444c56",
    codeBackground: "#22272e",
    codeBackgroundTop: "#22272e",
    codeText: "#adbac7",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #4d2d00 18%, transparent)",
    "color-code-line-warning-border": "#4d2d00",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #116329 16%, transparent)",
    "color-code-line-add-border": "#116329",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d7de 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d0d7de 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#116329",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "17, 99, 41",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#4d2d00",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#4d2d00",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6e7781",
    "syntax-token-punctuation": "#6e7781",
    "syntax-token-keyword": "#cf222e",
    "syntax-token-string": "#0a3069",
    "syntax-token-string-expression": "#0a3069",
    "syntax-token-constant": "#0550ae",
    "syntax-token-function": "#8250df",
    "syntax-token-parameter": "#1f2328",
    "syntax-token-link": "#0a3069",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #539bf5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #c69026 18%, transparent)",
    "color-code-line-warning-border": "#c69026",
    "color-code-line-error": "color-mix(in srgb, #f47067 20%, transparent)",
    "color-code-line-error-border": "#f47067",
    "color-code-line-add": "color-mix(in srgb, #57ab5a 16%, transparent)",
    "color-code-line-add-border": "#57ab5a",
    "color-code-line-remove": "color-mix(in srgb, #f47067 14%, transparent)",
    "color-code-line-remove-border": "#f47067",
    "color-code-line-focus": "color-mix(in srgb, #539bf5 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #22272e 92%, #adbac7)",
    "color-code-title-text": "color-mix(in srgb, #adbac7 88%, #22272e)",
    "color-code-title-border": "color-mix(in srgb, #adbac7 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #adbac7 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #444c56 92%, transparent)",
    "color-backdrop": "rgba(12, 14, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #1c2128 62%, #22272e)",
    "surface-line": "color-mix(in srgb, #444c56 72%, #22272e)",
    "brand-violet": "#b083f0",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#57ab5a",
    "brand-coral": "#f47067",
    "brand-navy": "color-mix(in srgb, #adbac7 70%, #22272e)",
    "brand-violet-rgb": "176, 131, 240",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "87, 171, 90",
    "brand-coral-rgb": "244, 112, 103",
    "accent-a": "#539bf5",
    "accent-b": "#b083f0",
    "accent-c": "#39c5cf",
    "accent-warm": "#c69026",
    "accent-cool": "#539bf5",
    "accent-a-ink": "#539bf5",
    "accent-b-ink": "#b083f0",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#c69026",
    "accent-cool-ink": "#539bf5",
    "accent-coral-ink": "#f47067",
    "syntax-foreground": "#adbac7",
    "syntax-background": "#22272e",
    "syntax-token-comment": "#768390",
    "syntax-token-punctuation": "#768390",
    "syntax-token-keyword": "#f47067",
    "syntax-token-string": "#96d0ff",
    "syntax-token-string-expression": "#96d0ff",
    "syntax-token-constant": "#6cb6ff",
    "syntax-token-function": "#dcbdfb",
    "syntax-token-parameter": "#adbac7",
    "syntax-token-link": "#96d0ff",
  },
};
