import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light High Contrast and Dark High Contrast.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubHighContrast: ThemeConfig = {
  name: "github-high-contrast",
  colors: {
    primary: "#0349b4",
    primaryHover: "#0349b4",
    background: "#ffffff",
    backgroundAlt: "#ffffff",
    text: "#0e1116",
    textMuted: "#66707b",
    border: "#20252c",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#0e1116",
  },
  darkColors: {
    primary: "#71b7ff",
    primaryHover: "#71b7ff",
    background: "#0a0c10",
    backgroundAlt: "#010409",
    text: "#f0f3f6",
    textMuted: "#bdc4cc",
    border: "#7a828e",
    codeBackground: "#0a0c10",
    codeBackgroundTop: "#0a0c10",
    codeText: "#f0f3f6",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0349b4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #3f2200 18%, transparent)",
    "color-code-line-warning-border": "#3f2200",
    "color-code-line-error": "color-mix(in srgb, #a0111f 20%, transparent)",
    "color-code-line-error-border": "#a0111f",
    "color-code-line-add": "color-mix(in srgb, #024c1a 16%, transparent)",
    "color-code-line-add-border": "#024c1a",
    "color-code-line-remove": "color-mix(in srgb, #a0111f 14%, transparent)",
    "color-code-line-remove-border": "#a0111f",
    "color-code-line-focus": "color-mix(in srgb, #0349b4 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #0e1116)",
    "color-code-title-text": "color-mix(in srgb, #0e1116 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #0e1116 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #0e1116 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #20252c 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #ffffff 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #20252c 72%, #ffffff)",
    "brand-violet": "#622cbc",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#024c1a",
    "brand-coral": "#a0111f",
    "brand-navy": "color-mix(in srgb, #0e1116 70%, #ffffff)",
    "brand-violet-rgb": "98, 44, 188",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "2, 76, 26",
    "brand-coral-rgb": "160, 17, 31",
    "accent-a": "#0349b4",
    "accent-b": "#622cbc",
    "accent-c": "#1b7c83",
    "accent-warm": "#3f2200",
    "accent-cool": "#0349b4",
    "accent-a-ink": "#0349b4",
    "accent-b-ink": "#622cbc",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#3f2200",
    "accent-cool-ink": "#0349b4",
    "accent-coral-ink": "#a0111f",
    "syntax-foreground": "#0e1116",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#66707b",
    "syntax-token-punctuation": "#66707b",
    "syntax-token-keyword": "#a0111f",
    "syntax-token-string": "#032563",
    "syntax-token-string-expression": "#032563",
    "syntax-token-constant": "#023b95",
    "syntax-token-function": "#622cbc",
    "syntax-token-parameter": "#0e1116",
    "syntax-token-link": "#032563",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #71b7ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f0b72f 18%, transparent)",
    "color-code-line-warning-border": "#f0b72f",
    "color-code-line-error": "color-mix(in srgb, #ff9492 20%, transparent)",
    "color-code-line-error-border": "#ff9492",
    "color-code-line-add": "color-mix(in srgb, #26cd4d 16%, transparent)",
    "color-code-line-add-border": "#26cd4d",
    "color-code-line-remove": "color-mix(in srgb, #ff9492 14%, transparent)",
    "color-code-line-remove-border": "#ff9492",
    "color-code-line-focus": "color-mix(in srgb, #71b7ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0a0c10 92%, #f0f3f6)",
    "color-code-title-text": "color-mix(in srgb, #f0f3f6 88%, #0a0c10)",
    "color-code-title-border": "color-mix(in srgb, #f0f3f6 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0f3f6 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #7a828e 92%, transparent)",
    "color-backdrop": "rgba(4, 4, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #010409 62%, #0a0c10)",
    "surface-line": "color-mix(in srgb, #7a828e 72%, #0a0c10)",
    "brand-violet": "#cb9eff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#26cd4d",
    "brand-coral": "#ff9492",
    "brand-navy": "color-mix(in srgb, #f0f3f6 70%, #0a0c10)",
    "brand-violet-rgb": "203, 158, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "38, 205, 77",
    "brand-coral-rgb": "255, 148, 146",
    "accent-a": "#71b7ff",
    "accent-b": "#cb9eff",
    "accent-c": "#39c5cf",
    "accent-warm": "#f0b72f",
    "accent-cool": "#71b7ff",
    "accent-a-ink": "#71b7ff",
    "accent-b-ink": "#cb9eff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#f0b72f",
    "accent-cool-ink": "#71b7ff",
    "accent-coral-ink": "#ff9492",
    "syntax-foreground": "#f0f3f6",
    "syntax-background": "#0a0c10",
    "syntax-token-comment": "#bdc4cc",
    "syntax-token-punctuation": "#bdc4cc",
    "syntax-token-keyword": "#ff9492",
    "syntax-token-string": "#addcff",
    "syntax-token-string-expression": "#addcff",
    "syntax-token-constant": "#91cbff",
    "syntax-token-function": "#dbb7ff",
    "syntax-token-parameter": "#f0f3f6",
    "syntax-token-link": "#addcff",
  },
};
