import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light and GitHub Dark.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const github: ThemeConfig = {
  name: "github",
  colors: {
    primary: "#0969da",
    primaryHover: "#0550ae",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#59636e",
    border: "#d1d9e0",
    codeBackground: "#f6f8fa",
    codeBackgroundTop: "#f6f8fa",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#4493f8",
    primaryHover: "#6cb6ff",
    background: "#0d1117",
    backgroundAlt: "#151b23",
    text: "#f0f6fc",
    textMuted: "#9198a1",
    border: "#3d444d",
    codeBackground: "#151b23",
    codeBackgroundTop: "#151b23",
    codeText: "#f0f6fc",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a6700 18%, transparent)",
    "color-code-line-warning-border": "#9a6700",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #1a7f37 16%, transparent)",
    "color-code-line-add-border": "#1a7f37",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f6f8fa 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #f6f8fa)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d1d9e0 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d1d9e0 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#1a7f37",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "26, 127, 55",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#9a6700",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#9a6700",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#f6f8fa",
    "syntax-token-comment": "color-mix(in srgb, #1f2328 55%, #f6f8fa)",
    "syntax-token-punctuation": "color-mix(in srgb, #1f2328 72%, #f6f8fa)",
    "syntax-token-keyword": "#8250df",
    "syntax-token-string": "#1a7f37",
    "syntax-token-string-expression": "#1a7f37",
    "syntax-token-constant": "#9a6700",
    "syntax-token-function": "#0969da",
    "syntax-token-parameter": "#cf222e",
    "syntax-token-link": "#1b7c83",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4493f8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d29922 18%, transparent)",
    "color-code-line-warning-border": "#d29922",
    "color-code-line-error": "color-mix(in srgb, #ff7b72 20%, transparent)",
    "color-code-line-error-border": "#ff7b72",
    "color-code-line-add": "color-mix(in srgb, #3fb950 16%, transparent)",
    "color-code-line-add-border": "#3fb950",
    "color-code-line-remove": "color-mix(in srgb, #ff7b72 14%, transparent)",
    "color-code-line-remove-border": "#ff7b72",
    "color-code-line-focus": "color-mix(in srgb, #4493f8 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #151b23 92%, #f0f6fc)",
    "color-code-title-text": "color-mix(in srgb, #f0f6fc 88%, #151b23)",
    "color-code-title-border": "color-mix(in srgb, #f0f6fc 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0f6fc 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3d444d 92%, transparent)",
    "color-backdrop": "rgba(5, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #151b23 62%, #0d1117)",
    "surface-line": "color-mix(in srgb, #3d444d 72%, #0d1117)",
    "brand-violet": "#bc8cff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#3fb950",
    "brand-coral": "#ff7b72",
    "brand-navy": "color-mix(in srgb, #f0f6fc 70%, #0d1117)",
    "brand-violet-rgb": "188, 140, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "63, 185, 80",
    "brand-coral-rgb": "255, 123, 114",
    "accent-a": "#4493f8",
    "accent-b": "#bc8cff",
    "accent-c": "#39c5cf",
    "accent-warm": "#d29922",
    "accent-cool": "#4493f8",
    "accent-a-ink": "#4493f8",
    "accent-b-ink": "#bc8cff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#d29922",
    "accent-cool-ink": "#4493f8",
    "accent-coral-ink": "#ff7b72",
    "syntax-foreground": "#f0f6fc",
    "syntax-background": "#151b23",
    "syntax-token-comment": "color-mix(in srgb, #f0f6fc 55%, #151b23)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0f6fc 72%, #151b23)",
    "syntax-token-keyword": "#bc8cff",
    "syntax-token-string": "#3fb950",
    "syntax-token-string-expression": "#3fb950",
    "syntax-token-constant": "#d29922",
    "syntax-token-function": "#4493f8",
    "syntax-token-parameter": "#ff7b72",
    "syntax-token-link": "#39c5cf",
  },
};

/**
 * GitHub — GitHub Light and Dark from @shikijs/themes.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubClassic: ThemeConfig = {
  name: "github-classic",
  colors: {
    primary: "#0366d6",
    primaryHover: "#005cc5",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#24292e",
    textMuted: "#6a737d",
    border: "#e1e4e8",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#24292e",
  },
  darkColors: {
    primary: "#79b8ff",
    primaryHover: "#c8e1ff",
    background: "#24292e",
    backgroundAlt: "#1f2428",
    text: "#e1e4e8",
    textMuted: "#8e959c",
    border: "#1b1f23",
    codeBackground: "#24292e",
    codeBackgroundTop: "#24292e",
    codeText: "#e1e4e8",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0366d6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dbab09 18%, transparent)",
    "color-code-line-warning-border": "#dbab09",
    "color-code-line-error": "color-mix(in srgb, #d73a49 20%, transparent)",
    "color-code-line-error-border": "#d73a49",
    "color-code-line-add": "color-mix(in srgb, #28a745 16%, transparent)",
    "color-code-line-add-border": "#28a745",
    "color-code-line-remove": "color-mix(in srgb, #d73a49 14%, transparent)",
    "color-code-line-remove-border": "#d73a49",
    "color-code-line-focus": "color-mix(in srgb, #0366d6 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #24292e)",
    "color-code-title-text": "color-mix(in srgb, #24292e 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #24292e 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #24292e 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e1e4e8 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #e1e4e8 72%, #ffffff)",
    "brand-violet": "#5a32a3",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#28a745",
    "brand-coral": "#d73a49",
    "brand-navy": "color-mix(in srgb, #24292e 70%, #ffffff)",
    "brand-violet-rgb": "90, 50, 163",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "40, 167, 69",
    "brand-coral-rgb": "215, 58, 73",
    "accent-a": "#0366d6",
    "accent-b": "#5a32a3",
    "accent-c": "#1b7c83",
    "accent-warm": "#dbab09",
    "accent-cool": "#0366d6",
    "accent-a-ink": "#0366d6",
    "accent-b-ink": "#5a32a3",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#8c6d06",
    "accent-cool-ink": "#0366d6",
    "accent-coral-ink": "#d73a49",
    "syntax-foreground": "#24292e",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6a737d",
    "syntax-token-punctuation": "#6a737d",
    "syntax-token-keyword": "#d73a49",
    "syntax-token-string": "#032f62",
    "syntax-token-string-expression": "#032f62",
    "syntax-token-constant": "#005cc5",
    "syntax-token-function": "#0366d6",
    "syntax-token-parameter": "#24292e",
    "syntax-token-link": "#032f62",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2188ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffea7f 18%, transparent)",
    "color-code-line-warning-border": "#ffea7f",
    "color-code-line-error": "color-mix(in srgb, #ea4a5a 20%, transparent)",
    "color-code-line-error-border": "#ea4a5a",
    "color-code-line-add": "color-mix(in srgb, #34d058 16%, transparent)",
    "color-code-line-add-border": "#34d058",
    "color-code-line-remove": "color-mix(in srgb, #ea4a5a 14%, transparent)",
    "color-code-line-remove-border": "#ea4a5a",
    "color-code-line-focus": "color-mix(in srgb, #79b8ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #24292e 92%, #e1e4e8)",
    "color-code-title-text": "color-mix(in srgb, #e1e4e8 88%, #24292e)",
    "color-code-title-border": "color-mix(in srgb, #e1e4e8 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e1e4e8 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #1b1f23 92%, transparent)",
    "color-backdrop": "rgba(13, 14, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #1f2428 62%, #24292e)",
    "surface-line": "color-mix(in srgb, #1b1f23 72%, #24292e)",
    "brand-violet": "#b392f0",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#34d058",
    "brand-coral": "#ea4a5a",
    "brand-navy": "color-mix(in srgb, #e1e4e8 70%, #24292e)",
    "brand-violet-rgb": "179, 146, 240",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "52, 208, 88",
    "brand-coral-rgb": "234, 74, 90",
    "accent-a": "#79b8ff",
    "accent-b": "#b392f0",
    "accent-c": "#39c5cf",
    "accent-warm": "#ffea7f",
    "accent-cool": "#2188ff",
    "accent-a-ink": "#79b8ff",
    "accent-b-ink": "#b392f0",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#ffea7f",
    "accent-cool-ink": "#3392ff",
    "accent-coral-ink": "#ed606e",
    "syntax-foreground": "#e1e4e8",
    "syntax-background": "#24292e",
    "syntax-token-comment": "#6a737d",
    "syntax-token-punctuation": "#6a737d",
    "syntax-token-keyword": "#f97583",
    "syntax-token-string": "#9ecbff",
    "syntax-token-string-expression": "#9ecbff",
    "syntax-token-constant": "#79b8ff",
    "syntax-token-function": "#2188ff",
    "syntax-token-parameter": "#e1e4e8",
    "syntax-token-link": "#dbedff",
  },
};

/**
 * GitHub — GitHub Light Default and Dark Default.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubDefault: ThemeConfig = {
  name: "github-default",
  colors: {
    primary: "#0969da",
    primaryHover: "#0969da",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#6e7781",
    border: "#d0d7de",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#2f81f7",
    primaryHover: "#2f81f7",
    background: "#0d1117",
    backgroundAlt: "#010409",
    text: "#e6edf3",
    textMuted: "#8b949e",
    border: "#30363d",
    codeBackground: "#0d1117",
    codeBackgroundTop: "#0d1117",
    codeText: "#e6edf3",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #4d2d00 18%, transparent)",
    "color-code-line-warning-border": "#4d2d00",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #116329 16%, transparent)",
    "color-code-line-add-border": "#116329",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d7de 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d0d7de 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#116329",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "17, 99, 41",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#4d2d00",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#4d2d00",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6e7781",
    "syntax-token-punctuation": "#6e7781",
    "syntax-token-keyword": "#cf222e",
    "syntax-token-string": "#0a3069",
    "syntax-token-string-expression": "#0a3069",
    "syntax-token-constant": "#0550ae",
    "syntax-token-function": "#8250df",
    "syntax-token-parameter": "#1f2328",
    "syntax-token-link": "#0a3069",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #58a6ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d29922 18%, transparent)",
    "color-code-line-warning-border": "#d29922",
    "color-code-line-error": "color-mix(in srgb, #ff7b72 20%, transparent)",
    "color-code-line-error-border": "#ff7b72",
    "color-code-line-add": "color-mix(in srgb, #3fb950 16%, transparent)",
    "color-code-line-add-border": "#3fb950",
    "color-code-line-remove": "color-mix(in srgb, #ff7b72 14%, transparent)",
    "color-code-line-remove-border": "#ff7b72",
    "color-code-line-focus": "color-mix(in srgb, #2f81f7 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0d1117 92%, #e6edf3)",
    "color-code-title-text": "color-mix(in srgb, #e6edf3 88%, #0d1117)",
    "color-code-title-border": "color-mix(in srgb, #e6edf3 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6edf3 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #30363d 92%, transparent)",
    "color-backdrop": "rgba(5, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #010409 62%, #0d1117)",
    "surface-line": "color-mix(in srgb, #30363d 72%, #0d1117)",
    "brand-violet": "#bc8cff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#3fb950",
    "brand-coral": "#ff7b72",
    "brand-navy": "color-mix(in srgb, #e6edf3 70%, #0d1117)",
    "brand-violet-rgb": "188, 140, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "63, 185, 80",
    "brand-coral-rgb": "255, 123, 114",
    "accent-a": "#2f81f7",
    "accent-b": "#bc8cff",
    "accent-c": "#39c5cf",
    "accent-warm": "#d29922",
    "accent-cool": "#58a6ff",
    "accent-a-ink": "#2f81f7",
    "accent-b-ink": "#bc8cff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#d29922",
    "accent-cool-ink": "#58a6ff",
    "accent-coral-ink": "#ff7b72",
    "syntax-foreground": "#e6edf3",
    "syntax-background": "#0d1117",
    "syntax-token-comment": "#8b949e",
    "syntax-token-punctuation": "#8b949e",
    "syntax-token-keyword": "#ff7b72",
    "syntax-token-string": "#a5d6ff",
    "syntax-token-string-expression": "#a5d6ff",
    "syntax-token-constant": "#79c0ff",
    "syntax-token-function": "#d2a8ff",
    "syntax-token-parameter": "#e6edf3",
    "syntax-token-link": "#a5d6ff",
  },
};

/**
 * GitHub — GitHub Light Default and Dark Dimmed.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubDimmed: ThemeConfig = {
  name: "github-dimmed",
  colors: {
    primary: "#0969da",
    primaryHover: "#0969da",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#6e7781",
    border: "#d0d7de",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#539bf5",
    primaryHover: "#539bf5",
    background: "#22272e",
    backgroundAlt: "#1c2128",
    text: "#adbac7",
    textMuted: "#86929d",
    border: "#444c56",
    codeBackground: "#22272e",
    codeBackgroundTop: "#22272e",
    codeText: "#adbac7",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #4d2d00 18%, transparent)",
    "color-code-line-warning-border": "#4d2d00",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #116329 16%, transparent)",
    "color-code-line-add-border": "#116329",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d7de 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d0d7de 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#116329",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "17, 99, 41",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#4d2d00",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#4d2d00",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#6e7781",
    "syntax-token-punctuation": "#6e7781",
    "syntax-token-keyword": "#cf222e",
    "syntax-token-string": "#0a3069",
    "syntax-token-string-expression": "#0a3069",
    "syntax-token-constant": "#0550ae",
    "syntax-token-function": "#8250df",
    "syntax-token-parameter": "#1f2328",
    "syntax-token-link": "#0a3069",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #539bf5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #c69026 18%, transparent)",
    "color-code-line-warning-border": "#c69026",
    "color-code-line-error": "color-mix(in srgb, #f47067 20%, transparent)",
    "color-code-line-error-border": "#f47067",
    "color-code-line-add": "color-mix(in srgb, #57ab5a 16%, transparent)",
    "color-code-line-add-border": "#57ab5a",
    "color-code-line-remove": "color-mix(in srgb, #f47067 14%, transparent)",
    "color-code-line-remove-border": "#f47067",
    "color-code-line-focus": "color-mix(in srgb, #539bf5 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #22272e 92%, #adbac7)",
    "color-code-title-text": "color-mix(in srgb, #adbac7 88%, #22272e)",
    "color-code-title-border": "color-mix(in srgb, #adbac7 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #adbac7 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #444c56 92%, transparent)",
    "color-backdrop": "rgba(12, 14, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #1c2128 62%, #22272e)",
    "surface-line": "color-mix(in srgb, #444c56 72%, #22272e)",
    "brand-violet": "#b083f0",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#57ab5a",
    "brand-coral": "#f47067",
    "brand-navy": "color-mix(in srgb, #adbac7 70%, #22272e)",
    "brand-violet-rgb": "176, 131, 240",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "87, 171, 90",
    "brand-coral-rgb": "244, 112, 103",
    "accent-a": "#539bf5",
    "accent-b": "#b083f0",
    "accent-c": "#39c5cf",
    "accent-warm": "#c69026",
    "accent-cool": "#539bf5",
    "accent-a-ink": "#539bf5",
    "accent-b-ink": "#b083f0",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#c69026",
    "accent-cool-ink": "#539bf5",
    "accent-coral-ink": "#f47067",
    "syntax-foreground": "#adbac7",
    "syntax-background": "#22272e",
    "syntax-token-comment": "#768390",
    "syntax-token-punctuation": "#768390",
    "syntax-token-keyword": "#f47067",
    "syntax-token-string": "#96d0ff",
    "syntax-token-string-expression": "#96d0ff",
    "syntax-token-constant": "#6cb6ff",
    "syntax-token-function": "#dcbdfb",
    "syntax-token-parameter": "#adbac7",
    "syntax-token-link": "#96d0ff",
  },
};

/**
 * GitHub — GitHub Light High Contrast and Dark High Contrast.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const githubHighContrast: ThemeConfig = {
  name: "github-high-contrast",
  colors: {
    primary: "#0349b4",
    primaryHover: "#0349b4",
    background: "#ffffff",
    backgroundAlt: "#ffffff",
    text: "#0e1116",
    textMuted: "#66707b",
    border: "#20252c",
    codeBackground: "#ffffff",
    codeBackgroundTop: "#ffffff",
    codeText: "#0e1116",
  },
  darkColors: {
    primary: "#71b7ff",
    primaryHover: "#71b7ff",
    background: "#0a0c10",
    backgroundAlt: "#010409",
    text: "#f0f3f6",
    textMuted: "#bdc4cc",
    border: "#7a828e",
    codeBackground: "#0a0c10",
    codeBackgroundTop: "#0a0c10",
    codeText: "#f0f3f6",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0349b4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #3f2200 18%, transparent)",
    "color-code-line-warning-border": "#3f2200",
    "color-code-line-error": "color-mix(in srgb, #a0111f 20%, transparent)",
    "color-code-line-error-border": "#a0111f",
    "color-code-line-add": "color-mix(in srgb, #024c1a 16%, transparent)",
    "color-code-line-add-border": "#024c1a",
    "color-code-line-remove": "color-mix(in srgb, #a0111f 14%, transparent)",
    "color-code-line-remove-border": "#a0111f",
    "color-code-line-focus": "color-mix(in srgb, #0349b4 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #ffffff 92%, #0e1116)",
    "color-code-title-text": "color-mix(in srgb, #0e1116 88%, #ffffff)",
    "color-code-title-border": "color-mix(in srgb, #0e1116 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #0e1116 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #20252c 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #ffffff 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #20252c 72%, #ffffff)",
    "brand-violet": "#622cbc",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#024c1a",
    "brand-coral": "#a0111f",
    "brand-navy": "color-mix(in srgb, #0e1116 70%, #ffffff)",
    "brand-violet-rgb": "98, 44, 188",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "2, 76, 26",
    "brand-coral-rgb": "160, 17, 31",
    "accent-a": "#0349b4",
    "accent-b": "#622cbc",
    "accent-c": "#1b7c83",
    "accent-warm": "#3f2200",
    "accent-cool": "#0349b4",
    "accent-a-ink": "#0349b4",
    "accent-b-ink": "#622cbc",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#3f2200",
    "accent-cool-ink": "#0349b4",
    "accent-coral-ink": "#a0111f",
    "syntax-foreground": "#0e1116",
    "syntax-background": "#ffffff",
    "syntax-token-comment": "#66707b",
    "syntax-token-punctuation": "#66707b",
    "syntax-token-keyword": "#a0111f",
    "syntax-token-string": "#032563",
    "syntax-token-string-expression": "#032563",
    "syntax-token-constant": "#023b95",
    "syntax-token-function": "#622cbc",
    "syntax-token-parameter": "#0e1116",
    "syntax-token-link": "#032563",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #71b7ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #f0b72f 18%, transparent)",
    "color-code-line-warning-border": "#f0b72f",
    "color-code-line-error": "color-mix(in srgb, #ff9492 20%, transparent)",
    "color-code-line-error-border": "#ff9492",
    "color-code-line-add": "color-mix(in srgb, #26cd4d 16%, transparent)",
    "color-code-line-add-border": "#26cd4d",
    "color-code-line-remove": "color-mix(in srgb, #ff9492 14%, transparent)",
    "color-code-line-remove-border": "#ff9492",
    "color-code-line-focus": "color-mix(in srgb, #71b7ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0a0c10 92%, #f0f3f6)",
    "color-code-title-text": "color-mix(in srgb, #f0f3f6 88%, #0a0c10)",
    "color-code-title-border": "color-mix(in srgb, #f0f3f6 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0f3f6 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #7a828e 92%, transparent)",
    "color-backdrop": "rgba(4, 4, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #010409 62%, #0a0c10)",
    "surface-line": "color-mix(in srgb, #7a828e 72%, #0a0c10)",
    "brand-violet": "#cb9eff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#26cd4d",
    "brand-coral": "#ff9492",
    "brand-navy": "color-mix(in srgb, #f0f3f6 70%, #0a0c10)",
    "brand-violet-rgb": "203, 158, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "38, 205, 77",
    "brand-coral-rgb": "255, 148, 146",
    "accent-a": "#71b7ff",
    "accent-b": "#cb9eff",
    "accent-c": "#39c5cf",
    "accent-warm": "#f0b72f",
    "accent-cool": "#71b7ff",
    "accent-a-ink": "#71b7ff",
    "accent-b-ink": "#cb9eff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#f0b72f",
    "accent-cool-ink": "#71b7ff",
    "accent-coral-ink": "#ff9492",
    "syntax-foreground": "#f0f3f6",
    "syntax-background": "#0a0c10",
    "syntax-token-comment": "#bdc4cc",
    "syntax-token-punctuation": "#bdc4cc",
    "syntax-token-keyword": "#ff9492",
    "syntax-token-string": "#addcff",
    "syntax-token-string-expression": "#addcff",
    "syntax-token-constant": "#91cbff",
    "syntax-token-function": "#dbb7ff",
    "syntax-token-parameter": "#f0f3f6",
    "syntax-token-link": "#addcff",
  },
};

export default github;
