import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * GitHub — GitHub Light and GitHub Dark.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const github: ThemeConfig = {
  name: "github",
  colors: {
    primary: "#0969da",
    primaryHover: "#0550ae",
    background: "#ffffff",
    backgroundAlt: "#f6f8fa",
    text: "#1f2328",
    textMuted: "#59636e",
    border: "#d1d9e0",
    codeBackground: "#f6f8fa",
    codeBackgroundTop: "#f6f8fa",
    codeText: "#1f2328",
  },
  darkColors: {
    primary: "#4493f8",
    primaryHover: "#6cb6ff",
    background: "#0d1117",
    backgroundAlt: "#151b23",
    text: "#f0f6fc",
    textMuted: "#9198a1",
    border: "#3d444d",
    codeBackground: "#151b23",
    codeBackgroundTop: "#151b23",
    codeText: "#f0f6fc",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a6700 18%, transparent)",
    "color-code-line-warning-border": "#9a6700",
    "color-code-line-error": "color-mix(in srgb, #cf222e 20%, transparent)",
    "color-code-line-error-border": "#cf222e",
    "color-code-line-add": "color-mix(in srgb, #1a7f37 16%, transparent)",
    "color-code-line-add-border": "#1a7f37",
    "color-code-line-remove": "color-mix(in srgb, #cf222e 14%, transparent)",
    "color-code-line-remove-border": "#cf222e",
    "color-code-line-focus": "color-mix(in srgb, #0969da 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f6f8fa 92%, #1f2328)",
    "color-code-title-text": "color-mix(in srgb, #1f2328 88%, #f6f8fa)",
    "color-code-title-border": "color-mix(in srgb, #1f2328 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #1f2328 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d1d9e0 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f6f8fa 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d1d9e0 72%, #ffffff)",
    "brand-violet": "#8250df",
    "brand-cyan": "#1b7c83",
    "brand-lime": "#1a7f37",
    "brand-coral": "#cf222e",
    "brand-navy": "color-mix(in srgb, #1f2328 70%, #ffffff)",
    "brand-violet-rgb": "130, 80, 223",
    "brand-cyan-rgb": "27, 124, 131",
    "brand-lime-rgb": "26, 127, 55",
    "brand-coral-rgb": "207, 34, 46",
    "accent-a": "#0969da",
    "accent-b": "#8250df",
    "accent-c": "#1b7c83",
    "accent-warm": "#9a6700",
    "accent-cool": "#0969da",
    "accent-a-ink": "#0969da",
    "accent-b-ink": "#8250df",
    "accent-c-ink": "#1b7c83",
    "accent-warm-ink": "#9a6700",
    "accent-cool-ink": "#0969da",
    "accent-coral-ink": "#cf222e",
    "syntax-foreground": "#1f2328",
    "syntax-background": "#f6f8fa",
    "syntax-token-comment": "color-mix(in srgb, #1f2328 55%, #f6f8fa)",
    "syntax-token-punctuation": "color-mix(in srgb, #1f2328 72%, #f6f8fa)",
    "syntax-token-keyword": "#8250df",
    "syntax-token-string": "#1a7f37",
    "syntax-token-string-expression": "#1a7f37",
    "syntax-token-constant": "#9a6700",
    "syntax-token-function": "#0969da",
    "syntax-token-parameter": "#cf222e",
    "syntax-token-link": "#1b7c83",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4493f8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d29922 18%, transparent)",
    "color-code-line-warning-border": "#d29922",
    "color-code-line-error": "color-mix(in srgb, #ff7b72 20%, transparent)",
    "color-code-line-error-border": "#ff7b72",
    "color-code-line-add": "color-mix(in srgb, #3fb950 16%, transparent)",
    "color-code-line-add-border": "#3fb950",
    "color-code-line-remove": "color-mix(in srgb, #ff7b72 14%, transparent)",
    "color-code-line-remove-border": "#ff7b72",
    "color-code-line-focus": "color-mix(in srgb, #4493f8 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #151b23 92%, #f0f6fc)",
    "color-code-title-text": "color-mix(in srgb, #f0f6fc 88%, #151b23)",
    "color-code-title-border": "color-mix(in srgb, #f0f6fc 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0f6fc 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3d444d 92%, transparent)",
    "color-backdrop": "rgba(5, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #151b23 62%, #0d1117)",
    "surface-line": "color-mix(in srgb, #3d444d 72%, #0d1117)",
    "brand-violet": "#bc8cff",
    "brand-cyan": "#39c5cf",
    "brand-lime": "#3fb950",
    "brand-coral": "#ff7b72",
    "brand-navy": "color-mix(in srgb, #f0f6fc 70%, #0d1117)",
    "brand-violet-rgb": "188, 140, 255",
    "brand-cyan-rgb": "57, 197, 207",
    "brand-lime-rgb": "63, 185, 80",
    "brand-coral-rgb": "255, 123, 114",
    "accent-a": "#4493f8",
    "accent-b": "#bc8cff",
    "accent-c": "#39c5cf",
    "accent-warm": "#d29922",
    "accent-cool": "#4493f8",
    "accent-a-ink": "#4493f8",
    "accent-b-ink": "#bc8cff",
    "accent-c-ink": "#39c5cf",
    "accent-warm-ink": "#d29922",
    "accent-cool-ink": "#4493f8",
    "accent-coral-ink": "#ff7b72",
    "syntax-foreground": "#f0f6fc",
    "syntax-background": "#151b23",
    "syntax-token-comment": "color-mix(in srgb, #f0f6fc 55%, #151b23)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0f6fc 72%, #151b23)",
    "syntax-token-keyword": "#bc8cff",
    "syntax-token-string": "#3fb950",
    "syntax-token-string-expression": "#3fb950",
    "syntax-token-constant": "#d29922",
    "syntax-token-function": "#4493f8",
    "syntax-token-parameter": "#ff7b72",
    "syntax-token-link": "#39c5cf",
  },
};

export default github;
