import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Oceanic — Oceanic Next — deep slate teal.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const oceanic: ThemeConfig = {
  name: "oceanic",
  colors: {
    primary: "#0b7285",
    primaryHover: "#095c6b",
    background: "#fafbfc",
    backgroundAlt: "#eef1f4",
    text: "#1b2b34",
    textMuted: "#5b6b76",
    border: "#dbe1e6",
    codeBackground: "#1b2b34",
    codeBackgroundTop: "#1b2b34",
    codeText: "#cdd3de",
  },
  darkColors: {
    primary: "#6699cc",
    primaryHover: "#8fb6dc",
    background: "#1b2b34",
    backgroundAlt: "#22333c",
    text: "#cdd3de",
    textMuted: "#87949e",
    border: "#31424c",
    codeBackground: "#16242c",
    codeBackgroundTop: "#16242c",
    codeText: "#cdd3de",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3a6ea8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a6b1f 18%, transparent)",
    "color-code-line-warning-border": "#9a6b1f",
    "color-code-line-error": "color-mix(in srgb, #c1453b 20%, transparent)",
    "color-code-line-error-border": "#c1453b",
    "color-code-line-add": "color-mix(in srgb, #3f7d3f 16%, transparent)",
    "color-code-line-add-border": "#3f7d3f",
    "color-code-line-remove": "color-mix(in srgb, #c1453b 14%, transparent)",
    "color-code-line-remove-border": "#c1453b",
    "color-code-line-focus": "color-mix(in srgb, #0b7285 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #1b2b34 92%, #cdd3de)",
    "color-code-title-text": "color-mix(in srgb, #cdd3de 88%, #1b2b34)",
    "color-code-title-border": "color-mix(in srgb, #cdd3de 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cdd3de 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dbe1e6 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eef1f4 62%, #fafbfc)",
    "surface-line": "color-mix(in srgb, #dbe1e6 72%, #fafbfc)",
    "brand-violet": "#8a5a9e",
    "brand-cyan": "#0b7285",
    "brand-lime": "#3f7d3f",
    "brand-coral": "#c1453b",
    "brand-navy": "color-mix(in srgb, #1b2b34 70%, #fafbfc)",
    "brand-violet-rgb": "138, 90, 158",
    "brand-cyan-rgb": "11, 114, 133",
    "brand-lime-rgb": "63, 125, 63",
    "brand-coral-rgb": "193, 69, 59",
    "accent-a": "#0b7285",
    "accent-b": "#8a5a9e",
    "accent-c": "#0b7285",
    "accent-warm": "#9a6b1f",
    "accent-cool": "#3a6ea8",
    "accent-a-ink": "#0b7285",
    "accent-b-ink": "#8a5a9e",
    "accent-c-ink": "#0b7285",
    "accent-warm-ink": "#9a6b1f",
    "accent-cool-ink": "#3a6ea8",
    "accent-coral-ink": "#c1453b",
    "syntax-foreground": "#cdd3de",
    "syntax-background": "#1b2b34",
    "syntax-token-comment": "color-mix(in srgb, #cdd3de 55%, #1b2b34)",
    "syntax-token-punctuation": "color-mix(in srgb, #cdd3de 72%, #1b2b34)",
    "syntax-token-keyword": "#c594c5",
    "syntax-token-string": "#99c794",
    "syntax-token-string-expression": "#99c794",
    "syntax-token-constant": "#fac863",
    "syntax-token-function": "#6699cc",
    "syntax-token-parameter": "#ec5f67",
    "syntax-token-link": "#5fb3b3",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #6699cc 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fac863 18%, transparent)",
    "color-code-line-warning-border": "#fac863",
    "color-code-line-error": "color-mix(in srgb, #ec5f67 20%, transparent)",
    "color-code-line-error-border": "#ec5f67",
    "color-code-line-add": "color-mix(in srgb, #99c794 16%, transparent)",
    "color-code-line-add-border": "#99c794",
    "color-code-line-remove": "color-mix(in srgb, #ec5f67 14%, transparent)",
    "color-code-line-remove-border": "#ec5f67",
    "color-code-line-focus": "color-mix(in srgb, #6699cc 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #16242c 92%, #cdd3de)",
    "color-code-title-text": "color-mix(in srgb, #cdd3de 88%, #16242c)",
    "color-code-title-border": "color-mix(in srgb, #cdd3de 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #cdd3de 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #31424c 92%, transparent)",
    "color-backdrop": "rgba(9, 15, 18, 0.62)",
    "surface-glass": "color-mix(in srgb, #22333c 62%, #1b2b34)",
    "surface-line": "color-mix(in srgb, #31424c 72%, #1b2b34)",
    "brand-violet": "#c594c5",
    "brand-cyan": "#5fb3b3",
    "brand-lime": "#99c794",
    "brand-coral": "#ec5f67",
    "brand-navy": "color-mix(in srgb, #cdd3de 70%, #1b2b34)",
    "brand-violet-rgb": "197, 148, 197",
    "brand-cyan-rgb": "95, 179, 179",
    "brand-lime-rgb": "153, 199, 148",
    "brand-coral-rgb": "236, 95, 103",
    "accent-a": "#6699cc",
    "accent-b": "#c594c5",
    "accent-c": "#5fb3b3",
    "accent-warm": "#fac863",
    "accent-cool": "#6699cc",
    "accent-a-ink": "#6699cc",
    "accent-b-ink": "#c594c5",
    "accent-c-ink": "#5fb3b3",
    "accent-warm-ink": "#fac863",
    "accent-cool-ink": "#6699cc",
    "accent-coral-ink": "#ed656d",
    "syntax-foreground": "#cdd3de",
    "syntax-background": "#16242c",
    "syntax-token-comment": "color-mix(in srgb, #cdd3de 55%, #16242c)",
    "syntax-token-punctuation": "color-mix(in srgb, #cdd3de 72%, #16242c)",
    "syntax-token-keyword": "#c594c5",
    "syntax-token-string": "#99c794",
    "syntax-token-string-expression": "#99c794",
    "syntax-token-constant": "#fac863",
    "syntax-token-function": "#6699cc",
    "syntax-token-parameter": "#ec5f67",
    "syntax-token-link": "#5fb3b3",
  },
};
