import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Monokai — Monokai Pro with a light companion.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const monokai: ThemeConfig = {
  name: "monokai",
  colors: {
    primary: "#bc4584",
    primaryHover: "#a83a73",
    background: "#fdfdfd",
    backgroundAlt: "#f2f2f2",
    text: "#2c292d",
    textMuted: "#6b6669",
    border: "#dcdcdc",
    codeBackground: "#2d2a2e",
    codeBackgroundTop: "#2d2a2e",
    codeText: "#fcfcfa",
  },
  darkColors: {
    primary: "#ff6188",
    primaryHover: "#ff8ba7",
    background: "#2d2a2e",
    backgroundAlt: "#353236",
    text: "#fcfcfa",
    textMuted: "#939293",
    border: "#4a464b",
    codeBackground: "#221f22",
    codeBackgroundTop: "#221f22",
    codeText: "#fcfcfa",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #1c8ca8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #cc7a0a 18%, transparent)",
    "color-code-line-warning-border": "#cc7a0a",
    "color-code-line-error": "color-mix(in srgb, #e14775 20%, transparent)",
    "color-code-line-error-border": "#e14775",
    "color-code-line-add": "color-mix(in srgb, #269d69 16%, transparent)",
    "color-code-line-add-border": "#269d69",
    "color-code-line-remove": "color-mix(in srgb, #e14775 14%, transparent)",
    "color-code-line-remove-border": "#e14775",
    "color-code-line-focus": "color-mix(in srgb, #bc4584 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #2d2a2e 92%, #fcfcfa)",
    "color-code-title-text": "color-mix(in srgb, #fcfcfa 88%, #2d2a2e)",
    "color-code-title-border": "color-mix(in srgb, #fcfcfa 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #fcfcfa 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dcdcdc 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f2f2f2 62%, #fdfdfd)",
    "surface-line": "color-mix(in srgb, #dcdcdc 72%, #fdfdfd)",
    "brand-violet": "#7058be",
    "brand-cyan": "#1c8ca8",
    "brand-lime": "#269d69",
    "brand-coral": "#e14775",
    "brand-navy": "color-mix(in srgb, #2c292d 70%, #fdfdfd)",
    "brand-violet-rgb": "112, 88, 190",
    "brand-cyan-rgb": "28, 140, 168",
    "brand-lime-rgb": "38, 157, 105",
    "brand-coral-rgb": "225, 71, 117",
    "accent-a": "#bc4584",
    "accent-b": "#7058be",
    "accent-c": "#1c8ca8",
    "accent-warm": "#cc7a0a",
    "accent-cool": "#1c8ca8",
    "accent-a-ink": "#bc4584",
    "accent-b-ink": "#7058be",
    "accent-c-ink": "#197b94",
    "accent-warm-ink": "#a36208",
    "accent-cool-ink": "#197b94",
    "accent-coral-ink": "#c63e67",
    "shiki-foreground": "#fcfcfa",
    "shiki-background": "#2d2a2e",
    "shiki-token-comment": "color-mix(in srgb, #fcfcfa 55%, #2d2a2e)",
    "shiki-token-punctuation": "color-mix(in srgb, #fcfcfa 72%, #2d2a2e)",
    "shiki-token-keyword": "#ab9df2",
    "shiki-token-string": "#a9dc76",
    "shiki-token-string-expression": "#a9dc76",
    "shiki-token-constant": "#ffd866",
    "shiki-token-function": "#78dce8",
    "shiki-token-parameter": "#ff6188",
    "shiki-token-link": "#78dce8",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #78dce8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffd866 18%, transparent)",
    "color-code-line-warning-border": "#ffd866",
    "color-code-line-error": "color-mix(in srgb, #ff6188 20%, transparent)",
    "color-code-line-error-border": "#ff6188",
    "color-code-line-add": "color-mix(in srgb, #a9dc76 16%, transparent)",
    "color-code-line-add-border": "#a9dc76",
    "color-code-line-remove": "color-mix(in srgb, #ff6188 14%, transparent)",
    "color-code-line-remove-border": "#ff6188",
    "color-code-line-focus": "color-mix(in srgb, #ff6188 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #221f22 92%, #fcfcfa)",
    "color-code-title-text": "color-mix(in srgb, #fcfcfa 88%, #221f22)",
    "color-code-title-border": "color-mix(in srgb, #fcfcfa 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #fcfcfa 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #4a464b 92%, transparent)",
    "color-backdrop": "rgba(16, 15, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #353236 62%, #2d2a2e)",
    "surface-line": "color-mix(in srgb, #4a464b 72%, #2d2a2e)",
    "brand-violet": "#ab9df2",
    "brand-cyan": "#78dce8",
    "brand-lime": "#a9dc76",
    "brand-coral": "#ff6188",
    "brand-navy": "color-mix(in srgb, #fcfcfa 70%, #2d2a2e)",
    "brand-violet-rgb": "171, 157, 242",
    "brand-cyan-rgb": "120, 220, 232",
    "brand-lime-rgb": "169, 220, 118",
    "brand-coral-rgb": "255, 97, 136",
    "accent-a": "#ff6188",
    "accent-b": "#ab9df2",
    "accent-c": "#78dce8",
    "accent-warm": "#ffd866",
    "accent-cool": "#78dce8",
    "accent-a-ink": "#ff6188",
    "accent-b-ink": "#ab9df2",
    "accent-c-ink": "#78dce8",
    "accent-warm-ink": "#ffd866",
    "accent-cool-ink": "#78dce8",
    "accent-coral-ink": "#ff6188",
    "shiki-foreground": "#fcfcfa",
    "shiki-background": "#221f22",
    "shiki-token-comment": "color-mix(in srgb, #fcfcfa 55%, #221f22)",
    "shiki-token-punctuation": "color-mix(in srgb, #fcfcfa 72%, #221f22)",
    "shiki-token-keyword": "#ab9df2",
    "shiki-token-string": "#a9dc76",
    "shiki-token-string-expression": "#a9dc76",
    "shiki-token-constant": "#ffd866",
    "shiki-token-function": "#78dce8",
    "shiki-token-parameter": "#ff6188",
    "shiki-token-link": "#78dce8",
  },
};

export default monokai;
