import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Nord — Nord Snow Storm and Polar Night.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const nord: ThemeConfig = {
  name: "nord",
  colors: {
    primary: "#4f6c90",
    primaryHover: "#4c6f96",
    background: "#eceff4",
    backgroundAlt: "#e5e9f0",
    text: "#2e3440",
    textMuted: "#4c566a",
    border: "#d8dee9",
    codeBackground: "#2e3440",
    codeBackgroundTop: "#2e3440",
    codeText: "#eceff4",
  },
  darkColors: {
    primary: "#88c0d0",
    primaryHover: "#8fbcbb",
    background: "#2e3440",
    backgroundAlt: "#3b4252",
    text: "#eceff4",
    textMuted: "#a5aec0",
    border: "#434c5e",
    codeBackground: "#272c36",
    codeBackgroundTop: "#272c36",
    codeText: "#eceff4",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5e81ac 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d08770 18%, transparent)",
    "color-code-line-warning-border": "#d08770",
    "color-code-line-error": "color-mix(in srgb, #bf616a 20%, transparent)",
    "color-code-line-error-border": "#bf616a",
    "color-code-line-add": "color-mix(in srgb, #a3be8c 16%, transparent)",
    "color-code-line-add-border": "#a3be8c",
    "color-code-line-remove": "color-mix(in srgb, #bf616a 14%, transparent)",
    "color-code-line-remove-border": "#bf616a",
    "color-code-line-focus": "color-mix(in srgb, #4f6c90 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #2e3440 92%, #eceff4)",
    "color-code-title-text": "color-mix(in srgb, #eceff4 88%, #2e3440)",
    "color-code-title-border": "color-mix(in srgb, #eceff4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #eceff4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d8dee9 92%, transparent)",
    "color-backdrop": "rgba(83, 84, 85, 0.62)",
    "surface-glass": "color-mix(in srgb, #e5e9f0 62%, #eceff4)",
    "surface-line": "color-mix(in srgb, #d8dee9 72%, #eceff4)",
    "brand-violet": "#b48ead",
    "brand-cyan": "#88c0d0",
    "brand-lime": "#a3be8c",
    "brand-coral": "#bf616a",
    "brand-navy": "color-mix(in srgb, #2e3440 70%, #eceff4)",
    "brand-violet-rgb": "180, 142, 173",
    "brand-cyan-rgb": "136, 192, 208",
    "brand-lime-rgb": "163, 190, 140",
    "brand-coral-rgb": "191, 97, 106",
    "accent-a": "#4f6c90",
    "accent-b": "#b48ead",
    "accent-c": "#88c0d0",
    "accent-warm": "#d08770",
    "accent-cool": "#5e81ac",
    "accent-a-ink": "#4f6c90",
    "accent-b-ink": "#7a6176",
    "accent-c-ink": "#4c6c74",
    "accent-warm-ink": "#8d5c4c",
    "accent-cool-ink": "#4f6c90",
    "accent-coral-ink": "#a05159",
    "syntax-foreground": "#eceff4",
    "syntax-background": "#2e3440",
    "syntax-token-comment": "color-mix(in srgb, #eceff4 55%, #2e3440)",
    "syntax-token-punctuation": "color-mix(in srgb, #eceff4 72%, #2e3440)",
    "syntax-token-keyword": "#b48ead",
    "syntax-token-string": "#a3be8c",
    "syntax-token-string-expression": "#a3be8c",
    "syntax-token-constant": "#ebcb8b",
    "syntax-token-function": "#81a1c1",
    "syntax-token-parameter": "#bf616a",
    "syntax-token-link": "#88c0d0",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #81a1c1 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ebcb8b 18%, transparent)",
    "color-code-line-warning-border": "#ebcb8b",
    "color-code-line-error": "color-mix(in srgb, #bf616a 20%, transparent)",
    "color-code-line-error-border": "#bf616a",
    "color-code-line-add": "color-mix(in srgb, #a3be8c 16%, transparent)",
    "color-code-line-add-border": "#a3be8c",
    "color-code-line-remove": "color-mix(in srgb, #bf616a 14%, transparent)",
    "color-code-line-remove-border": "#bf616a",
    "color-code-line-focus": "color-mix(in srgb, #88c0d0 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #272c36 92%, #eceff4)",
    "color-code-title-text": "color-mix(in srgb, #eceff4 88%, #272c36)",
    "color-code-title-border": "color-mix(in srgb, #eceff4 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #eceff4 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #434c5e 92%, transparent)",
    "color-backdrop": "rgba(16, 18, 22, 0.62)",
    "surface-glass": "color-mix(in srgb, #3b4252 62%, #2e3440)",
    "surface-line": "color-mix(in srgb, #434c5e 72%, #2e3440)",
    "brand-violet": "#b48ead",
    "brand-cyan": "#88c0d0",
    "brand-lime": "#a3be8c",
    "brand-coral": "#bf616a",
    "brand-navy": "color-mix(in srgb, #eceff4 70%, #2e3440)",
    "brand-violet-rgb": "180, 142, 173",
    "brand-cyan-rgb": "136, 192, 208",
    "brand-lime-rgb": "163, 190, 140",
    "brand-coral-rgb": "191, 97, 106",
    "accent-a": "#88c0d0",
    "accent-b": "#b48ead",
    "accent-c": "#88c0d0",
    "accent-warm": "#ebcb8b",
    "accent-cool": "#81a1c1",
    "accent-a-ink": "#88c0d0",
    "accent-b-ink": "#b793b0",
    "accent-c-ink": "#88c0d0",
    "accent-warm-ink": "#ebcb8b",
    "accent-cool-ink": "#81a1c1",
    "accent-coral-ink": "#d18d94",
    "syntax-foreground": "#eceff4",
    "syntax-background": "#272c36",
    "syntax-token-comment": "color-mix(in srgb, #eceff4 55%, #272c36)",
    "syntax-token-punctuation": "color-mix(in srgb, #eceff4 72%, #272c36)",
    "syntax-token-keyword": "#b48ead",
    "syntax-token-string": "#a3be8c",
    "syntax-token-string-expression": "#a3be8c",
    "syntax-token-constant": "#ebcb8b",
    "syntax-token-function": "#81a1c1",
    "syntax-token-parameter": "#bf616a",
    "syntax-token-link": "#88c0d0",
  },
};

export default nord;
