import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Moss — Deep forest and paper cream.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const moss: ThemeConfig = {
  name: "moss",
  colors: {
    primary: "#2f6b4f",
    primaryHover: "#22513c",
    background: "#f7f6f0",
    backgroundAlt: "#ecebe1",
    text: "#17211b",
    textMuted: "#5c6b60",
    border: "#dbdccf",
    codeBackground: "#14201a",
    codeBackgroundTop: "#14201a",
    codeText: "#e6ece7",
  },
  darkColors: {
    primary: "#7fc79b",
    primaryHover: "#a4dbb7",
    background: "#111813",
    backgroundAlt: "#18211b",
    text: "#e2e9e2",
    textMuted: "#8b9a8e",
    border: "#243027",
    codeBackground: "#0c120e",
    codeBackgroundTop: "#0c120e",
    codeText: "#e2e9e2",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3c5f72 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8a6a1d 18%, transparent)",
    "color-code-line-warning-border": "#8a6a1d",
    "color-code-line-error": "color-mix(in srgb, #a4432f 20%, transparent)",
    "color-code-line-error-border": "#a4432f",
    "color-code-line-add": "color-mix(in srgb, #2f6b4f 16%, transparent)",
    "color-code-line-add-border": "#2f6b4f",
    "color-code-line-remove": "color-mix(in srgb, #a4432f 14%, transparent)",
    "color-code-line-remove-border": "#a4432f",
    "color-code-line-focus": "color-mix(in srgb, #2f6b4f 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #14201a 92%, #e6ece7)",
    "color-code-title-text": "color-mix(in srgb, #e6ece7 88%, #14201a)",
    "color-code-title-border": "color-mix(in srgb, #e6ece7 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6ece7 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dbdccf 92%, transparent)",
    "color-backdrop": "rgba(86, 86, 84, 0.62)",
    "surface-glass": "color-mix(in srgb, #ecebe1 62%, #f7f6f0)",
    "surface-line": "color-mix(in srgb, #dbdccf 72%, #f7f6f0)",
    "brand-violet": "#7a4d6a",
    "brand-cyan": "#2e6d68",
    "brand-lime": "#2f6b4f",
    "brand-coral": "#a4432f",
    "brand-navy": "color-mix(in srgb, #17211b 70%, #f7f6f0)",
    "brand-violet-rgb": "122, 77, 106",
    "brand-cyan-rgb": "46, 109, 104",
    "brand-lime-rgb": "47, 107, 79",
    "brand-coral-rgb": "164, 67, 47",
    "accent-a": "#2f6b4f",
    "accent-b": "#7a4d6a",
    "accent-c": "#2e6d68",
    "accent-warm": "#8a6a1d",
    "accent-cool": "#3c5f72",
    "accent-a-ink": "#2f6b4f",
    "accent-b-ink": "#7a4d6a",
    "accent-c-ink": "#2e6d68",
    "accent-warm-ink": "#8a6a1d",
    "accent-cool-ink": "#3c5f72",
    "accent-coral-ink": "#a4432f",
    "syntax-foreground": "#e6ece7",
    "syntax-background": "#14201a",
    "syntax-token-comment": "color-mix(in srgb, #e6ece7 55%, #14201a)",
    "syntax-token-punctuation": "color-mix(in srgb, #e6ece7 72%, #14201a)",
    "syntax-token-keyword": "#c39ab8",
    "syntax-token-string": "#7fc79b",
    "syntax-token-string-expression": "#7fc79b",
    "syntax-token-constant": "#d7bd7c",
    "syntax-token-function": "#89b3c9",
    "syntax-token-parameter": "#e08a76",
    "syntax-token-link": "#79c4bd",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #89b3c9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d7bd7c 18%, transparent)",
    "color-code-line-warning-border": "#d7bd7c",
    "color-code-line-error": "color-mix(in srgb, #e08a76 20%, transparent)",
    "color-code-line-error-border": "#e08a76",
    "color-code-line-add": "color-mix(in srgb, #7fc79b 16%, transparent)",
    "color-code-line-add-border": "#7fc79b",
    "color-code-line-remove": "color-mix(in srgb, #e08a76 14%, transparent)",
    "color-code-line-remove-border": "#e08a76",
    "color-code-line-focus": "color-mix(in srgb, #7fc79b 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0c120e 92%, #e2e9e2)",
    "color-code-title-text": "color-mix(in srgb, #e2e9e2 88%, #0c120e)",
    "color-code-title-border": "color-mix(in srgb, #e2e9e2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e2e9e2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #243027 92%, transparent)",
    "color-backdrop": "rgba(6, 8, 7, 0.62)",
    "surface-glass": "color-mix(in srgb, #18211b 62%, #111813)",
    "surface-line": "color-mix(in srgb, #243027 72%, #111813)",
    "brand-violet": "#c39ab8",
    "brand-cyan": "#79c4bd",
    "brand-lime": "#7fc79b",
    "brand-coral": "#e08a76",
    "brand-navy": "color-mix(in srgb, #e2e9e2 70%, #111813)",
    "brand-violet-rgb": "195, 154, 184",
    "brand-cyan-rgb": "121, 196, 189",
    "brand-lime-rgb": "127, 199, 155",
    "brand-coral-rgb": "224, 138, 118",
    "accent-a": "#7fc79b",
    "accent-b": "#c39ab8",
    "accent-c": "#79c4bd",
    "accent-warm": "#d7bd7c",
    "accent-cool": "#89b3c9",
    "accent-a-ink": "#7fc79b",
    "accent-b-ink": "#c39ab8",
    "accent-c-ink": "#79c4bd",
    "accent-warm-ink": "#d7bd7c",
    "accent-cool-ink": "#89b3c9",
    "accent-coral-ink": "#e08a76",
    "syntax-foreground": "#e2e9e2",
    "syntax-background": "#0c120e",
    "syntax-token-comment": "color-mix(in srgb, #e2e9e2 55%, #0c120e)",
    "syntax-token-punctuation": "color-mix(in srgb, #e2e9e2 72%, #0c120e)",
    "syntax-token-keyword": "#c39ab8",
    "syntax-token-string": "#7fc79b",
    "syntax-token-string-expression": "#7fc79b",
    "syntax-token-constant": "#d7bd7c",
    "syntax-token-function": "#89b3c9",
    "syntax-token-parameter": "#e08a76",
    "syntax-token-link": "#79c4bd",
  },
};
