import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Modus — Protesilaos' accessibility-first scheme, WCAG AAA throughout.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const modus: ThemeConfig = {
  name: "modus",
  colors: {
    primary: "#3548cf",
    primaryHover: "#2635a8",
    background: "#ffffff",
    backgroundAlt: "#f2f2f2",
    text: "#000000",
    textMuted: "#505050",
    border: "#d0d0d0",
    codeBackground: "#f2f2f2",
    codeBackgroundTop: "#f2f2f2",
    codeText: "#000000",
  },
  darkColors: {
    primary: "#79a8ff",
    primaryHover: "#a3c4ff",
    background: "#000000",
    backgroundAlt: "#1e1e1e",
    text: "#ffffff",
    textMuted: "#a8a8a8",
    border: "#3a3a3a",
    codeBackground: "#0d0d0d",
    codeBackgroundTop: "#0d0d0d",
    codeText: "#ffffff",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3548cf 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #6f5500 18%, transparent)",
    "color-code-line-warning-border": "#6f5500",
    "color-code-line-error": "color-mix(in srgb, #a60000 20%, transparent)",
    "color-code-line-error-border": "#a60000",
    "color-code-line-add": "color-mix(in srgb, #006800 16%, transparent)",
    "color-code-line-add-border": "#006800",
    "color-code-line-remove": "color-mix(in srgb, #a60000 14%, transparent)",
    "color-code-line-remove-border": "#a60000",
    "color-code-line-focus": "color-mix(in srgb, #3548cf 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f2f2f2 92%, #000000)",
    "color-code-title-text": "color-mix(in srgb, #000000 88%, #f2f2f2)",
    "color-code-title-border": "color-mix(in srgb, #000000 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #000000 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d0d0d0 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f2f2f2 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #d0d0d0 72%, #ffffff)",
    "brand-violet": "#721045",
    "brand-cyan": "#005e8b",
    "brand-lime": "#006800",
    "brand-coral": "#a60000",
    "brand-navy": "color-mix(in srgb, #000000 70%, #ffffff)",
    "brand-violet-rgb": "114, 16, 69",
    "brand-cyan-rgb": "0, 94, 139",
    "brand-lime-rgb": "0, 104, 0",
    "brand-coral-rgb": "166, 0, 0",
    "accent-a": "#3548cf",
    "accent-b": "#721045",
    "accent-c": "#005e8b",
    "accent-warm": "#6f5500",
    "accent-cool": "#3548cf",
    "accent-a-ink": "#3548cf",
    "accent-b-ink": "#721045",
    "accent-c-ink": "#005e8b",
    "accent-warm-ink": "#6f5500",
    "accent-cool-ink": "#3548cf",
    "accent-coral-ink": "#a60000",
    "syntax-foreground": "#000000",
    "syntax-background": "#f2f2f2",
    "syntax-token-comment": "color-mix(in srgb, #000000 55%, #f2f2f2)",
    "syntax-token-punctuation": "color-mix(in srgb, #000000 72%, #f2f2f2)",
    "syntax-token-keyword": "#721045",
    "syntax-token-string": "#006800",
    "syntax-token-string-expression": "#006800",
    "syntax-token-constant": "#6f5500",
    "syntax-token-function": "#3548cf",
    "syntax-token-parameter": "#a60000",
    "syntax-token-link": "#005e8b",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #79a8ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d0bc00 18%, transparent)",
    "color-code-line-warning-border": "#d0bc00",
    "color-code-line-error": "color-mix(in srgb, #ff5f59 20%, transparent)",
    "color-code-line-error-border": "#ff5f59",
    "color-code-line-add": "color-mix(in srgb, #44bc44 16%, transparent)",
    "color-code-line-add-border": "#44bc44",
    "color-code-line-remove": "color-mix(in srgb, #ff5f59 14%, transparent)",
    "color-code-line-remove-border": "#ff5f59",
    "color-code-line-focus": "color-mix(in srgb, #79a8ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0d0d0d 92%, #ffffff)",
    "color-code-title-text": "color-mix(in srgb, #ffffff 88%, #0d0d0d)",
    "color-code-title-border": "color-mix(in srgb, #ffffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3a3a3a 92%, transparent)",
    "color-backdrop": "rgba(0, 0, 0, 0.62)",
    "surface-glass": "color-mix(in srgb, #1e1e1e 62%, #000000)",
    "surface-line": "color-mix(in srgb, #3a3a3a 72%, #000000)",
    "brand-violet": "#f78fe7",
    "brand-cyan": "#00d3d0",
    "brand-lime": "#44bc44",
    "brand-coral": "#ff5f59",
    "brand-navy": "color-mix(in srgb, #ffffff 70%, #000000)",
    "brand-violet-rgb": "247, 143, 231",
    "brand-cyan-rgb": "0, 211, 208",
    "brand-lime-rgb": "68, 188, 68",
    "brand-coral-rgb": "255, 95, 89",
    "accent-a": "#79a8ff",
    "accent-b": "#f78fe7",
    "accent-c": "#00d3d0",
    "accent-warm": "#d0bc00",
    "accent-cool": "#79a8ff",
    "accent-a-ink": "#79a8ff",
    "accent-b-ink": "#f78fe7",
    "accent-c-ink": "#00d3d0",
    "accent-warm-ink": "#d0bc00",
    "accent-cool-ink": "#79a8ff",
    "accent-coral-ink": "#ff5f59",
    "syntax-foreground": "#ffffff",
    "syntax-background": "#0d0d0d",
    "syntax-token-comment": "color-mix(in srgb, #ffffff 55%, #0d0d0d)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffffff 72%, #0d0d0d)",
    "syntax-token-keyword": "#f78fe7",
    "syntax-token-string": "#44bc44",
    "syntax-token-string-expression": "#44bc44",
    "syntax-token-constant": "#d0bc00",
    "syntax-token-function": "#79a8ff",
    "syntax-token-parameter": "#ff5f59",
    "syntax-token-link": "#00d3d0",
  },
};

export default modus;
