import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Poimandres — Poimandres, cool teal on deep navy.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const poimandres: ThemeConfig = {
  name: "poimandres",
  colors: {
    primary: "#0b7285",
    primaryHover: "#095c6b",
    background: "#fcfcfc",
    backgroundAlt: "#f1f3f5",
    text: "#1b1e28",
    textMuted: "#5f6672",
    border: "#dfe3e8",
    codeBackground: "#1b1e28",
    codeBackgroundTop: "#1b1e28",
    codeText: "#e4f0fb",
  },
  darkColors: {
    primary: "#add7ff",
    primaryHover: "#cbe4ff",
    background: "#1b1e28",
    backgroundAlt: "#252b37",
    text: "#e4f0fb",
    textMuted: "#8186a5",
    border: "#303340",
    codeBackground: "#171922",
    codeBackgroundTop: "#171922",
    codeText: "#e4f0fb",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2b6ea8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a6d17 18%, transparent)",
    "color-code-line-warning-border": "#9a6d17",
    "color-code-line-error": "color-mix(in srgb, #c14a5c 20%, transparent)",
    "color-code-line-error-border": "#c14a5c",
    "color-code-line-add": "color-mix(in srgb, #0f7a5f 16%, transparent)",
    "color-code-line-add-border": "#0f7a5f",
    "color-code-line-remove": "color-mix(in srgb, #c14a5c 14%, transparent)",
    "color-code-line-remove-border": "#c14a5c",
    "color-code-line-focus": "color-mix(in srgb, #0b7285 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #1b1e28 92%, #e4f0fb)",
    "color-code-title-text": "color-mix(in srgb, #e4f0fb 88%, #1b1e28)",
    "color-code-title-border": "color-mix(in srgb, #e4f0fb 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e4f0fb 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dfe3e8 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f1f3f5 62%, #fcfcfc)",
    "surface-line": "color-mix(in srgb, #dfe3e8 72%, #fcfcfc)",
    "brand-violet": "#7f5bb0",
    "brand-cyan": "#0b7285",
    "brand-lime": "#0f7a5f",
    "brand-coral": "#c14a5c",
    "brand-navy": "color-mix(in srgb, #1b1e28 70%, #fcfcfc)",
    "brand-violet-rgb": "127, 91, 176",
    "brand-cyan-rgb": "11, 114, 133",
    "brand-lime-rgb": "15, 122, 95",
    "brand-coral-rgb": "193, 74, 92",
    "accent-a": "#0b7285",
    "accent-b": "#7f5bb0",
    "accent-c": "#0b7285",
    "accent-warm": "#9a6d17",
    "accent-cool": "#2b6ea8",
    "accent-a-ink": "#0b7285",
    "accent-b-ink": "#7f5bb0",
    "accent-c-ink": "#0b7285",
    "accent-warm-ink": "#946916",
    "accent-cool-ink": "#2b6ea8",
    "accent-coral-ink": "#c14a5c",
    "syntax-foreground": "#e4f0fb",
    "syntax-background": "#1b1e28",
    "syntax-token-comment": "color-mix(in srgb, #e4f0fb 55%, #1b1e28)",
    "syntax-token-punctuation": "color-mix(in srgb, #e4f0fb 72%, #1b1e28)",
    "syntax-token-keyword": "#f087bd",
    "syntax-token-string": "#5de4c7",
    "syntax-token-string-expression": "#5de4c7",
    "syntax-token-constant": "#fffac2",
    "syntax-token-function": "#add7ff",
    "syntax-token-parameter": "#d0679d",
    "syntax-token-link": "#89ddff",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #add7ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fffac2 18%, transparent)",
    "color-code-line-warning-border": "#fffac2",
    "color-code-line-error": "color-mix(in srgb, #d0679d 20%, transparent)",
    "color-code-line-error-border": "#d0679d",
    "color-code-line-add": "color-mix(in srgb, #5de4c7 16%, transparent)",
    "color-code-line-add-border": "#5de4c7",
    "color-code-line-remove": "color-mix(in srgb, #d0679d 14%, transparent)",
    "color-code-line-remove-border": "#d0679d",
    "color-code-line-focus": "color-mix(in srgb, #add7ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #171922 92%, #e4f0fb)",
    "color-code-title-text": "color-mix(in srgb, #e4f0fb 88%, #171922)",
    "color-code-title-border": "color-mix(in srgb, #e4f0fb 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e4f0fb 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #303340 92%, transparent)",
    "color-backdrop": "rgba(9, 11, 14, 0.62)",
    "surface-glass": "color-mix(in srgb, #252b37 62%, #1b1e28)",
    "surface-line": "color-mix(in srgb, #303340 72%, #1b1e28)",
    "brand-violet": "#f087bd",
    "brand-cyan": "#89ddff",
    "brand-lime": "#5de4c7",
    "brand-coral": "#d0679d",
    "brand-navy": "color-mix(in srgb, #e4f0fb 70%, #1b1e28)",
    "brand-violet-rgb": "240, 135, 189",
    "brand-cyan-rgb": "137, 221, 255",
    "brand-lime-rgb": "93, 228, 199",
    "brand-coral-rgb": "208, 103, 157",
    "accent-a": "#add7ff",
    "accent-b": "#f087bd",
    "accent-c": "#89ddff",
    "accent-warm": "#fffac2",
    "accent-cool": "#add7ff",
    "accent-a-ink": "#add7ff",
    "accent-b-ink": "#f087bd",
    "accent-c-ink": "#89ddff",
    "accent-warm-ink": "#fffac2",
    "accent-cool-ink": "#add7ff",
    "accent-coral-ink": "#d0679d",
    "syntax-foreground": "#e4f0fb",
    "syntax-background": "#171922",
    "syntax-token-comment": "color-mix(in srgb, #e4f0fb 55%, #171922)",
    "syntax-token-punctuation": "color-mix(in srgb, #e4f0fb 72%, #171922)",
    "syntax-token-keyword": "#f087bd",
    "syntax-token-string": "#5de4c7",
    "syntax-token-string-expression": "#5de4c7",
    "syntax-token-constant": "#fffac2",
    "syntax-token-function": "#add7ff",
    "syntax-token-parameter": "#d0679d",
    "syntax-token-link": "#89ddff",
  },
};

export default poimandres;
