import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * High Contrast — Maximum-contrast scheme aimed at WCAG AAA body text.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const highContrast: ThemeConfig = {
  name: "high-contrast",
  colors: {
    primary: "#0000cc",
    primaryHover: "#000099",
    background: "#ffffff",
    backgroundAlt: "#f0f0f0",
    text: "#000000",
    textMuted: "#3d3d3d",
    border: "#000000",
    codeBackground: "#000000",
    codeBackgroundTop: "#000000",
    codeText: "#ffffff",
  },
  darkColors: {
    primary: "#66d9ff",
    primaryHover: "#a6e9ff",
    background: "#000000",
    backgroundAlt: "#0f0f0f",
    text: "#ffffff",
    textMuted: "#c4c4c4",
    border: "#ffffff",
    codeBackground: "#000000",
    codeBackgroundTop: "#000000",
    codeText: "#ffffff",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #0000cc 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #664d00 18%, transparent)",
    "color-code-line-warning-border": "#664d00",
    "color-code-line-error": "color-mix(in srgb, #b30000 20%, transparent)",
    "color-code-line-error-border": "#b30000",
    "color-code-line-add": "color-mix(in srgb, #005c1f 16%, transparent)",
    "color-code-line-add-border": "#005c1f",
    "color-code-line-remove": "color-mix(in srgb, #b30000 14%, transparent)",
    "color-code-line-remove-border": "#b30000",
    "color-code-line-focus": "color-mix(in srgb, #0000cc 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #000000 92%, #ffffff)",
    "color-code-title-text": "color-mix(in srgb, #ffffff 88%, #000000)",
    "color-code-title-border": "color-mix(in srgb, #ffffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #000000 92%, transparent)",
    "color-backdrop": "rgba(89, 89, 89, 0.62)",
    "surface-glass": "color-mix(in srgb, #f0f0f0 62%, #ffffff)",
    "surface-line": "color-mix(in srgb, #000000 72%, #ffffff)",
    "brand-violet": "#7a007a",
    "brand-cyan": "#00565c",
    "brand-lime": "#005c1f",
    "brand-coral": "#b30000",
    "brand-navy": "color-mix(in srgb, #000000 70%, #ffffff)",
    "brand-violet-rgb": "122, 0, 122",
    "brand-cyan-rgb": "0, 86, 92",
    "brand-lime-rgb": "0, 92, 31",
    "brand-coral-rgb": "179, 0, 0",
    "accent-a": "#0000cc",
    "accent-b": "#7a007a",
    "accent-c": "#00565c",
    "accent-warm": "#664d00",
    "accent-cool": "#0000cc",
    "accent-a-ink": "#0000cc",
    "accent-b-ink": "#7a007a",
    "accent-c-ink": "#00565c",
    "accent-warm-ink": "#664d00",
    "accent-cool-ink": "#0000cc",
    "accent-coral-ink": "#b30000",
    "syntax-foreground": "#ffffff",
    "syntax-background": "#000000",
    "syntax-token-comment": "color-mix(in srgb, #ffffff 55%, #000000)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffffff 72%, #000000)",
    "syntax-token-keyword": "#ff9fff",
    "syntax-token-string": "#5eff8f",
    "syntax-token-string-expression": "#5eff8f",
    "syntax-token-constant": "#ffe680",
    "syntax-token-function": "#66d9ff",
    "syntax-token-parameter": "#ff8080",
    "syntax-token-link": "#80ffff",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #66d9ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffe680 18%, transparent)",
    "color-code-line-warning-border": "#ffe680",
    "color-code-line-error": "color-mix(in srgb, #ff8080 20%, transparent)",
    "color-code-line-error-border": "#ff8080",
    "color-code-line-add": "color-mix(in srgb, #5eff8f 16%, transparent)",
    "color-code-line-add-border": "#5eff8f",
    "color-code-line-remove": "color-mix(in srgb, #ff8080 14%, transparent)",
    "color-code-line-remove-border": "#ff8080",
    "color-code-line-focus": "color-mix(in srgb, #66d9ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #000000 92%, #ffffff)",
    "color-code-title-text": "color-mix(in srgb, #ffffff 88%, #000000)",
    "color-code-title-border": "color-mix(in srgb, #ffffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ffffff 92%, transparent)",
    "color-backdrop": "rgba(0, 0, 0, 0.62)",
    "surface-glass": "color-mix(in srgb, #0f0f0f 62%, #000000)",
    "surface-line": "color-mix(in srgb, #ffffff 72%, #000000)",
    "brand-violet": "#ff9fff",
    "brand-cyan": "#80ffff",
    "brand-lime": "#5eff8f",
    "brand-coral": "#ff8080",
    "brand-navy": "color-mix(in srgb, #ffffff 70%, #000000)",
    "brand-violet-rgb": "255, 159, 255",
    "brand-cyan-rgb": "128, 255, 255",
    "brand-lime-rgb": "94, 255, 143",
    "brand-coral-rgb": "255, 128, 128",
    "accent-a": "#66d9ff",
    "accent-b": "#ff9fff",
    "accent-c": "#80ffff",
    "accent-warm": "#ffe680",
    "accent-cool": "#66d9ff",
    "accent-a-ink": "#66d9ff",
    "accent-b-ink": "#ff9fff",
    "accent-c-ink": "#80ffff",
    "accent-warm-ink": "#ffe680",
    "accent-cool-ink": "#66d9ff",
    "accent-coral-ink": "#ff8080",
    "syntax-foreground": "#ffffff",
    "syntax-background": "#000000",
    "syntax-token-comment": "color-mix(in srgb, #ffffff 55%, #000000)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffffff 72%, #000000)",
    "syntax-token-keyword": "#ff9fff",
    "syntax-token-string": "#5eff8f",
    "syntax-token-string-expression": "#5eff8f",
    "syntax-token-constant": "#ffe680",
    "syntax-token-function": "#66d9ff",
    "syntax-token-parameter": "#ff8080",
    "syntax-token-link": "#80ffff",
  },
};
