import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Graphite — Off-black and off-white with one electric accent.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const graphite: ThemeConfig = {
  name: "graphite",
  colors: {
    primary: "#3b5bfd",
    primaryHover: "#2842d4",
    background: "#fbfbfc",
    backgroundAlt: "#f1f2f4",
    text: "#16161a",
    textMuted: "#6a6c73",
    border: "#e4e5e9",
    codeBackground: "#16161a",
    codeBackgroundTop: "#16161a",
    codeText: "#e9eaee",
  },
  darkColors: {
    primary: "#8ba0ff",
    primaryHover: "#adbcff",
    background: "#101014",
    backgroundAlt: "#18181d",
    text: "#e9eaee",
    textMuted: "#8b8d96",
    border: "#26262e",
    codeBackground: "#0b0b0e",
    codeBackgroundTop: "#0b0b0e",
    codeText: "#e9eaee",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3b5bfd 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #96690d 18%, transparent)",
    "color-code-line-warning-border": "#96690d",
    "color-code-line-error": "color-mix(in srgb, #d33a3a 20%, transparent)",
    "color-code-line-error-border": "#d33a3a",
    "color-code-line-add": "color-mix(in srgb, #1c7f52 16%, transparent)",
    "color-code-line-add-border": "#1c7f52",
    "color-code-line-remove": "color-mix(in srgb, #d33a3a 14%, transparent)",
    "color-code-line-remove-border": "#d33a3a",
    "color-code-line-focus": "color-mix(in srgb, #3b5bfd 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #16161a 92%, #e9eaee)",
    "color-code-title-text": "color-mix(in srgb, #e9eaee 88%, #16161a)",
    "color-code-title-border": "color-mix(in srgb, #e9eaee 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e9eaee 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e4e5e9 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f1f2f4 62%, #fbfbfc)",
    "surface-line": "color-mix(in srgb, #e4e5e9 72%, #fbfbfc)",
    "brand-violet": "#7b45d6",
    "brand-cyan": "#0f7f8c",
    "brand-lime": "#1c7f52",
    "brand-coral": "#d33a3a",
    "brand-navy": "color-mix(in srgb, #16161a 70%, #fbfbfc)",
    "brand-violet-rgb": "123, 69, 214",
    "brand-cyan-rgb": "15, 127, 140",
    "brand-lime-rgb": "28, 127, 82",
    "brand-coral-rgb": "211, 58, 58",
    "accent-a": "#3b5bfd",
    "accent-b": "#7b45d6",
    "accent-c": "#0f7f8c",
    "accent-warm": "#96690d",
    "accent-cool": "#3b5bfd",
    "accent-a-ink": "#3b5bfd",
    "accent-b-ink": "#7b45d6",
    "accent-c-ink": "#0f7f8c",
    "accent-warm-ink": "#96690d",
    "accent-cool-ink": "#3b5bfd",
    "accent-coral-ink": "#d33a3a",
    "syntax-foreground": "#e9eaee",
    "syntax-background": "#16161a",
    "syntax-token-comment": "color-mix(in srgb, #e9eaee 55%, #16161a)",
    "syntax-token-punctuation": "color-mix(in srgb, #e9eaee 72%, #16161a)",
    "syntax-token-keyword": "#b898f5",
    "syntax-token-string": "#5fd39b",
    "syntax-token-string-expression": "#5fd39b",
    "syntax-token-constant": "#e0b96a",
    "syntax-token-function": "#8ba0ff",
    "syntax-token-parameter": "#ff8080",
    "syntax-token-link": "#5ecfd8",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8ba0ff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e0b96a 18%, transparent)",
    "color-code-line-warning-border": "#e0b96a",
    "color-code-line-error": "color-mix(in srgb, #ff8080 20%, transparent)",
    "color-code-line-error-border": "#ff8080",
    "color-code-line-add": "color-mix(in srgb, #5fd39b 16%, transparent)",
    "color-code-line-add-border": "#5fd39b",
    "color-code-line-remove": "color-mix(in srgb, #ff8080 14%, transparent)",
    "color-code-line-remove-border": "#ff8080",
    "color-code-line-focus": "color-mix(in srgb, #8ba0ff 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0b0b0e 92%, #e9eaee)",
    "color-code-title-text": "color-mix(in srgb, #e9eaee 88%, #0b0b0e)",
    "color-code-title-border": "color-mix(in srgb, #e9eaee 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e9eaee 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #26262e 92%, transparent)",
    "color-backdrop": "rgba(6, 6, 7, 0.62)",
    "surface-glass": "color-mix(in srgb, #18181d 62%, #101014)",
    "surface-line": "color-mix(in srgb, #26262e 72%, #101014)",
    "brand-violet": "#b898f5",
    "brand-cyan": "#5ecfd8",
    "brand-lime": "#5fd39b",
    "brand-coral": "#ff8080",
    "brand-navy": "color-mix(in srgb, #e9eaee 70%, #101014)",
    "brand-violet-rgb": "184, 152, 245",
    "brand-cyan-rgb": "94, 207, 216",
    "brand-lime-rgb": "95, 211, 155",
    "brand-coral-rgb": "255, 128, 128",
    "accent-a": "#8ba0ff",
    "accent-b": "#b898f5",
    "accent-c": "#5ecfd8",
    "accent-warm": "#e0b96a",
    "accent-cool": "#8ba0ff",
    "accent-a-ink": "#8ba0ff",
    "accent-b-ink": "#b898f5",
    "accent-c-ink": "#5ecfd8",
    "accent-warm-ink": "#e0b96a",
    "accent-cool-ink": "#8ba0ff",
    "accent-coral-ink": "#ff8080",
    "syntax-foreground": "#e9eaee",
    "syntax-background": "#0b0b0e",
    "syntax-token-comment": "color-mix(in srgb, #e9eaee 55%, #0b0b0e)",
    "syntax-token-punctuation": "color-mix(in srgb, #e9eaee 72%, #0b0b0e)",
    "syntax-token-keyword": "#b898f5",
    "syntax-token-string": "#5fd39b",
    "syntax-token-string-expression": "#5fd39b",
    "syntax-token-constant": "#e0b96a",
    "syntax-token-function": "#8ba0ff",
    "syntax-token-parameter": "#ff8080",
    "syntax-token-link": "#5ecfd8",
  },
};

export default graphite;
