export const redditCardSnapshots = {
  textPost: [
    '<article class="ox-reddit-card">',
    '<a class="ox-reddit-card__main" href="https://www.reddit.com/r/webdev/comments/abc123/release_notes/" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header">',
    '<span class="ox-reddit-card__network">Reddit</span>',
    '<span class="ox-reddit-card__subreddit">r/webdev</span>',
    '<span class="ox-reddit-card__author">u/octo_user</span>',
    '<time class="ox-reddit-card__time" datetime="2025-08-02T00:00:00.000Z">2025-08-02</time>',
    "</header>",
    '<h3 class="ox-reddit-card__title">Ship static Reddit cards &lt;without scripts&gt;</h3>',
    '<p class="ox-reddit-card__body">The release notes include static cards.<br>No widget script.</p>',
    '<footer class="ox-reddit-card__meta">',
    '<span class="ox-reddit-card__metric"><strong>15.4K</strong> points</span>',
    '<span class="ox-reddit-card__metric"><strong>87</strong> comments</span>',
    '<span class="ox-reddit-card__source">Open post</span>',
    "</footer>",
    "</a>",
    "</article>",
  ].join(""),

  imagePost: [
    '<article class="ox-reddit-card ox-reddit-card--image">',
    '<a class="ox-reddit-card__main" href="https://www.reddit.com/r/oxcontent/comments/img999/the_new_renderer_output/" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header">',
    '<span class="ox-reddit-card__network">Reddit</span>',
    '<span class="ox-reddit-card__subreddit">r/oxcontent</span>',
    '<span class="ox-reddit-card__author">u/image_author</span>',
    '<time class="ox-reddit-card__time" datetime="2025-08-03T00:00:00.000Z">2025-08-03</time>',
    "</header>",
    '<h3 class="ox-reddit-card__title">The new renderer output</h3>',
    '<img class="ox-reddit-card__image" src="https://preview.redd.it/render-output.png?width=960&amp;format=png" alt="" width="960" height="540" loading="lazy" decoding="async">',
    '<footer class="ox-reddit-card__meta">',
    '<span class="ox-reddit-card__metric"><strong>999</strong> points</span>',
    '<span class="ox-reddit-card__metric"><strong>12</strong> comments</span>',
    '<span class="ox-reddit-card__source">Open post</span>',
    "</footer>",
    "</a>",
    '<a class="ox-reddit-card__original" href="https://i.redd.it/render-output.png" target="_blank" rel="noopener noreferrer">Original link: i.redd.it</a>',
    "</article>",
  ].join(""),

  unavailablePost: [
    '<article class="ox-reddit-card ox-reddit-card--fallback">',
    '<a class="ox-reddit-card__main" href="https://www.reddit.com/r/webdev/comments/missing/gone/" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header">',
    '<span class="ox-reddit-card__network">Reddit</span>',
    '<span class="ox-reddit-card__subreddit">r/webdev</span>',
    "</header>",
    '<h3 class="ox-reddit-card__title">Reddit post</h3>',
    '<p class="ox-reddit-card__body">Metadata unavailable. Open the post on Reddit.</p>',
    '<footer class="ox-reddit-card__meta"><span class="ox-reddit-card__source">Open post</span></footer>',
    "</a>",
    "</article>",
    '<article class="ox-reddit-card ox-reddit-card--fallback">',
    '<a class="ox-reddit-card__main" href="https://www.reddit.com/r/webdev/s/AbC_123/" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header">',
    '<span class="ox-reddit-card__network">Reddit</span>',
    '<span class="ox-reddit-card__subreddit">r/webdev</span>',
    "</header>",
    '<h3 class="ox-reddit-card__title">Reddit post</h3>',
    '<p class="ox-reddit-card__body">Metadata unavailable. Open the post on Reddit.</p>',
    '<footer class="ox-reddit-card__meta"><span class="ox-reddit-card__source">Open post</span></footer>',
    "</a>",
    "</article>",
  ].join(""),

  unsafeInputs: [
    '<article class="ox-reddit-card error">',
    '<a class="ox-reddit-card__main" href="#" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header"><span class="ox-reddit-card__network">Reddit</span></header>',
    '<h3 class="ox-reddit-card__title">Unsupported Reddit URL</h3>',
    '<p class="ox-reddit-card__body">Use a public reddit.com post URL or redd.it share URL.</p>',
    "</a>",
    "</article>",
    '<article class="ox-reddit-card error">',
    '<a class="ox-reddit-card__main" href="#" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header"><span class="ox-reddit-card__network">Reddit</span></header>',
    '<h3 class="ox-reddit-card__title">Unsupported Reddit URL</h3>',
    '<p class="ox-reddit-card__body">Use a public reddit.com post URL or redd.it share URL.</p>',
    "</a>",
    "</article>",
  ].join(""),

  fetchDisabled: [
    '<article class="ox-reddit-card ox-reddit-card--fallback">',
    '<a class="ox-reddit-card__main" href="https://www.reddit.com/comments/abc123/" target="_blank" rel="noopener noreferrer">',
    '<header class="ox-reddit-card__header"><span class="ox-reddit-card__network">Reddit</span></header>',
    '<h3 class="ox-reddit-card__title">Reddit post</h3>',
    '<p class="ox-reddit-card__body">Metadata fetch disabled. Open the post on Reddit.</p>',
    '<footer class="ox-reddit-card__meta"><span class="ox-reddit-card__source">Open post</span></footer>',
    "</a>",
    "</article>",
  ].join(""),
} as const;
