import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Plum — Aubergine and blush.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const plum: ThemeConfig = {
  name: "plum",
  colors: {
    primary: "#8a3d75",
    primaryHover: "#6c2c5b",
    background: "#fbf8fa",
    backgroundAlt: "#f2ecf0",
    text: "#1e1520",
    textMuted: "#6b5a6d",
    border: "#e6dbe3",
    codeBackground: "#1e1520",
    codeBackgroundTop: "#1e1520",
    codeText: "#efe6ec",
  },
  darkColors: {
    primary: "#dfa3c9",
    primaryHover: "#eec2dc",
    background: "#150f18",
    backgroundAlt: "#1d1621",
    text: "#efe4ec",
    textMuted: "#9d8aa0",
    border: "#2b2130",
    codeBackground: "#100b12",
    codeBackgroundTop: "#100b12",
    codeText: "#efe4ec",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #54588f 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8f6a22 18%, transparent)",
    "color-code-line-warning-border": "#8f6a22",
    "color-code-line-error": "color-mix(in srgb, #b6394f 20%, transparent)",
    "color-code-line-error-border": "#b6394f",
    "color-code-line-add": "color-mix(in srgb, #4f7150 16%, transparent)",
    "color-code-line-add-border": "#4f7150",
    "color-code-line-remove": "color-mix(in srgb, #b6394f 14%, transparent)",
    "color-code-line-remove-border": "#b6394f",
    "color-code-line-focus": "color-mix(in srgb, #8a3d75 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #1e1520 92%, #efe6ec)",
    "color-code-title-text": "color-mix(in srgb, #efe6ec 88%, #1e1520)",
    "color-code-title-border": "color-mix(in srgb, #efe6ec 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #efe6ec 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e6dbe3 92%, transparent)",
    "color-backdrop": "rgba(88, 87, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #f2ecf0 62%, #fbf8fa)",
    "surface-line": "color-mix(in srgb, #e6dbe3 72%, #fbf8fa)",
    "brand-violet": "#8a3d75",
    "brand-cyan": "#3c6f74",
    "brand-lime": "#4f7150",
    "brand-coral": "#b6394f",
    "brand-navy": "color-mix(in srgb, #1e1520 70%, #fbf8fa)",
    "brand-violet-rgb": "138, 61, 117",
    "brand-cyan-rgb": "60, 111, 116",
    "brand-lime-rgb": "79, 113, 80",
    "brand-coral-rgb": "182, 57, 79",
    "accent-a": "#8a3d75",
    "accent-b": "#8a3d75",
    "accent-c": "#3c6f74",
    "accent-warm": "#8f6a22",
    "accent-cool": "#54588f",
    "accent-a-ink": "#8a3d75",
    "accent-b-ink": "#8a3d75",
    "accent-c-ink": "#3c6f74",
    "accent-warm-ink": "#8f6a22",
    "accent-cool-ink": "#54588f",
    "accent-coral-ink": "#b6394f",
    "shiki-foreground": "#efe6ec",
    "shiki-background": "#1e1520",
    "shiki-token-comment": "color-mix(in srgb, #efe6ec 55%, #1e1520)",
    "shiki-token-punctuation": "color-mix(in srgb, #efe6ec 72%, #1e1520)",
    "shiki-token-keyword": "#dfa3c9",
    "shiki-token-string": "#9dc79c",
    "shiki-token-string-expression": "#9dc79c",
    "shiki-token-constant": "#e3c07d",
    "shiki-token-function": "#9ea3e0",
    "shiki-token-parameter": "#ef8298",
    "shiki-token-link": "#83c3c9",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #9ea3e0 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e3c07d 18%, transparent)",
    "color-code-line-warning-border": "#e3c07d",
    "color-code-line-error": "color-mix(in srgb, #ef8298 20%, transparent)",
    "color-code-line-error-border": "#ef8298",
    "color-code-line-add": "color-mix(in srgb, #9dc79c 16%, transparent)",
    "color-code-line-add-border": "#9dc79c",
    "color-code-line-remove": "color-mix(in srgb, #ef8298 14%, transparent)",
    "color-code-line-remove-border": "#ef8298",
    "color-code-line-focus": "color-mix(in srgb, #dfa3c9 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #100b12 92%, #efe4ec)",
    "color-code-title-text": "color-mix(in srgb, #efe4ec 88%, #100b12)",
    "color-code-title-border": "color-mix(in srgb, #efe4ec 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #efe4ec 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2b2130 92%, transparent)",
    "color-backdrop": "rgba(7, 5, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #1d1621 62%, #150f18)",
    "surface-line": "color-mix(in srgb, #2b2130 72%, #150f18)",
    "brand-violet": "#dfa3c9",
    "brand-cyan": "#83c3c9",
    "brand-lime": "#9dc79c",
    "brand-coral": "#ef8298",
    "brand-navy": "color-mix(in srgb, #efe4ec 70%, #150f18)",
    "brand-violet-rgb": "223, 163, 201",
    "brand-cyan-rgb": "131, 195, 201",
    "brand-lime-rgb": "157, 199, 156",
    "brand-coral-rgb": "239, 130, 152",
    "accent-a": "#dfa3c9",
    "accent-b": "#dfa3c9",
    "accent-c": "#83c3c9",
    "accent-warm": "#e3c07d",
    "accent-cool": "#9ea3e0",
    "accent-a-ink": "#dfa3c9",
    "accent-b-ink": "#dfa3c9",
    "accent-c-ink": "#83c3c9",
    "accent-warm-ink": "#e3c07d",
    "accent-cool-ink": "#9ea3e0",
    "accent-coral-ink": "#ef8298",
    "shiki-foreground": "#efe4ec",
    "shiki-background": "#100b12",
    "shiki-token-comment": "color-mix(in srgb, #efe4ec 55%, #100b12)",
    "shiki-token-punctuation": "color-mix(in srgb, #efe4ec 72%, #100b12)",
    "shiki-token-keyword": "#dfa3c9",
    "shiki-token-string": "#9dc79c",
    "shiki-token-string-expression": "#9dc79c",
    "shiki-token-constant": "#e3c07d",
    "shiki-token-function": "#9ea3e0",
    "shiki-token-parameter": "#ef8298",
    "shiki-token-link": "#83c3c9",
  },
};

export default plum;
