import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Sand — Warm neutral stone with terracotta.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const sand: ThemeConfig = {
  name: "sand",
  colors: {
    primary: "#b4552d",
    primaryHover: "#8f4122",
    background: "#faf7f2",
    backgroundAlt: "#f0ebe2",
    text: "#1f1b16",
    textMuted: "#6d6255",
    border: "#e2dacd",
    codeBackground: "#221d18",
    codeBackgroundTop: "#221d18",
    codeText: "#f0ebe2",
  },
  darkColors: {
    primary: "#e08a5c",
    primaryHover: "#eda884",
    background: "#191510",
    backgroundAlt: "#221d17",
    text: "#f0e9dd",
    textMuted: "#9d9082",
    border: "#332b22",
    codeBackground: "#12100c",
    codeBackgroundTop: "#12100c",
    codeText: "#f0e9dd",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4a6478 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a7420 18%, transparent)",
    "color-code-line-warning-border": "#9a7420",
    "color-code-line-error": "color-mix(in srgb, #b03a2e 20%, transparent)",
    "color-code-line-error-border": "#b03a2e",
    "color-code-line-add": "color-mix(in srgb, #5c7043 16%, transparent)",
    "color-code-line-add-border": "#5c7043",
    "color-code-line-remove": "color-mix(in srgb, #b03a2e 14%, transparent)",
    "color-code-line-remove-border": "#b03a2e",
    "color-code-line-focus": "color-mix(in srgb, #b4552d 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #221d18 92%, #f0ebe2)",
    "color-code-title-text": "color-mix(in srgb, #f0ebe2 88%, #221d18)",
    "color-code-title-border": "color-mix(in srgb, #f0ebe2 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0ebe2 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e2dacd 92%, transparent)",
    "color-backdrop": "rgba(88, 86, 85, 0.62)",
    "surface-glass": "color-mix(in srgb, #f0ebe2 62%, #faf7f2)",
    "surface-line": "color-mix(in srgb, #e2dacd 72%, #faf7f2)",
    "brand-violet": "#8a5470",
    "brand-cyan": "#3f6f68",
    "brand-lime": "#5c7043",
    "brand-coral": "#b03a2e",
    "brand-navy": "color-mix(in srgb, #1f1b16 70%, #faf7f2)",
    "brand-violet-rgb": "138, 84, 112",
    "brand-cyan-rgb": "63, 111, 104",
    "brand-lime-rgb": "92, 112, 67",
    "brand-coral-rgb": "176, 58, 46",
    "accent-a": "#b4552d",
    "accent-b": "#8a5470",
    "accent-c": "#3f6f68",
    "accent-warm": "#9a7420",
    "accent-cool": "#4a6478",
    "accent-a-ink": "#b4552d",
    "accent-b-ink": "#8a5470",
    "accent-c-ink": "#3f6f68",
    "accent-warm-ink": "#8e6b1d",
    "accent-cool-ink": "#4a6478",
    "accent-coral-ink": "#b03a2e",
    "syntax-foreground": "#f0ebe2",
    "syntax-background": "#221d18",
    "syntax-token-comment": "color-mix(in srgb, #f0ebe2 55%, #221d18)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0ebe2 72%, #221d18)",
    "syntax-token-keyword": "#c396ac",
    "syntax-token-string": "#a3b878",
    "syntax-token-string-expression": "#a3b878",
    "syntax-token-constant": "#dcbb7a",
    "syntax-token-function": "#8fa8bc",
    "syntax-token-parameter": "#e08272",
    "syntax-token-link": "#7fb3a8",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8fa8bc 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dcbb7a 18%, transparent)",
    "color-code-line-warning-border": "#dcbb7a",
    "color-code-line-error": "color-mix(in srgb, #e08272 20%, transparent)",
    "color-code-line-error-border": "#e08272",
    "color-code-line-add": "color-mix(in srgb, #a3b878 16%, transparent)",
    "color-code-line-add-border": "#a3b878",
    "color-code-line-remove": "color-mix(in srgb, #e08272 14%, transparent)",
    "color-code-line-remove-border": "#e08272",
    "color-code-line-focus": "color-mix(in srgb, #e08a5c 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #12100c 92%, #f0e9dd)",
    "color-code-title-text": "color-mix(in srgb, #f0e9dd 88%, #12100c)",
    "color-code-title-border": "color-mix(in srgb, #f0e9dd 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #f0e9dd 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #332b22 92%, transparent)",
    "color-backdrop": "rgba(9, 7, 6, 0.62)",
    "surface-glass": "color-mix(in srgb, #221d17 62%, #191510)",
    "surface-line": "color-mix(in srgb, #332b22 72%, #191510)",
    "brand-violet": "#c396ac",
    "brand-cyan": "#7fb3a8",
    "brand-lime": "#a3b878",
    "brand-coral": "#e08272",
    "brand-navy": "color-mix(in srgb, #f0e9dd 70%, #191510)",
    "brand-violet-rgb": "195, 150, 172",
    "brand-cyan-rgb": "127, 179, 168",
    "brand-lime-rgb": "163, 184, 120",
    "brand-coral-rgb": "224, 130, 114",
    "accent-a": "#e08a5c",
    "accent-b": "#c396ac",
    "accent-c": "#7fb3a8",
    "accent-warm": "#dcbb7a",
    "accent-cool": "#8fa8bc",
    "accent-a-ink": "#e08a5c",
    "accent-b-ink": "#c396ac",
    "accent-c-ink": "#7fb3a8",
    "accent-warm-ink": "#dcbb7a",
    "accent-cool-ink": "#8fa8bc",
    "accent-coral-ink": "#e08272",
    "syntax-foreground": "#f0e9dd",
    "syntax-background": "#12100c",
    "syntax-token-comment": "color-mix(in srgb, #f0e9dd 55%, #12100c)",
    "syntax-token-punctuation": "color-mix(in srgb, #f0e9dd 72%, #12100c)",
    "syntax-token-keyword": "#c396ac",
    "syntax-token-string": "#a3b878",
    "syntax-token-string-expression": "#a3b878",
    "syntax-token-constant": "#dcbb7a",
    "syntax-token-function": "#8fa8bc",
    "syntax-token-parameter": "#e08272",
    "syntax-token-link": "#7fb3a8",
  },
};

export default sand;
