import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Slate — Cool grey with an electric lime edge.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const slate: ThemeConfig = {
  name: "slate",
  colors: {
    primary: "#4a7a12",
    primaryHover: "#375c0d",
    background: "#f6f7f9",
    backgroundAlt: "#eceef2",
    text: "#14181f",
    textMuted: "#61697a",
    border: "#dfe3ea",
    codeBackground: "#14181f",
    codeBackgroundTop: "#14181f",
    codeText: "#e6e9ef",
  },
  darkColors: {
    primary: "#b6e84f",
    primaryHover: "#cef07f",
    background: "#0f1216",
    backgroundAlt: "#171b21",
    text: "#e6e9ef",
    textMuted: "#868f9f",
    border: "#232830",
    codeBackground: "#0a0d10",
    codeBackgroundTop: "#0a0d10",
    codeText: "#e6e9ef",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2f5fa8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8f6d14 18%, transparent)",
    "color-code-line-warning-border": "#8f6d14",
    "color-code-line-error": "color-mix(in srgb, #c23a45 20%, transparent)",
    "color-code-line-error-border": "#c23a45",
    "color-code-line-add": "color-mix(in srgb, #4a7a12 16%, transparent)",
    "color-code-line-add-border": "#4a7a12",
    "color-code-line-remove": "color-mix(in srgb, #c23a45 14%, transparent)",
    "color-code-line-remove-border": "#c23a45",
    "color-code-line-focus": "color-mix(in srgb, #4a7a12 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #14181f 92%, #e6e9ef)",
    "color-code-title-text": "color-mix(in srgb, #e6e9ef 88%, #14181f)",
    "color-code-title-border": "color-mix(in srgb, #e6e9ef 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6e9ef 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dfe3ea 92%, transparent)",
    "color-backdrop": "rgba(86, 86, 87, 0.62)",
    "surface-glass": "color-mix(in srgb, #eceef2 62%, #f6f7f9)",
    "surface-line": "color-mix(in srgb, #dfe3ea 72%, #f6f7f9)",
    "brand-violet": "#7148ab",
    "brand-cyan": "#12727f",
    "brand-lime": "#4a7a12",
    "brand-coral": "#c23a45",
    "brand-navy": "color-mix(in srgb, #14181f 70%, #f6f7f9)",
    "brand-violet-rgb": "113, 72, 171",
    "brand-cyan-rgb": "18, 114, 127",
    "brand-lime-rgb": "74, 122, 18",
    "brand-coral-rgb": "194, 58, 69",
    "accent-a": "#4a7a12",
    "accent-b": "#7148ab",
    "accent-c": "#12727f",
    "accent-warm": "#8f6d14",
    "accent-cool": "#2f5fa8",
    "accent-a-ink": "#4a7a12",
    "accent-b-ink": "#7148ab",
    "accent-c-ink": "#12727f",
    "accent-warm-ink": "#896913",
    "accent-cool-ink": "#2f5fa8",
    "accent-coral-ink": "#c23a45",
    "syntax-foreground": "#e6e9ef",
    "syntax-background": "#14181f",
    "syntax-token-comment": "color-mix(in srgb, #e6e9ef 55%, #14181f)",
    "syntax-token-punctuation": "color-mix(in srgb, #e6e9ef 72%, #14181f)",
    "syntax-token-keyword": "#b190f2",
    "syntax-token-string": "#b6e84f",
    "syntax-token-string-expression": "#b6e84f",
    "syntax-token-constant": "#e9c86a",
    "syntax-token-function": "#77a8f0",
    "syntax-token-parameter": "#f27c88",
    "syntax-token-link": "#57cbd8",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #77a8f0 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e9c86a 18%, transparent)",
    "color-code-line-warning-border": "#e9c86a",
    "color-code-line-error": "color-mix(in srgb, #f27c88 20%, transparent)",
    "color-code-line-error-border": "#f27c88",
    "color-code-line-add": "color-mix(in srgb, #b6e84f 16%, transparent)",
    "color-code-line-add-border": "#b6e84f",
    "color-code-line-remove": "color-mix(in srgb, #f27c88 14%, transparent)",
    "color-code-line-remove-border": "#f27c88",
    "color-code-line-focus": "color-mix(in srgb, #b6e84f 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0a0d10 92%, #e6e9ef)",
    "color-code-title-text": "color-mix(in srgb, #e6e9ef 88%, #0a0d10)",
    "color-code-title-border": "color-mix(in srgb, #e6e9ef 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e6e9ef 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #232830 92%, transparent)",
    "color-backdrop": "rgba(5, 6, 8, 0.62)",
    "surface-glass": "color-mix(in srgb, #171b21 62%, #0f1216)",
    "surface-line": "color-mix(in srgb, #232830 72%, #0f1216)",
    "brand-violet": "#b190f2",
    "brand-cyan": "#57cbd8",
    "brand-lime": "#b6e84f",
    "brand-coral": "#f27c88",
    "brand-navy": "color-mix(in srgb, #e6e9ef 70%, #0f1216)",
    "brand-violet-rgb": "177, 144, 242",
    "brand-cyan-rgb": "87, 203, 216",
    "brand-lime-rgb": "182, 232, 79",
    "brand-coral-rgb": "242, 124, 136",
    "accent-a": "#b6e84f",
    "accent-b": "#b190f2",
    "accent-c": "#57cbd8",
    "accent-warm": "#e9c86a",
    "accent-cool": "#77a8f0",
    "accent-a-ink": "#b6e84f",
    "accent-b-ink": "#b190f2",
    "accent-c-ink": "#57cbd8",
    "accent-warm-ink": "#e9c86a",
    "accent-cool-ink": "#77a8f0",
    "accent-coral-ink": "#f27c88",
    "syntax-foreground": "#e6e9ef",
    "syntax-background": "#0a0d10",
    "syntax-token-comment": "color-mix(in srgb, #e6e9ef 55%, #0a0d10)",
    "syntax-token-punctuation": "color-mix(in srgb, #e6e9ef 72%, #0a0d10)",
    "syntax-token-keyword": "#b190f2",
    "syntax-token-string": "#b6e84f",
    "syntax-token-string-expression": "#b6e84f",
    "syntax-token-constant": "#e9c86a",
    "syntax-token-function": "#77a8f0",
    "syntax-token-parameter": "#f27c88",
    "syntax-token-link": "#57cbd8",
  },
};

export default slate;
