import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Palenight — Material Palenight — soft indigo.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const palenight: ThemeConfig = {
  name: "palenight",
  colors: {
    primary: "#5c53b8",
    primaryHover: "#473f96",
    background: "#fafafa",
    backgroundAlt: "#eeeef2",
    text: "#2f3350",
    textMuted: "#5f6485",
    border: "#dedee6",
    codeBackground: "#292d3e",
    codeBackgroundTop: "#292d3e",
    codeText: "#a6accd",
  },
  darkColors: {
    primary: "#c792ea",
    primaryHover: "#dcb6f2",
    background: "#292d3e",
    backgroundAlt: "#32364a",
    text: "#a6accd",
    textMuted: "#9096b6",
    border: "#3d4259",
    codeBackground: "#232635",
    codeBackgroundTop: "#232635",
    codeText: "#a6accd",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4460b8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9a7420 18%, transparent)",
    "color-code-line-warning-border": "#9a7420",
    "color-code-line-error": "color-mix(in srgb, #c3486b 20%, transparent)",
    "color-code-line-error-border": "#c3486b",
    "color-code-line-add": "color-mix(in srgb, #3f8a5f 16%, transparent)",
    "color-code-line-add-border": "#3f8a5f",
    "color-code-line-remove": "color-mix(in srgb, #c3486b 14%, transparent)",
    "color-code-line-remove-border": "#c3486b",
    "color-code-line-focus": "color-mix(in srgb, #5c53b8 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #292d3e 92%, #a6accd)",
    "color-code-title-text": "color-mix(in srgb, #a6accd 88%, #292d3e)",
    "color-code-title-border": "color-mix(in srgb, #a6accd 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #a6accd 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #dedee6 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eeeef2 62%, #fafafa)",
    "surface-line": "color-mix(in srgb, #dedee6 72%, #fafafa)",
    "brand-violet": "#8a52b0",
    "brand-cyan": "#2f7f8f",
    "brand-lime": "#3f8a5f",
    "brand-coral": "#c3486b",
    "brand-navy": "color-mix(in srgb, #2f3350 70%, #fafafa)",
    "brand-violet-rgb": "138, 82, 176",
    "brand-cyan-rgb": "47, 127, 143",
    "brand-lime-rgb": "63, 138, 95",
    "brand-coral-rgb": "195, 72, 107",
    "accent-a": "#5c53b8",
    "accent-b": "#8a52b0",
    "accent-c": "#2f7f8f",
    "accent-warm": "#9a7420",
    "accent-cool": "#4460b8",
    "accent-a-ink": "#5c53b8",
    "accent-b-ink": "#8a52b0",
    "accent-c-ink": "#2d7a89",
    "accent-warm-ink": "#8e6b1d",
    "accent-cool-ink": "#4460b8",
    "accent-coral-ink": "#c3486b",
    "shiki-foreground": "#a6accd",
    "shiki-background": "#292d3e",
    "shiki-token-comment": "color-mix(in srgb, #a6accd 55%, #292d3e)",
    "shiki-token-punctuation": "color-mix(in srgb, #a6accd 72%, #292d3e)",
    "shiki-token-keyword": "#c792ea",
    "shiki-token-string": "#c3e88d",
    "shiki-token-string-expression": "#c3e88d",
    "shiki-token-constant": "#ffcb6b",
    "shiki-token-function": "#82aaff",
    "shiki-token-parameter": "#ff5370",
    "shiki-token-link": "#89ddff",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #82aaff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffcb6b 18%, transparent)",
    "color-code-line-warning-border": "#ffcb6b",
    "color-code-line-error": "color-mix(in srgb, #ff5370 20%, transparent)",
    "color-code-line-error-border": "#ff5370",
    "color-code-line-add": "color-mix(in srgb, #c3e88d 16%, transparent)",
    "color-code-line-add-border": "#c3e88d",
    "color-code-line-remove": "color-mix(in srgb, #ff5370 14%, transparent)",
    "color-code-line-remove-border": "#ff5370",
    "color-code-line-focus": "color-mix(in srgb, #c792ea 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #232635 92%, #a6accd)",
    "color-code-title-text": "color-mix(in srgb, #a6accd 88%, #232635)",
    "color-code-title-border": "color-mix(in srgb, #a6accd 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #a6accd 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #3d4259 92%, transparent)",
    "color-backdrop": "rgba(14, 16, 22, 0.62)",
    "surface-glass": "color-mix(in srgb, #32364a 62%, #292d3e)",
    "surface-line": "color-mix(in srgb, #3d4259 72%, #292d3e)",
    "brand-violet": "#c792ea",
    "brand-cyan": "#89ddff",
    "brand-lime": "#c3e88d",
    "brand-coral": "#ff5370",
    "brand-navy": "color-mix(in srgb, #a6accd 70%, #292d3e)",
    "brand-violet-rgb": "199, 146, 234",
    "brand-cyan-rgb": "137, 221, 255",
    "brand-lime-rgb": "195, 232, 141",
    "brand-coral-rgb": "255, 83, 112",
    "accent-a": "#c792ea",
    "accent-b": "#c792ea",
    "accent-c": "#89ddff",
    "accent-warm": "#ffcb6b",
    "accent-cool": "#82aaff",
    "accent-a-ink": "#c792ea",
    "accent-b-ink": "#c792ea",
    "accent-c-ink": "#89ddff",
    "accent-warm-ink": "#ffcb6b",
    "accent-cool-ink": "#82aaff",
    "accent-coral-ink": "#ff5a76",
    "shiki-foreground": "#a6accd",
    "shiki-background": "#232635",
    "shiki-token-comment": "color-mix(in srgb, #a6accd 55%, #232635)",
    "shiki-token-punctuation": "color-mix(in srgb, #a6accd 72%, #232635)",
    "shiki-token-keyword": "#c792ea",
    "shiki-token-string": "#c3e88d",
    "shiki-token-string-expression": "#c3e88d",
    "shiki-token-constant": "#ffcb6b",
    "shiki-token-function": "#82aaff",
    "shiki-token-parameter": "#ff5370",
    "shiki-token-link": "#89ddff",
  },
};

export default palenight;
