import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Synthwave — Sunset-grid synthwave with hot magenta accents.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const synthwave: ThemeConfig = {
  name: "synthwave",
  colors: {
    primary: "#c026a3",
    primaryHover: "#9c1c83",
    background: "#fdf0f6",
    backgroundAlt: "#f7e2ee",
    text: "#2b1b3d",
    textMuted: "#6d5680",
    border: "#e6c9dc",
    codeBackground: "#241b2f",
    codeBackgroundTop: "#241b2f",
    codeText: "#ffe6ff",
  },
  darkColors: {
    primary: "#ff7edb",
    primaryHover: "#ffa9e8",
    background: "#241b2f",
    backgroundAlt: "#2d2140",
    text: "#ffe6ff",
    textMuted: "#a48fc0",
    border: "#463063",
    codeBackground: "#1a1425",
    codeBackgroundTop: "#1a1425",
    codeText: "#ffe6ff",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #5b4bc4 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #b26a00 18%, transparent)",
    "color-code-line-warning-border": "#b26a00",
    "color-code-line-error": "color-mix(in srgb, #e0245e 20%, transparent)",
    "color-code-line-error-border": "#e0245e",
    "color-code-line-add": "color-mix(in srgb, #1f8a70 16%, transparent)",
    "color-code-line-add-border": "#1f8a70",
    "color-code-line-remove": "color-mix(in srgb, #e0245e 14%, transparent)",
    "color-code-line-remove-border": "#e0245e",
    "color-code-line-focus": "color-mix(in srgb, #c026a3 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #241b2f 92%, #ffe6ff)",
    "color-code-title-text": "color-mix(in srgb, #ffe6ff 88%, #241b2f)",
    "color-code-title-border": "color-mix(in srgb, #ffe6ff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffe6ff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e6c9dc 92%, transparent)",
    "color-backdrop": "rgba(89, 84, 86, 0.62)",
    "surface-glass": "color-mix(in srgb, #f7e2ee 62%, #fdf0f6)",
    "surface-line": "color-mix(in srgb, #e6c9dc 72%, #fdf0f6)",
    "brand-violet": "#c026a3",
    "brand-cyan": "#0e7c86",
    "brand-lime": "#1f8a70",
    "brand-coral": "#e0245e",
    "brand-navy": "color-mix(in srgb, #2b1b3d 70%, #fdf0f6)",
    "brand-violet-rgb": "192, 38, 163",
    "brand-cyan-rgb": "14, 124, 134",
    "brand-lime-rgb": "31, 138, 112",
    "brand-coral-rgb": "224, 36, 94",
    "accent-a": "#c026a3",
    "accent-b": "#c026a3",
    "accent-c": "#0e7c86",
    "accent-warm": "#b26a00",
    "accent-cool": "#5b4bc4",
    "accent-a-ink": "#c026a3",
    "accent-b-ink": "#c026a3",
    "accent-c-ink": "#0d7781",
    "accent-warm-ink": "#9d5d00",
    "accent-cool-ink": "#5b4bc4",
    "accent-coral-ink": "#ce2156",
    "syntax-foreground": "#ffe6ff",
    "syntax-background": "#241b2f",
    "syntax-token-comment": "color-mix(in srgb, #ffe6ff 55%, #241b2f)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffe6ff 72%, #241b2f)",
    "syntax-token-keyword": "#ff7edb",
    "syntax-token-string": "#72f1b8",
    "syntax-token-string-expression": "#72f1b8",
    "syntax-token-constant": "#fede5d",
    "syntax-token-function": "#36f9f6",
    "syntax-token-parameter": "#fe4450",
    "syntax-token-link": "#36f9f6",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #36f9f6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fede5d 18%, transparent)",
    "color-code-line-warning-border": "#fede5d",
    "color-code-line-error": "color-mix(in srgb, #fe4450 20%, transparent)",
    "color-code-line-error-border": "#fe4450",
    "color-code-line-add": "color-mix(in srgb, #72f1b8 16%, transparent)",
    "color-code-line-add-border": "#72f1b8",
    "color-code-line-remove": "color-mix(in srgb, #fe4450 14%, transparent)",
    "color-code-line-remove-border": "#fe4450",
    "color-code-line-focus": "color-mix(in srgb, #ff7edb 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #1a1425 92%, #ffe6ff)",
    "color-code-title-text": "color-mix(in srgb, #ffe6ff 88%, #1a1425)",
    "color-code-title-border": "color-mix(in srgb, #ffe6ff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #ffe6ff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #463063 92%, transparent)",
    "color-backdrop": "rgba(13, 9, 16, 0.62)",
    "surface-glass": "color-mix(in srgb, #2d2140 62%, #241b2f)",
    "surface-line": "color-mix(in srgb, #463063 72%, #241b2f)",
    "brand-violet": "#ff7edb",
    "brand-cyan": "#36f9f6",
    "brand-lime": "#72f1b8",
    "brand-coral": "#fe4450",
    "brand-navy": "color-mix(in srgb, #ffe6ff 70%, #241b2f)",
    "brand-violet-rgb": "255, 126, 219",
    "brand-cyan-rgb": "54, 249, 246",
    "brand-lime-rgb": "114, 241, 184",
    "brand-coral-rgb": "254, 68, 80",
    "accent-a": "#ff7edb",
    "accent-b": "#ff7edb",
    "accent-c": "#36f9f6",
    "accent-warm": "#fede5d",
    "accent-cool": "#36f9f6",
    "accent-a-ink": "#ff7edb",
    "accent-b-ink": "#ff7edb",
    "accent-c-ink": "#36f9f6",
    "accent-warm-ink": "#fede5d",
    "accent-cool-ink": "#36f9f6",
    "accent-coral-ink": "#fe4450",
    "syntax-foreground": "#ffe6ff",
    "syntax-background": "#1a1425",
    "syntax-token-comment": "color-mix(in srgb, #ffe6ff 55%, #1a1425)",
    "syntax-token-punctuation": "color-mix(in srgb, #ffe6ff 72%, #1a1425)",
    "syntax-token-keyword": "#ff7edb",
    "syntax-token-string": "#72f1b8",
    "syntax-token-string-expression": "#72f1b8",
    "syntax-token-constant": "#fede5d",
    "syntax-token-function": "#36f9f6",
    "syntax-token-parameter": "#fe4450",
    "syntax-token-link": "#36f9f6",
  },
};
