import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Horizon — Warm coral and plum at dusk.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const horizon: ThemeConfig = {
  name: "horizon",
  colors: {
    primary: "#b24d44",
    primaryHover: "#9e433a",
    background: "#fdf0ed",
    backgroundAlt: "#f9e3de",
    text: "#1c1e26",
    textMuted: "#686b8d",
    border: "#eccec6",
    codeBackground: "#1c1e26",
    codeBackgroundTop: "#1c1e26",
    codeText: "#d5d8da",
  },
  darkColors: {
    primary: "#e95678",
    primaryHover: "#f0839c",
    background: "#1c1e26",
    backgroundAlt: "#232530",
    text: "#d5d8da",
    textMuted: "#8b8fa3",
    border: "#2e303e",
    codeBackground: "#16171d",
    codeBackgroundTop: "#16171d",
    codeText: "#d5d8da",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4f5fa8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #a0722a 18%, transparent)",
    "color-code-line-warning-border": "#a0722a",
    "color-code-line-error": "color-mix(in srgb, #c1544a 20%, transparent)",
    "color-code-line-error-border": "#c1544a",
    "color-code-line-add": "color-mix(in srgb, #3f7d5f 16%, transparent)",
    "color-code-line-add-border": "#3f7d5f",
    "color-code-line-remove": "color-mix(in srgb, #c1544a 14%, transparent)",
    "color-code-line-remove-border": "#c1544a",
    "color-code-line-focus": "color-mix(in srgb, #b24d44 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #1c1e26 92%, #d5d8da)",
    "color-code-title-text": "color-mix(in srgb, #d5d8da 88%, #1c1e26)",
    "color-code-title-border": "color-mix(in srgb, #d5d8da 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #d5d8da 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #eccec6 92%, transparent)",
    "color-backdrop": "rgba(89, 84, 83, 0.62)",
    "surface-glass": "color-mix(in srgb, #f9e3de 62%, #fdf0ed)",
    "surface-line": "color-mix(in srgb, #eccec6 72%, #fdf0ed)",
    "brand-violet": "#a0489c",
    "brand-cyan": "#2f7f8a",
    "brand-lime": "#3f7d5f",
    "brand-coral": "#c1544a",
    "brand-navy": "color-mix(in srgb, #1c1e26 70%, #fdf0ed)",
    "brand-violet-rgb": "160, 72, 156",
    "brand-cyan-rgb": "47, 127, 138",
    "brand-lime-rgb": "63, 125, 95",
    "brand-coral-rgb": "193, 84, 74",
    "accent-a": "#b24d44",
    "accent-b": "#a0489c",
    "accent-c": "#2f7f8a",
    "accent-warm": "#a0722a",
    "accent-cool": "#4f5fa8",
    "accent-a-ink": "#b24d44",
    "accent-b-ink": "#a0489c",
    "accent-c-ink": "#2b757f",
    "accent-warm-ink": "#8d6425",
    "accent-cool-ink": "#4f5fa8",
    "accent-coral-ink": "#b24d44",
    "syntax-foreground": "#d5d8da",
    "syntax-background": "#1c1e26",
    "syntax-token-comment": "color-mix(in srgb, #d5d8da 55%, #1c1e26)",
    "syntax-token-punctuation": "color-mix(in srgb, #d5d8da 72%, #1c1e26)",
    "syntax-token-keyword": "#b877db",
    "syntax-token-string": "#29d398",
    "syntax-token-string-expression": "#29d398",
    "syntax-token-constant": "#fab795",
    "syntax-token-function": "#26bbd9",
    "syntax-token-parameter": "#e95678",
    "syntax-token-link": "#59e1e3",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #26bbd9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #fab795 18%, transparent)",
    "color-code-line-warning-border": "#fab795",
    "color-code-line-error": "color-mix(in srgb, #e95678 20%, transparent)",
    "color-code-line-error-border": "#e95678",
    "color-code-line-add": "color-mix(in srgb, #29d398 16%, transparent)",
    "color-code-line-add-border": "#29d398",
    "color-code-line-remove": "color-mix(in srgb, #e95678 14%, transparent)",
    "color-code-line-remove-border": "#e95678",
    "color-code-line-focus": "color-mix(in srgb, #e95678 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #16171d 92%, #d5d8da)",
    "color-code-title-text": "color-mix(in srgb, #d5d8da 88%, #16171d)",
    "color-code-title-border": "color-mix(in srgb, #d5d8da 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #d5d8da 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2e303e 92%, transparent)",
    "color-backdrop": "rgba(10, 11, 13, 0.62)",
    "surface-glass": "color-mix(in srgb, #232530 62%, #1c1e26)",
    "surface-line": "color-mix(in srgb, #2e303e 72%, #1c1e26)",
    "brand-violet": "#b877db",
    "brand-cyan": "#59e1e3",
    "brand-lime": "#29d398",
    "brand-coral": "#e95678",
    "brand-navy": "color-mix(in srgb, #d5d8da 70%, #1c1e26)",
    "brand-violet-rgb": "184, 119, 219",
    "brand-cyan-rgb": "89, 225, 227",
    "brand-lime-rgb": "41, 211, 152",
    "brand-coral-rgb": "233, 86, 120",
    "accent-a": "#e95678",
    "accent-b": "#b877db",
    "accent-c": "#59e1e3",
    "accent-warm": "#fab795",
    "accent-cool": "#26bbd9",
    "accent-a-ink": "#e95678",
    "accent-b-ink": "#b877db",
    "accent-c-ink": "#59e1e3",
    "accent-warm-ink": "#fab795",
    "accent-cool-ink": "#26bbd9",
    "accent-coral-ink": "#e95678",
    "syntax-foreground": "#d5d8da",
    "syntax-background": "#16171d",
    "syntax-token-comment": "color-mix(in srgb, #d5d8da 55%, #16171d)",
    "syntax-token-punctuation": "color-mix(in srgb, #d5d8da 72%, #16171d)",
    "syntax-token-keyword": "#b877db",
    "syntax-token-string": "#29d398",
    "syntax-token-string-expression": "#29d398",
    "syntax-token-constant": "#fab795",
    "syntax-token-function": "#26bbd9",
    "syntax-token-parameter": "#e95678",
    "syntax-token-link": "#59e1e3",
  },
};
