import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Tokyo Night — Tokyo Night Day and Tokyo Night Storm.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const tokyoNight: ThemeConfig = {
  name: "tokyo-night",
  colors: {
    primary: "#235fb1",
    primaryHover: "#1a5fc4",
    background: "#e1e2e7",
    backgroundAlt: "#d6d8de",
    text: "#3760bf",
    textMuted: "#516094",
    border: "#a8aecb",
    codeBackground: "#d0d5e3",
    codeBackgroundTop: "#d0d5e3",
    codeText: "#3358b0",
  },
  darkColors: {
    primary: "#7aa2f7",
    primaryHover: "#9eb8fa",
    background: "#1a1b26",
    backgroundAlt: "#24283b",
    text: "#c0caf5",
    textMuted: "#8386a1",
    border: "#2f334d",
    codeBackground: "#16161e",
    codeBackgroundTop: "#16161e",
    codeText: "#c0caf5",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2e7de9 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8c6c3e 18%, transparent)",
    "color-code-line-warning-border": "#8c6c3e",
    "color-code-line-error": "color-mix(in srgb, #f52a65 20%, transparent)",
    "color-code-line-error-border": "#f52a65",
    "color-code-line-add": "color-mix(in srgb, #587539 16%, transparent)",
    "color-code-line-add-border": "#587539",
    "color-code-line-remove": "color-mix(in srgb, #f52a65 14%, transparent)",
    "color-code-line-remove-border": "#f52a65",
    "color-code-line-focus": "color-mix(in srgb, #235fb1 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #d0d5e3 92%, #3358b0)",
    "color-code-title-text": "color-mix(in srgb, #3358b0 88%, #d0d5e3)",
    "color-code-title-border": "color-mix(in srgb, #3358b0 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #3358b0 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #a8aecb 92%, transparent)",
    "color-backdrop": "rgba(79, 79, 81, 0.62)",
    "surface-glass": "color-mix(in srgb, #d6d8de 62%, #e1e2e7)",
    "surface-line": "color-mix(in srgb, #a8aecb 72%, #e1e2e7)",
    "brand-violet": "#9854f1",
    "brand-cyan": "#007197",
    "brand-lime": "#587539",
    "brand-coral": "#f52a65",
    "brand-navy": "color-mix(in srgb, #3760bf 70%, #e1e2e7)",
    "brand-violet-rgb": "152, 84, 241",
    "brand-cyan-rgb": "0, 113, 151",
    "brand-lime-rgb": "88, 117, 57",
    "brand-coral-rgb": "245, 42, 101",
    "accent-a": "#235fb1",
    "accent-b": "#9854f1",
    "accent-c": "#007197",
    "accent-warm": "#8c6c3e",
    "accent-cool": "#2e7de9",
    "accent-a-ink": "#235fb1",
    "accent-b-ink": "#7a43c1",
    "accent-c-ink": "#006c91",
    "accent-warm-ink": "#7b5f37",
    "accent-cool-ink": "#235fb1",
    "accent-coral-ink": "#ba204d",
    "shiki-foreground": "#3358b0",
    "shiki-background": "#d0d5e3",
    "shiki-token-comment": "color-mix(in srgb, #3358b0 55%, #d0d5e3)",
    "shiki-token-punctuation": "color-mix(in srgb, #3358b0 72%, #d0d5e3)",
    "shiki-token-keyword": "#9854f1",
    "shiki-token-string": "#587539",
    "shiki-token-string-expression": "#587539",
    "shiki-token-constant": "#8c6c3e",
    "shiki-token-function": "#2e7de9",
    "shiki-token-parameter": "#f52a65",
    "shiki-token-link": "#007197",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #7aa2f7 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e0af68 18%, transparent)",
    "color-code-line-warning-border": "#e0af68",
    "color-code-line-error": "color-mix(in srgb, #f7768e 20%, transparent)",
    "color-code-line-error-border": "#f7768e",
    "color-code-line-add": "color-mix(in srgb, #9ece6a 16%, transparent)",
    "color-code-line-add-border": "#9ece6a",
    "color-code-line-remove": "color-mix(in srgb, #f7768e 14%, transparent)",
    "color-code-line-remove-border": "#f7768e",
    "color-code-line-focus": "color-mix(in srgb, #7aa2f7 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #16161e 92%, #c0caf5)",
    "color-code-title-text": "color-mix(in srgb, #c0caf5 88%, #16161e)",
    "color-code-title-border": "color-mix(in srgb, #c0caf5 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #c0caf5 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #2f334d 92%, transparent)",
    "color-backdrop": "rgba(9, 9, 13, 0.62)",
    "surface-glass": "color-mix(in srgb, #24283b 62%, #1a1b26)",
    "surface-line": "color-mix(in srgb, #2f334d 72%, #1a1b26)",
    "brand-violet": "#bb9af7",
    "brand-cyan": "#7dcfff",
    "brand-lime": "#9ece6a",
    "brand-coral": "#f7768e",
    "brand-navy": "color-mix(in srgb, #c0caf5 70%, #1a1b26)",
    "brand-violet-rgb": "187, 154, 247",
    "brand-cyan-rgb": "125, 207, 255",
    "brand-lime-rgb": "158, 206, 106",
    "brand-coral-rgb": "247, 118, 142",
    "accent-a": "#7aa2f7",
    "accent-b": "#bb9af7",
    "accent-c": "#7dcfff",
    "accent-warm": "#e0af68",
    "accent-cool": "#7aa2f7",
    "accent-a-ink": "#7aa2f7",
    "accent-b-ink": "#bb9af7",
    "accent-c-ink": "#7dcfff",
    "accent-warm-ink": "#e0af68",
    "accent-cool-ink": "#7aa2f7",
    "accent-coral-ink": "#f7768e",
    "shiki-foreground": "#c0caf5",
    "shiki-background": "#16161e",
    "shiki-token-comment": "color-mix(in srgb, #c0caf5 55%, #16161e)",
    "shiki-token-punctuation": "color-mix(in srgb, #c0caf5 72%, #16161e)",
    "shiki-token-keyword": "#bb9af7",
    "shiki-token-string": "#9ece6a",
    "shiki-token-string-expression": "#9ece6a",
    "shiki-token-constant": "#e0af68",
    "shiki-token-function": "#7aa2f7",
    "shiki-token-parameter": "#f7768e",
    "shiki-token-link": "#7dcfff",
  },
};

export default tokyoNight;
