import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Everforest — Everforest light and dark, medium contrast.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const everforest: ThemeConfig = {
  name: "everforest",
  colors: {
    primary: "#2e769e",
    primaryHover: "#2a759d",
    background: "#fdf6e3",
    backgroundAlt: "#f4f0d9",
    text: "#5c6a72",
    textMuted: "#687467",
    border: "#e0dcc7",
    codeBackground: "#f4f0d9",
    codeBackgroundTop: "#f4f0d9",
    codeText: "#5c6a72",
  },
  darkColors: {
    primary: "#7fbbb3",
    primaryHover: "#a7d1cb",
    background: "#2d353b",
    backgroundAlt: "#343f44",
    text: "#d3c6aa",
    textMuted: "#9da9a0",
    border: "#475258",
    codeBackground: "#272e33",
    codeBackgroundTop: "#272e33",
    codeText: "#d3c6aa",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #3a94c5 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dfa000 18%, transparent)",
    "color-code-line-warning-border": "#dfa000",
    "color-code-line-error": "color-mix(in srgb, #f85552 20%, transparent)",
    "color-code-line-error-border": "#f85552",
    "color-code-line-add": "color-mix(in srgb, #8da101 16%, transparent)",
    "color-code-line-add-border": "#8da101",
    "color-code-line-remove": "color-mix(in srgb, #f85552 14%, transparent)",
    "color-code-line-remove-border": "#f85552",
    "color-code-line-focus": "color-mix(in srgb, #2e769e 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f4f0d9 92%, #5c6a72)",
    "color-code-title-text": "color-mix(in srgb, #5c6a72 88%, #f4f0d9)",
    "color-code-title-border": "color-mix(in srgb, #5c6a72 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #5c6a72 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e0dcc7 92%, transparent)",
    "color-backdrop": "rgba(89, 86, 79, 0.62)",
    "surface-glass": "color-mix(in srgb, #f4f0d9 62%, #fdf6e3)",
    "surface-line": "color-mix(in srgb, #e0dcc7 72%, #fdf6e3)",
    "brand-violet": "#df69ba",
    "brand-cyan": "#35a77c",
    "brand-lime": "#8da101",
    "brand-coral": "#f85552",
    "brand-navy": "color-mix(in srgb, #5c6a72 70%, #fdf6e3)",
    "brand-violet-rgb": "223, 105, 186",
    "brand-cyan-rgb": "53, 167, 124",
    "brand-lime-rgb": "141, 161, 1",
    "brand-coral-rgb": "248, 85, 82",
    "accent-a": "#2e769e",
    "accent-b": "#df69ba",
    "accent-c": "#35a77c",
    "accent-warm": "#dfa000",
    "accent-cool": "#3a94c5",
    "accent-a-ink": "#2e769e",
    "accent-b-ink": "#a9508d",
    "accent-c-ink": "#287f5e",
    "accent-warm-ink": "#8f6600",
    "accent-cool-ink": "#2e769e",
    "accent-coral-ink": "#c64442",
    "syntax-foreground": "#5c6a72",
    "syntax-background": "#f4f0d9",
    "syntax-token-comment": "color-mix(in srgb, #5c6a72 55%, #f4f0d9)",
    "syntax-token-punctuation": "color-mix(in srgb, #5c6a72 72%, #f4f0d9)",
    "syntax-token-keyword": "#df69ba",
    "syntax-token-string": "#8da101",
    "syntax-token-string-expression": "#8da101",
    "syntax-token-constant": "#dfa000",
    "syntax-token-function": "#3a94c5",
    "syntax-token-parameter": "#f85552",
    "syntax-token-link": "#35a77c",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #7fbbb3 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #dbbc7f 18%, transparent)",
    "color-code-line-warning-border": "#dbbc7f",
    "color-code-line-error": "color-mix(in srgb, #e67e80 20%, transparent)",
    "color-code-line-error-border": "#e67e80",
    "color-code-line-add": "color-mix(in srgb, #a7c080 16%, transparent)",
    "color-code-line-add-border": "#a7c080",
    "color-code-line-remove": "color-mix(in srgb, #e67e80 14%, transparent)",
    "color-code-line-remove-border": "#e67e80",
    "color-code-line-focus": "color-mix(in srgb, #7fbbb3 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #272e33 92%, #d3c6aa)",
    "color-code-title-text": "color-mix(in srgb, #d3c6aa 88%, #272e33)",
    "color-code-title-border": "color-mix(in srgb, #d3c6aa 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #d3c6aa 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #475258 92%, transparent)",
    "color-backdrop": "rgba(16, 19, 21, 0.62)",
    "surface-glass": "color-mix(in srgb, #343f44 62%, #2d353b)",
    "surface-line": "color-mix(in srgb, #475258 72%, #2d353b)",
    "brand-violet": "#d699b6",
    "brand-cyan": "#83c092",
    "brand-lime": "#a7c080",
    "brand-coral": "#e67e80",
    "brand-navy": "color-mix(in srgb, #d3c6aa 70%, #2d353b)",
    "brand-violet-rgb": "214, 153, 182",
    "brand-cyan-rgb": "131, 192, 146",
    "brand-lime-rgb": "167, 192, 128",
    "brand-coral-rgb": "230, 126, 128",
    "accent-a": "#7fbbb3",
    "accent-b": "#d699b6",
    "accent-c": "#83c092",
    "accent-warm": "#dbbc7f",
    "accent-cool": "#7fbbb3",
    "accent-a-ink": "#7fbbb3",
    "accent-b-ink": "#d699b6",
    "accent-c-ink": "#83c092",
    "accent-warm-ink": "#dbbc7f",
    "accent-cool-ink": "#7fbbb3",
    "accent-coral-ink": "#e67e80",
    "syntax-foreground": "#d3c6aa",
    "syntax-background": "#272e33",
    "syntax-token-comment": "color-mix(in srgb, #d3c6aa 55%, #272e33)",
    "syntax-token-punctuation": "color-mix(in srgb, #d3c6aa 72%, #272e33)",
    "syntax-token-keyword": "#d699b6",
    "syntax-token-string": "#a7c080",
    "syntax-token-string-expression": "#a7c080",
    "syntax-token-constant": "#dbbc7f",
    "syntax-token-function": "#7fbbb3",
    "syntax-token-parameter": "#e67e80",
    "syntax-token-link": "#83c092",
  },
};

export default everforest;
