import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Emerald — Vivid green over deep slate — the conference-badge palette.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const emerald: ThemeConfig = {
  name: "emerald",
  colors: {
    primary: "#0e8462",
    primaryHover: "#0a664c",
    background: "#fbfdfc",
    backgroundAlt: "#eef5f2",
    text: "#1b2b33",
    textMuted: "#526d78",
    border: "#d9eae3",
    codeBackground: "#253440",
    codeBackgroundTop: "#253440",
    codeText: "#e7f2ee",
  },
  darkColors: {
    primary: "#42d99f",
    primaryHover: "#74e8bb",
    background: "#101c22",
    backgroundAlt: "#17262e",
    text: "#e7f2ee",
    textMuted: "#82a099",
    border: "#22343c",
    codeBackground: "#0b1418",
    codeBackgroundTop: "#0b1418",
    codeText: "#e7f2ee",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #2a6a9c 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #8f6c10 18%, transparent)",
    "color-code-line-warning-border": "#8f6c10",
    "color-code-line-error": "color-mix(in srgb, #c9453f 20%, transparent)",
    "color-code-line-error-border": "#c9453f",
    "color-code-line-add": "color-mix(in srgb, #0f8a66 16%, transparent)",
    "color-code-line-add-border": "#0f8a66",
    "color-code-line-remove": "color-mix(in srgb, #c9453f 14%, transparent)",
    "color-code-line-remove-border": "#c9453f",
    "color-code-line-focus": "color-mix(in srgb, #0e8462 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #253440 92%, #e7f2ee)",
    "color-code-title-text": "color-mix(in srgb, #e7f2ee 88%, #253440)",
    "color-code-title-border": "color-mix(in srgb, #e7f2ee 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e7f2ee 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #d9eae3 92%, transparent)",
    "color-backdrop": "rgba(88, 89, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eef5f2 62%, #fbfdfc)",
    "surface-line": "color-mix(in srgb, #d9eae3 72%, #fbfdfc)",
    "brand-violet": "#7c4a91",
    "brand-cyan": "#12808a",
    "brand-lime": "#0f8a66",
    "brand-coral": "#c9453f",
    "brand-navy": "color-mix(in srgb, #1b2b33 70%, #fbfdfc)",
    "brand-violet-rgb": "124, 74, 145",
    "brand-cyan-rgb": "18, 128, 138",
    "brand-lime-rgb": "15, 138, 102",
    "brand-coral-rgb": "201, 69, 63",
    "accent-a": "#0e8462",
    "accent-b": "#7c4a91",
    "accent-c": "#12808a",
    "accent-warm": "#8f6c10",
    "accent-cool": "#2a6a9c",
    "accent-a-ink": "#0e8462",
    "accent-b-ink": "#7c4a91",
    "accent-c-ink": "#12808a",
    "accent-warm-ink": "#8f6c10",
    "accent-cool-ink": "#2a6a9c",
    "accent-coral-ink": "#c9453f",
    "syntax-foreground": "#e7f2ee",
    "syntax-background": "#253440",
    "syntax-token-comment": "color-mix(in srgb, #e7f2ee 55%, #253440)",
    "syntax-token-punctuation": "color-mix(in srgb, #e7f2ee 72%, #253440)",
    "syntax-token-keyword": "#cf94d8",
    "syntax-token-string": "#42d99f",
    "syntax-token-string-expression": "#42d99f",
    "syntax-token-constant": "#ffd166",
    "syntax-token-function": "#6fc0e8",
    "syntax-token-parameter": "#ff7d72",
    "syntax-token-link": "#4fd8d0",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #6fc0e8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffd166 18%, transparent)",
    "color-code-line-warning-border": "#ffd166",
    "color-code-line-error": "color-mix(in srgb, #ff7d72 20%, transparent)",
    "color-code-line-error-border": "#ff7d72",
    "color-code-line-add": "color-mix(in srgb, #42d99f 16%, transparent)",
    "color-code-line-add-border": "#42d99f",
    "color-code-line-remove": "color-mix(in srgb, #ff7d72 14%, transparent)",
    "color-code-line-remove-border": "#ff7d72",
    "color-code-line-focus": "color-mix(in srgb, #42d99f 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0b1418 92%, #e7f2ee)",
    "color-code-title-text": "color-mix(in srgb, #e7f2ee 88%, #0b1418)",
    "color-code-title-border": "color-mix(in srgb, #e7f2ee 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e7f2ee 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #22343c 92%, transparent)",
    "color-backdrop": "rgba(6, 10, 12, 0.62)",
    "surface-glass": "color-mix(in srgb, #17262e 62%, #101c22)",
    "surface-line": "color-mix(in srgb, #22343c 72%, #101c22)",
    "brand-violet": "#cf94d8",
    "brand-cyan": "#4fd8d0",
    "brand-lime": "#42d99f",
    "brand-coral": "#ff7d72",
    "brand-navy": "color-mix(in srgb, #e7f2ee 70%, #101c22)",
    "brand-violet-rgb": "207, 148, 216",
    "brand-cyan-rgb": "79, 216, 208",
    "brand-lime-rgb": "66, 217, 159",
    "brand-coral-rgb": "255, 125, 114",
    "accent-a": "#42d99f",
    "accent-b": "#cf94d8",
    "accent-c": "#4fd8d0",
    "accent-warm": "#ffd166",
    "accent-cool": "#6fc0e8",
    "accent-a-ink": "#42d99f",
    "accent-b-ink": "#cf94d8",
    "accent-c-ink": "#4fd8d0",
    "accent-warm-ink": "#ffd166",
    "accent-cool-ink": "#6fc0e8",
    "accent-coral-ink": "#ff7d72",
    "syntax-foreground": "#e7f2ee",
    "syntax-background": "#0b1418",
    "syntax-token-comment": "color-mix(in srgb, #e7f2ee 55%, #0b1418)",
    "syntax-token-punctuation": "color-mix(in srgb, #e7f2ee 72%, #0b1418)",
    "syntax-token-keyword": "#cf94d8",
    "syntax-token-string": "#42d99f",
    "syntax-token-string-expression": "#42d99f",
    "syntax-token-constant": "#ffd166",
    "syntax-token-function": "#6fc0e8",
    "syntax-token-parameter": "#ff7d72",
    "syntax-token-link": "#4fd8d0",
  },
};
