import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Stage — Event poster — deep indigo with coral and acid yellow.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const stage: ThemeConfig = {
  name: "stage",
  colors: {
    primary: "#4b32c3",
    primaryHover: "#37238f",
    background: "#f8f7fc",
    backgroundAlt: "#eeecf7",
    text: "#14122b",
    textMuted: "#5c5880",
    border: "#ddd9ee",
    codeBackground: "#14122b",
    codeBackgroundTop: "#14122b",
    codeText: "#e9e6f6",
  },
  darkColors: {
    primary: "#ff6b5b",
    primaryHover: "#ff9184",
    background: "#0f0d1f",
    backgroundAlt: "#161331",
    text: "#e9e6f6",
    textMuted: "#8c86ad",
    border: "#221d42",
    codeBackground: "#0a0817",
    codeBackgroundTop: "#0a0817",
    codeText: "#e9e6f6",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4b32c3 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #9c7409 18%, transparent)",
    "color-code-line-warning-border": "#9c7409",
    "color-code-line-error": "color-mix(in srgb, #d63b35 20%, transparent)",
    "color-code-line-error-border": "#d63b35",
    "color-code-line-add": "color-mix(in srgb, #2f7a52 16%, transparent)",
    "color-code-line-add-border": "#2f7a52",
    "color-code-line-remove": "color-mix(in srgb, #d63b35 14%, transparent)",
    "color-code-line-remove-border": "#d63b35",
    "color-code-line-focus": "color-mix(in srgb, #4b32c3 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #14122b 92%, #e9e6f6)",
    "color-code-title-text": "color-mix(in srgb, #e9e6f6 88%, #14122b)",
    "color-code-title-border": "color-mix(in srgb, #e9e6f6 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e9e6f6 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #ddd9ee 92%, transparent)",
    "color-backdrop": "rgba(87, 86, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #eeecf7 62%, #f8f7fc)",
    "surface-line": "color-mix(in srgb, #ddd9ee 72%, #f8f7fc)",
    "brand-violet": "#b82f84",
    "brand-cyan": "#0f7d8c",
    "brand-lime": "#2f7a52",
    "brand-coral": "#d63b35",
    "brand-navy": "color-mix(in srgb, #14122b 70%, #f8f7fc)",
    "brand-violet-rgb": "184, 47, 132",
    "brand-cyan-rgb": "15, 125, 140",
    "brand-lime-rgb": "47, 122, 82",
    "brand-coral-rgb": "214, 59, 53",
    "accent-a": "#4b32c3",
    "accent-b": "#b82f84",
    "accent-c": "#0f7d8c",
    "accent-warm": "#9c7409",
    "accent-cool": "#4b32c3",
    "accent-a-ink": "#4b32c3",
    "accent-b-ink": "#b82f84",
    "accent-c-ink": "#0f7d8c",
    "accent-warm-ink": "#906b08",
    "accent-cool-ink": "#4b32c3",
    "accent-coral-ink": "#cd3933",
    "syntax-foreground": "#e9e6f6",
    "syntax-background": "#14122b",
    "syntax-token-comment": "color-mix(in srgb, #e9e6f6 55%, #14122b)",
    "syntax-token-punctuation": "color-mix(in srgb, #e9e6f6 72%, #14122b)",
    "syntax-token-keyword": "#ff6bc4",
    "syntax-token-string": "#5fd39a",
    "syntax-token-string-expression": "#5fd39a",
    "syntax-token-constant": "#ffe14f",
    "syntax-token-function": "#8f7dff",
    "syntax-token-parameter": "#ff6b5b",
    "syntax-token-link": "#4fd6e0",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #8f7dff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffe14f 18%, transparent)",
    "color-code-line-warning-border": "#ffe14f",
    "color-code-line-error": "color-mix(in srgb, #ff6b5b 20%, transparent)",
    "color-code-line-error-border": "#ff6b5b",
    "color-code-line-add": "color-mix(in srgb, #5fd39a 16%, transparent)",
    "color-code-line-add-border": "#5fd39a",
    "color-code-line-remove": "color-mix(in srgb, #ff6b5b 14%, transparent)",
    "color-code-line-remove-border": "#ff6b5b",
    "color-code-line-focus": "color-mix(in srgb, #ff6b5b 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #0a0817 92%, #e9e6f6)",
    "color-code-title-text": "color-mix(in srgb, #e9e6f6 88%, #0a0817)",
    "color-code-title-border": "color-mix(in srgb, #e9e6f6 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #e9e6f6 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #221d42 92%, transparent)",
    "color-backdrop": "rgba(5, 5, 11, 0.62)",
    "surface-glass": "color-mix(in srgb, #161331 62%, #0f0d1f)",
    "surface-line": "color-mix(in srgb, #221d42 72%, #0f0d1f)",
    "brand-violet": "#ff6bc4",
    "brand-cyan": "#4fd6e0",
    "brand-lime": "#5fd39a",
    "brand-coral": "#ff6b5b",
    "brand-navy": "color-mix(in srgb, #e9e6f6 70%, #0f0d1f)",
    "brand-violet-rgb": "255, 107, 196",
    "brand-cyan-rgb": "79, 214, 224",
    "brand-lime-rgb": "95, 211, 154",
    "brand-coral-rgb": "255, 107, 91",
    "accent-a": "#ff6b5b",
    "accent-b": "#ff6bc4",
    "accent-c": "#4fd6e0",
    "accent-warm": "#ffe14f",
    "accent-cool": "#8f7dff",
    "accent-a-ink": "#ff6b5b",
    "accent-b-ink": "#ff6bc4",
    "accent-c-ink": "#4fd6e0",
    "accent-warm-ink": "#ffe14f",
    "accent-cool-ink": "#8f7dff",
    "accent-coral-ink": "#ff6b5b",
    "syntax-foreground": "#e9e6f6",
    "syntax-background": "#0a0817",
    "syntax-token-comment": "color-mix(in srgb, #e9e6f6 55%, #0a0817)",
    "syntax-token-punctuation": "color-mix(in srgb, #e9e6f6 72%, #0a0817)",
    "syntax-token-keyword": "#ff6bc4",
    "syntax-token-string": "#5fd39a",
    "syntax-token-string-expression": "#5fd39a",
    "syntax-token-constant": "#ffe14f",
    "syntax-token-function": "#8f7dff",
    "syntax-token-parameter": "#ff6b5b",
    "syntax-token-link": "#4fd6e0",
  },
};
