import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Material — Material Theme Lighter and Material Theme Darker.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const materialDarker: ThemeConfig = {
  name: "material-darker",
  colors: {
    primary: "#4d7a76",
    primaryHover: "#627076",
    background: "#fafafa",
    backgroundAlt: "#fafafa",
    text: "#627076",
    textMuted: "#627076",
    border: "#00000020",
    codeBackground: "#fafafa",
    codeBackgroundTop: "#fafafa",
    codeText: "#627076",
  },
  darkColors: {
    primary: "#80cbc4",
    primaryHover: "#eeffff",
    background: "#212121",
    backgroundAlt: "#212121",
    text: "#eeffff",
    textMuted: "#8b8b8b",
    border: "#00000030",
    codeBackground: "#212121",
    codeBackgroundTop: "#212121",
    codeText: "#eeffff",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #6182b8 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #e2931d 18%, transparent)",
    "color-code-line-warning-border": "#e2931d",
    "color-code-line-error": "color-mix(in srgb, #e53935 20%, transparent)",
    "color-code-line-error-border": "#e53935",
    "color-code-line-add": "color-mix(in srgb, #91b859 16%, transparent)",
    "color-code-line-add-border": "#91b859",
    "color-code-line-remove": "color-mix(in srgb, #e53935 14%, transparent)",
    "color-code-line-remove-border": "#e53935",
    "color-code-line-focus": "color-mix(in srgb, #4d7a76 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #fafafa 92%, #627076)",
    "color-code-title-text": "color-mix(in srgb, #627076 88%, #fafafa)",
    "color-code-title-border": "color-mix(in srgb, #627076 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #627076 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #00000020 92%, transparent)",
    "color-backdrop": "rgba(88, 88, 88, 0.62)",
    "surface-glass": "color-mix(in srgb, #fafafa 62%, #fafafa)",
    "surface-line": "color-mix(in srgb, #00000020 72%, #fafafa)",
    "brand-violet": "#9c3eda",
    "brand-cyan": "#39adb5",
    "brand-lime": "#91b859",
    "brand-coral": "#e53935",
    "brand-navy": "color-mix(in srgb, #627076 70%, #fafafa)",
    "brand-violet-rgb": "156, 62, 218",
    "brand-cyan-rgb": "57, 173, 181",
    "brand-lime-rgb": "145, 184, 89",
    "brand-coral-rgb": "229, 57, 53",
    "accent-a": "#4d7a76",
    "accent-b": "#9c3eda",
    "accent-c": "#39adb5",
    "accent-warm": "#e2931d",
    "accent-cool": "#6182b8",
    "accent-a-ink": "#4d7a76",
    "accent-b-ink": "#9c3eda",
    "accent-c-ink": "#297d82",
    "accent-warm-ink": "#9a6414",
    "accent-cool-ink": "#5572a2",
    "accent-coral-ink": "#d33431",
    "syntax-foreground": "#90a4ae",
    "syntax-background": "#fafafa",
    "syntax-token-comment": "#90a4ae",
    "syntax-token-punctuation": "#39adb5",
    "syntax-token-keyword": "#f76d47",
    "syntax-token-string": "#91b859",
    "syntax-token-string-expression": "#91b859",
    "syntax-token-constant": "#f76d47",
    "syntax-token-function": "#6182b8",
    "syntax-token-parameter": "#e53935",
    "syntax-token-link": "#80cbc4",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #82aaff 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ffcb6b 18%, transparent)",
    "color-code-line-warning-border": "#ffcb6b",
    "color-code-line-error": "color-mix(in srgb, #f07178 20%, transparent)",
    "color-code-line-error-border": "#f07178",
    "color-code-line-add": "color-mix(in srgb, #c3e88d 16%, transparent)",
    "color-code-line-add-border": "#c3e88d",
    "color-code-line-remove": "color-mix(in srgb, #f07178 14%, transparent)",
    "color-code-line-remove-border": "#f07178",
    "color-code-line-focus": "color-mix(in srgb, #80cbc4 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #212121 92%, #eeffff)",
    "color-code-title-text": "color-mix(in srgb, #eeffff 88%, #212121)",
    "color-code-title-border": "color-mix(in srgb, #eeffff 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #eeffff 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #00000030 92%, transparent)",
    "color-backdrop": "rgba(12, 12, 12, 0.62)",
    "surface-glass": "color-mix(in srgb, #212121 62%, #212121)",
    "surface-line": "color-mix(in srgb, #00000030 72%, #212121)",
    "brand-violet": "#c792ea",
    "brand-cyan": "#89ddff",
    "brand-lime": "#c3e88d",
    "brand-coral": "#f07178",
    "brand-navy": "color-mix(in srgb, #eeffff 70%, #212121)",
    "brand-violet-rgb": "199, 146, 234",
    "brand-cyan-rgb": "137, 221, 255",
    "brand-lime-rgb": "195, 232, 141",
    "brand-coral-rgb": "240, 113, 120",
    "accent-a": "#80cbc4",
    "accent-b": "#c792ea",
    "accent-c": "#89ddff",
    "accent-warm": "#ffcb6b",
    "accent-cool": "#82aaff",
    "accent-a-ink": "#80cbc4",
    "accent-b-ink": "#c792ea",
    "accent-c-ink": "#89ddff",
    "accent-warm-ink": "#ffcb6b",
    "accent-cool-ink": "#82aaff",
    "accent-coral-ink": "#f07178",
    "syntax-foreground": "#eeffff",
    "syntax-background": "#212121",
    "syntax-token-comment": "#545454",
    "syntax-token-punctuation": "#89ddff",
    "syntax-token-keyword": "#f78c6c",
    "syntax-token-string": "#c3e88d",
    "syntax-token-string-expression": "#c3e88d",
    "syntax-token-constant": "#f78c6c",
    "syntax-token-function": "#82aaff",
    "syntax-token-parameter": "#f07178",
    "syntax-token-link": "#80cbc4",
  },
};
