use super::*;

#[test]
fn generate_docs_markdown_group_order_reorders_module_index() {
    fn entry(name: &str, kind: &str) -> JsDocsMarkdownEntry {
        JsDocsMarkdownEntry {
            name: name.to_string(),
            kind: kind.to_string(),
            description: String::new(),
            params: None,
            returns: None,
            throws: None,
            examples: None,
            tags: None,
            private: false,
            file: format!("/repo/src/{name}.ts"),
            line: 1,
            end_line: 1,
            signature: Some(format!("export declare const {name}: unknown")),
            extends: None,
            implements: None,
            has_body: None,
            members: None,
            type_parameters: None,
        }
    }
    let docs = vec![JsDocsMarkdownModule {
        description: None,
        file: "default".to_string(),
        source_path: None,
        examples: None,
        tags: None,
        entries: vec![entry("alpha", "function"), entry("VERSION", "variable")],
    }];

    let markdown = generate_docs_markdown(
        docs,
        Some(JsDocsMarkdownOptions {
            path_strategy: Some("typedoc".to_string()),
            render_style: Some("markdown".to_string()),
            group_order: Some(vec!["Variables".to_string(), "Functions".to_string()]),
            ..Default::default()
        }),
    );
    let index = markdown.get("default/index.md").unwrap();

    assert!(index.find("## Variables").unwrap() < index.find("## Functions").unwrap());
}

fn docs_markdown_module() -> Vec<JsDocsMarkdownModule> {
    vec![JsDocsMarkdownModule {
        description: None,
        file: "default".to_string(),
        source_path: None,
        examples: None,
        tags: None,
        entries: vec![JsDocsMarkdownEntry {
            name: "cli".to_string(),
            kind: "function".to_string(),
            description: "Run.".to_string(),
            params: None,
            returns: None,
            throws: None,
            examples: None,
            tags: None,
            private: false,
            file: "/repo/src/cli.ts".to_string(),
            line: 1,
            end_line: 1,
            signature: Some("export function cli(): void".to_string()),
            extends: None,
            implements: None,
            has_body: None,
            members: None,
            type_parameters: None,
        }],
    }]
}

#[test]
fn generate_docs_markdown_render_stats_option_toggles_stats_summary() {
    fn options(render_stats: Option<bool>) -> JsDocsMarkdownOptions {
        JsDocsMarkdownOptions {
            path_strategy: Some("typedoc".to_string()),
            render_style: Some("markdown".to_string()),
            render_stats,
            ..Default::default()
        }
    }

    // Default (None -> true) keeps the stats summary.
    let with_stats = generate_docs_markdown(docs_markdown_module(), Some(options(None)));
    assert!(with_stats.get("default/index.md").unwrap().contains("symbols ·"));

    // Explicit false omits it.
    let without_stats = generate_docs_markdown(docs_markdown_module(), Some(options(Some(false))));
    assert!(!without_stats.get("default/index.md").unwrap().contains("symbols ·"));
}

#[test]
fn generate_docs_markdown_render_generated_by_option_toggles_attribution() {
    fn options(render_generated_by: Option<bool>) -> JsDocsMarkdownOptions {
        JsDocsMarkdownOptions {
            path_strategy: Some("typedoc".to_string()),
            render_style: Some("markdown".to_string()),
            render_stats: Some(false),
            render_generated_by,
            ..Default::default()
        }
    }

    // Default (None -> true) keeps the generated-by attribution.
    let with_generated_by = generate_docs_markdown(docs_markdown_module(), Some(options(None)));
    assert!(with_generated_by.get("index.md").unwrap().contains("Generated by [Ox Content]"));

    // Explicit false omits it and leaves the Modules heading directly after
    // the H1 when stats are also disabled.
    let without_generated_by =
        generate_docs_markdown(docs_markdown_module(), Some(options(Some(false))));
    let root = without_generated_by.get("index.md").unwrap();
    assert!(!root.contains("Generated by [Ox Content]"));
    assert!(root.starts_with("# API Documentation\n\n## Modules\n\n"));
}
