import type { ThemeConfig } from "@ox-content/vite-plugin";

/**
 * Flexoki — Ink and paper, tuned for e-ink-like calm.
 *
 * Color only: no layout, no texture, no typography. Compose it under any
 * `@ox-content/theme-*` skin, or use it on its own over the default theme.
 *
 * Generated from `scripts/theme-colors/palettes.json`; edit that file and run
 * `node scripts/theme-colors/generate.mjs` rather than editing this by hand.
 */
export const flexoki: ThemeConfig = {
  name: "flexoki",
  colors: {
    primary: "#237e76",
    primaryHover: "#1c6c66",
    background: "#fffcf0",
    backgroundAlt: "#f2f0e5",
    text: "#100f0f",
    textMuted: "#6f6e69",
    border: "#e6e4d9",
    codeBackground: "#f2f0e5",
    codeBackgroundTop: "#f2f0e5",
    codeText: "#100f0f",
  },
  darkColors: {
    primary: "#3aa99f",
    primaryHover: "#5abdb3",
    background: "#100f0f",
    backgroundAlt: "#1c1b1a",
    text: "#fffcf0",
    textMuted: "#878580",
    border: "#282726",
    codeBackground: "#1c1b1a",
    codeBackgroundTop: "#1c1b1a",
    codeText: "#fffcf0",
  },
  tokens: {
    "color-code-line-highlight": "color-mix(in srgb, #205ea6 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #ad8301 18%, transparent)",
    "color-code-line-warning-border": "#ad8301",
    "color-code-line-error": "color-mix(in srgb, #af3029 20%, transparent)",
    "color-code-line-error-border": "#af3029",
    "color-code-line-add": "color-mix(in srgb, #66800b 16%, transparent)",
    "color-code-line-add-border": "#66800b",
    "color-code-line-remove": "color-mix(in srgb, #af3029 14%, transparent)",
    "color-code-line-remove-border": "#af3029",
    "color-code-line-focus": "color-mix(in srgb, #237e76 16%, transparent)",
    "color-code-line-dim": "0.45",
    "color-code-title-bg": "color-mix(in srgb, #f2f0e5 92%, #100f0f)",
    "color-code-title-text": "color-mix(in srgb, #100f0f 88%, #f2f0e5)",
    "color-code-title-border": "color-mix(in srgb, #100f0f 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #100f0f 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #e6e4d9 92%, transparent)",
    "color-backdrop": "rgba(89, 88, 84, 0.62)",
    "surface-glass": "color-mix(in srgb, #f2f0e5 62%, #fffcf0)",
    "surface-line": "color-mix(in srgb, #e6e4d9 72%, #fffcf0)",
    "brand-violet": "#a02f6f",
    "brand-cyan": "#24837b",
    "brand-lime": "#66800b",
    "brand-coral": "#af3029",
    "brand-navy": "color-mix(in srgb, #100f0f 70%, #fffcf0)",
    "brand-violet-rgb": "160, 47, 111",
    "brand-cyan-rgb": "36, 131, 123",
    "brand-lime-rgb": "102, 128, 11",
    "brand-coral-rgb": "175, 48, 41",
    "accent-a": "#237e76",
    "accent-b": "#a02f6f",
    "accent-c": "#24837b",
    "accent-warm": "#ad8301",
    "accent-cool": "#205ea6",
    "accent-a-ink": "#237e76",
    "accent-b-ink": "#a02f6f",
    "accent-c-ink": "#237e76",
    "accent-warm-ink": "#916e01",
    "accent-cool-ink": "#205ea6",
    "accent-coral-ink": "#af3029",
    "syntax-foreground": "#100f0f",
    "syntax-background": "#f2f0e5",
    "syntax-token-comment": "color-mix(in srgb, #100f0f 55%, #f2f0e5)",
    "syntax-token-punctuation": "color-mix(in srgb, #100f0f 72%, #f2f0e5)",
    "syntax-token-keyword": "#a02f6f",
    "syntax-token-string": "#66800b",
    "syntax-token-string-expression": "#66800b",
    "syntax-token-constant": "#ad8301",
    "syntax-token-function": "#205ea6",
    "syntax-token-parameter": "#af3029",
    "syntax-token-link": "#24837b",
  },
  darkTokens: {
    "color-code-line-highlight": "color-mix(in srgb, #4385be 16%, transparent)",
    "color-code-line-warning": "color-mix(in srgb, #d0a215 18%, transparent)",
    "color-code-line-warning-border": "#d0a215",
    "color-code-line-error": "color-mix(in srgb, #d14d41 20%, transparent)",
    "color-code-line-error-border": "#d14d41",
    "color-code-line-add": "color-mix(in srgb, #879a39 16%, transparent)",
    "color-code-line-add-border": "#879a39",
    "color-code-line-remove": "color-mix(in srgb, #d14d41 14%, transparent)",
    "color-code-line-remove-border": "#d14d41",
    "color-code-line-focus": "color-mix(in srgb, #3aa99f 16%, transparent)",
    "color-code-line-dim": "0.35",
    "color-code-title-bg": "color-mix(in srgb, #1c1b1a 92%, #fffcf0)",
    "color-code-title-text": "color-mix(in srgb, #fffcf0 88%, #1c1b1a)",
    "color-code-title-border": "color-mix(in srgb, #fffcf0 22%, transparent)",
    "color-code-line-number": "color-mix(in srgb, #fffcf0 48%, transparent)",
    "color-code-frame-border": "color-mix(in srgb, #282726 92%, transparent)",
    "color-backdrop": "rgba(6, 5, 5, 0.62)",
    "surface-glass": "color-mix(in srgb, #1c1b1a 62%, #100f0f)",
    "surface-line": "color-mix(in srgb, #282726 72%, #100f0f)",
    "brand-violet": "#ce5d97",
    "brand-cyan": "#3aa99f",
    "brand-lime": "#879a39",
    "brand-coral": "#d14d41",
    "brand-navy": "color-mix(in srgb, #fffcf0 70%, #100f0f)",
    "brand-violet-rgb": "206, 93, 151",
    "brand-cyan-rgb": "58, 169, 159",
    "brand-lime-rgb": "135, 154, 57",
    "brand-coral-rgb": "209, 77, 65",
    "accent-a": "#3aa99f",
    "accent-b": "#ce5d97",
    "accent-c": "#3aa99f",
    "accent-warm": "#d0a215",
    "accent-cool": "#4385be",
    "accent-a-ink": "#3aa99f",
    "accent-b-ink": "#ce5d97",
    "accent-c-ink": "#3aa99f",
    "accent-warm-ink": "#d0a215",
    "accent-cool-ink": "#4385be",
    "accent-coral-ink": "#d35449",
    "syntax-foreground": "#fffcf0",
    "syntax-background": "#1c1b1a",
    "syntax-token-comment": "color-mix(in srgb, #fffcf0 55%, #1c1b1a)",
    "syntax-token-punctuation": "color-mix(in srgb, #fffcf0 72%, #1c1b1a)",
    "syntax-token-keyword": "#ce5d97",
    "syntax-token-string": "#879a39",
    "syntax-token-string-expression": "#879a39",
    "syntax-token-constant": "#d0a215",
    "syntax-token-function": "#4385be",
    "syntax-token-parameter": "#d14d41",
    "syntax-token-link": "#3aa99f",
  },
};
