import type { ResolvedSearchOptions } from "../types";

const DEFAULT_HOSTED_ENDPOINT = "/search";

/**
 * JSON-embeds a value so it stays inert inside a script tag.
 */
export function embedSearchJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

export function hostedClientOptions(options: ResolvedSearchOptions) {
  return {
    enabled: options.enabled,
    limit: options.limit,
    prefix: options.prefix,
    fuzzy: options.fuzzy,
    placeholder: options.placeholder,
    hotkey: options.hotkey,
    provider: "hosted" as const,
  };
}

export function failClosedSearchModule(options: ResolvedSearchOptions): string {
  return `// Search module generated by ox-content
const searchOptions = ${embedSearchJson(hostedClientOptions(options))};
export function parseSearchQuery(query) {
  const raw = String(query || "");
  const text = raw.trim();
  return {
    raw,
    text,
    terms: text ? text.toLowerCase().split(/\\s+/).filter(Boolean) : [],
    phrases: [],
    prefixes: [],
    filters: [],
    scopes: [],
  };
}
export function formatSearchResultForCard(result, index = 0) {
  const metadata = result?.metadata || { scopes: result?.scopes || [], section: "" };
  const ranking = result?.ranking || { score: Number(result?.score || 0), fields: [], reasons: [] };
  const idSeed = String(result?.id || result?.url || index || "result")
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return {
    id: "ox-search-result-" + (idSeed || index),
    role: "option",
    title: String(result?.title || ""),
    url: String(result?.url || ""),
    snippet: String(result?.snippet || ""),
    metadata,
    ranking,
    badges: [],
    ariaLabel: String(result?.ariaLabel || result?.aria_label || result?.title || "Untitled search result"),
  };
}
export function createSearchUiState(query, results = [], options = {}) {
  const parsedQuery = parseSearchQuery(query);
  const cards = results.map((result, index) => formatSearchResultForCard(result, index));
  const active = Boolean(parsedQuery.text);
  const status = options.isComposing || options.composing
    ? "composing"
    : !active
      ? "empty"
      : options.loading
        ? "loading"
        : cards.length
          ? "results"
          : "no-results";
  return {
    status,
    parsedQuery,
    refinements: [],
    resultCount: cards.length,
    activeDescendant: cards[0]?.id || "",
    ariaLiveMessage:
      status === "empty"
        ? "Type to search"
        : status === "loading" || status === "composing"
          ? "Loading search results"
          : status === "no-results"
            ? "No results"
            : cards.length + " results",
    cards,
  };
}
export async function search() { return []; }
export { searchOptions };
export default { search, searchOptions, parseSearchQuery, createSearchUiState, formatSearchResultForCard };
`;
}

export { DEFAULT_HOSTED_ENDPOINT };
