name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  pull_request:
    branches: ["**"]
    paths:
      - .github/workflows/**

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: blacksmith-32vcpu-ubuntu-2404
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Install zizmor
        run: cargo install zizmor --version 1.26.1 --locked

      - name: Run zizmor
        run: zizmor --no-exit-codes --format sarif .github/workflows/ > zizmor.sarif
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: zizmor.sarif
