name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  pull_request:
    branches: ["**"]
    paths:
      - .github/workflows/**

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: blacksmith-32vcpu-ubuntu-2404
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Install zizmor
        run: cargo install zizmor --version 1.26.1 --locked

      - name: Run zizmor
        run: zizmor --no-exit-codes --format sarif .github/workflows/ > zizmor.sarif
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: zizmor.sarif
